//! Dumps zeron's diff results as canonical JSON lines for the Zig parity
//! tests in apps/zeron/src/diff/parity_test.zig.
//!
//! Inputs: apps/zeron/src/diff/testdata/{patches,pairs}.txt (generated by
//! apps/zeron/scripts/gen_diff_corpus.py). Outputs next to them:
//!   patches.jsonl — zeron_ui::changes::parse_patch files, plus per file
//!                   file_notices, split_pairs / split_pairs_upto(3) per hunk
//!                   and truncate_file_lines(5)
//!   pairs.jsonl   — similar 2.7.0 TextDiff ops (lines/words/chars), grouped
//!                   ops (3), iter_changes, iter_inline_changes, and
//!                   zeron_ui::transcript::diff_to_file
//!
//! `iter_inline_changes` needs similar's `inline` feature, which zeron's
//! build leaves off, so similar is rebuilt from the registry source:
//!   S=~/.cargo/registry/src/*/similar-2.7.0
//!   rustc --edition 2018 -O --crate-type rlib --crate-name similar \
//!     --cfg 'feature="text"' --cfg 'feature="inline"' $S/src/lib.rs -o /tmp/libsimilar_inline.rlib
//!   D=$ZERON/target/debug/deps
//!   rustc --edition 2024 -O diff_parity.rs -o /tmp/diff_parity -L $D \
//!     --extern zeron_ui=$(ls $D/libzeron_ui-*.rlib) --extern zeron_proto=$(ls $D/libzeron_proto-*.rlib) \
//!     --extern similar=/tmp/libsimilar_inline.rlib
//!   /tmp/diff_parity apps/zeron/src/diff/testdata

use std::fmt::Write as _;

use similar::{ChangeTag, DiffOp, TextDiff};
use zeron_ui::changes::{FileDiff, FileStatus, LineKind};

fn esc(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
}

fn opt_u32(out: &mut String, v: Option<u32>) {
    match v {
        Some(v) => {
            let _ = write!(out, "{v}");
        }
        None => out.push_str("null"),
    }
}

fn opt_usize(out: &mut String, v: Option<usize>) {
    match v {
        Some(v) => {
            let _ = write!(out, "{v}");
        }
        None => out.push_str("null"),
    }
}

fn strs(out: &mut String, v: &[String]) {
    out.push('[');
    for (i, s) in v.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        esc(out, s);
    }
    out.push(']');
}

fn file(out: &mut String, f: &FileDiff) {
    out.push_str("{\"path\":");
    esc(out, &f.path);
    out.push_str(",\"old_path\":");
    match &f.old_path {
        Some(p) => esc(out, p),
        None => out.push_str("null"),
    }
    let status = match f.status {
        FileStatus::Added => "added",
        FileStatus::Deleted => "deleted",
        FileStatus::Modified => "modified",
        FileStatus::Renamed => "renamed",
    };
    let _ = write!(out, ",\"status\":\"{status}\",\"binary\":{},\"notices\":", f.binary);
    strs(out, &f.notices);
    out.push_str(",\"hunks\":[");
    for (i, h) in f.hunks.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push_str("{\"header\":");
        esc(out, &h.header);
        out.push_str(",\"lines\":[");
        for (j, l) in h.lines.iter().enumerate() {
            if j > 0 {
                out.push(',');
            }
            let k = match l.kind {
                LineKind::Context => "context",
                LineKind::Add => "add",
                LineKind::Del => "del",
                LineKind::Meta => "meta",
            };
            let _ = write!(out, "[\"{k}\",");
            opt_u32(out, l.old_no);
            out.push(',');
            opt_u32(out, l.new_no);
            out.push(',');
            esc(out, &l.text);
            out.push(']');
        }
        out.push_str("]}");
    }
    let _ = write!(
        out,
        "],\"additions\":{},\"deletions\":{},\"max_line\":{}}}",
        f.additions, f.deletions, f.max_line
    );
}

fn pairs(out: &mut String, ps: &[(Option<u32>, Option<u32>)]) {
    out.push('[');
    for (i, (l, r)) in ps.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push('[');
        opt_u32(out, *l);
        out.push(',');
        opt_u32(out, *r);
        out.push(']');
    }
    out.push(']');
}

fn ops(out: &mut String, os: &[DiffOp]) {
    out.push('[');
    for (i, op) in os.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        match *op {
            DiffOp::Equal {
                old_index,
                new_index,
                len,
            } => {
                let _ = write!(out, "[\"E\",{old_index},{new_index},{len}]");
            }
            DiffOp::Delete {
                old_index,
                old_len,
                new_index,
            } => {
                let _ = write!(out, "[\"D\",{old_index},{old_len},{new_index}]");
            }
            DiffOp::Insert {
                old_index,
                new_index,
                new_len,
            } => {
                let _ = write!(out, "[\"I\",{old_index},{new_index},{new_len}]");
            }
            DiffOp::Replace {
                old_index,
                old_len,
                new_index,
                new_len,
            } => {
                let _ = write!(out, "[\"R\",{old_index},{old_len},{new_index},{new_len}]");
            }
        }
    }
    out.push(']');
}

fn tag(t: ChangeTag) -> &'static str {
    match t {
        ChangeTag::Equal => "equal",
        ChangeTag::Delete => "delete",
        ChangeTag::Insert => "insert",
    }
}

fn read_docs(path: &str) -> Vec<String> {
    let bytes = std::fs::read(path).expect("read corpus");
    let mut docs = Vec::new();
    let mut at = 0;
    while at < bytes.len() {
        let nl = at + bytes[at..].iter().position(|&b| b == b'\n').unwrap();
        let len: usize = std::str::from_utf8(&bytes[at..nl]).unwrap().parse().unwrap();
        let start = nl + 1;
        docs.push(String::from_utf8(bytes[start..start + len].to_vec()).unwrap());
        at = start + len + 1;
    }
    docs
}

fn main() {
    let dir = std::env::args().nth(1).expect("testdata dir");
    let mut po = String::new();
    for patch in read_docs(&format!("{dir}/patches.txt")) {
        let files = zeron_ui::changes::parse_patch(&patch);
        po.push('[');
        for (i, f) in files.iter().enumerate() {
            if i > 0 {
                po.push(',');
            }
            po.push_str("{\"file\":");
            file(&mut po, f);
            po.push_str(",\"notices\":");
            strs(&mut po, &zeron_ui::changes::file_notices(f));
            po.push_str(",\"pairs\":[");
            for (j, h) in f.hunks.iter().enumerate() {
                if j > 0 {
                    po.push(',');
                }
                pairs(&mut po, &zeron_ui::changes::split_pairs(&h.lines));
            }
            po.push_str("],\"pairs3\":[");
            for (j, h) in f.hunks.iter().enumerate() {
                if j > 0 {
                    po.push(',');
                }
                pairs(&mut po, &zeron_ui::changes::split_pairs_upto(&h.lines, 3));
            }
            po.push_str("],\"truncated\":");
            let mut t = f.clone();
            zeron_ui::changes::truncate_file_lines(&mut t, 5);
            file(&mut po, &t);
            po.push('}');
        }
        po.push_str("]\n");
    }
    std::fs::write(format!("{dir}/patches.jsonl"), po).unwrap();

    let docs = read_docs(&format!("{dir}/pairs.txt"));
    let mut out = String::new();
    for pair in docs.chunks(2) {
        let (old_raw, new) = (&pair[0], &pair[1]);
        let old_opt = if old_raw == "\0" { None } else { Some(old_raw.clone()) };
        let old = old_opt.clone().unwrap_or_default();
        let lines = TextDiff::from_lines(old.as_str(), new.as_str());
        out.push_str("{\"lines\":");
        ops(&mut out, lines.ops());
        out.push_str(",\"grouped\":[");
        for (i, g) in lines.grouped_ops(3).iter().enumerate() {
            if i > 0 {
                out.push(',');
            }
            ops(&mut out, g);
        }
        out.push_str("],\"changes\":[");
        let mut first = true;
        for op in lines.ops() {
            for c in lines.iter_changes(op) {
                if !first {
                    out.push(',');
                }
                first = false;
                let _ = write!(out, "[\"{}\",", tag(c.tag()));
                opt_usize(&mut out, c.old_index());
                out.push(',');
                opt_usize(&mut out, c.new_index());
                out.push(',');
                esc(&mut out, c.value());
                out.push(']');
            }
        }
        out.push_str("],\"inline\":[");
        let mut first = true;
        for op in lines.ops() {
            for c in lines.iter_inline_changes(op) {
                if !first {
                    out.push(',');
                }
                first = false;
                let _ = write!(out, "[\"{}\",", tag(c.tag()));
                opt_usize(&mut out, c.old_index());
                out.push(',');
                opt_usize(&mut out, c.new_index());
                out.push_str(",[");
                for (k, (emph, v)) in c.values().iter().enumerate() {
                    if k > 0 {
                        out.push(',');
                    }
                    let _ = write!(out, "[{emph},");
                    esc(&mut out, v);
                    out.push(']');
                }
                out.push_str("]]");
            }
        }
        out.push_str("],\"words\":");
        ops(&mut out, TextDiff::from_words(old.as_str(), new.as_str()).ops());
        out.push_str(",\"chars\":");
        if old.len() + new.len() <= 6000 {
            ops(&mut out, TextDiff::from_chars(old.as_str(), new.as_str()).ops());
        } else {
            out.push_str("null");
        }
        out.push_str(",\"file\":");
        let tool = zeron_proto::ToolDiff {
            path: "dir/file.rs".into(),
            old_text: old_opt,
            new_text: new.clone(),
        };
        file(&mut out, &zeron_ui::transcript::diff_to_file(&tool));
        out.push_str("}\n");
    }
    std::fs::write(format!("{dir}/pairs.jsonl"), out).unwrap();
    eprintln!("wrote {} pairs", docs.len() / 2);
}
