//! Dumps the composer route choreography (zeron `crates/ui/src/composer_dock.rs`
//! + `composer_dock/panel_handoff.rs`) for a deterministic corpus as Zig
//! source, for apps/zeron/src/ui/shell/testdata/dock_parity.zig (compared by
//! the "dock parity" test in apps/zeron/src/ui/shell/dock.zig).
//!
//! The state machine is private to the gpui crate, so it is lifted VERBATIM
//! into generated includes; only visibility is relaxed, the module path of
//! `panel_handoff::` is flattened, `crate::motion::lerp` is the catalog lerp
//! and `crate::motion::speed_scale()` is 1 (no ZERON_MOTION_SCALE):
//!   Z=$ZERON  S=/tmp/dock_parity && mkdir -p $S
//!   sed -n '18,470p' $Z/crates/ui/src/composer_dock.rs \
//!     | sed 's/pub(crate) //; s/crate::motion::speed_scale()/1.0f32/g; s/crate::motion::lerp/lerp/g; s/panel_handoff:://g' > $S/dock.rs
//!   sed -n '1,57p' $Z/crates/ui/src/composer_dock/panel_handoff.rs \
//!     | sed 's/pub(super) //; /^use std::time::Instant;/d; /^\/\/!/d' > $S/handoff.rs
//!   DOCK_LIFTED=$S/dock.rs HANDOFF_LIFTED=$S/handoff.rs rustc --edition 2024 dock_parity.rs -o $S/run
//!   $S/run > apps/zeron/src/ui/shell/testdata/dock_parity.zig
//!
//! Clock order per frame matches `Shell::render` → `DockedComposer::prepaint`:
//! `observe_pane`, `tick`, `layout_width`, then the prepaint position step.

#![allow(dead_code)]

use std::time::{Duration, Instant};

fn lerp(from: f32, to: f32, t: f32) -> f32 {
    from + (to - from) * t
}

include!(env!("HANDOFF_LIFTED"));
include!(env!("DOCK_LIFTED"));

/// `DockedComposer::prepaint`'s commit (the element itself needs a window).
fn place(state: &mut DockState, x: f32, y: f32, reduced: bool, now: Instant) -> f32 {
    let docked = state.frame.docked;
    let position = state.position_at(x, y, reduced, now);
    state.last_geometry = Some(now);
    state.last_docked = docked;
    state.position = Some(position);
    let unsettled = (position.0.value - x).abs() > 0.1
        || (position.1.value - y).abs() > 0.1
        || position.0.velocity.abs() > 1.0
        || position.1.velocity.abs() > 1.0;
    state.moving = !reduced
        && (unsettled || state.frame.active || state.width.is_some_and(|width| width.active()));
    position.1.value
}

fn f(v: f32) -> String {
    format!("{v:?}")
}

fn main() {
    println!("//! Generated by apps/zeron/scripts/dock_parity.rs from zeron composer_dock.rs. Do not edit.");
    println!();

    // ---- glides ----
    println!("pub const GlideCase = struct {{ start: f32, duration: f32, steps: []const [2]f32, values: []const [2]f32 }};");
    println!("pub const glides = [_]GlideCase{{");
    let cases: &[(f32, f32, &[(f32, f32)])] = &[
        (0.0, 0.42, &[(100.0, 0.016), (100.0, 0.016), (100.0, 0.033), (100.0, 0.05), (100.0, 0.1), (100.0, 0.2), (100.0, 0.5)]),
        (240.0, 0.47, &[(560.0, 0.0), (560.0, 0.016), (560.0, 0.016), (100.0, 0.0), (100.0, 0.016), (100.0, 0.05), (100.0, 0.3), (100.0, 1.0)]),
        (1.0, 0.42, &[(0.0, 0.008), (0.0, 0.008), (1.0, 0.016), (0.0, 0.2), (0.0, 0.4)]),
    ];
    for (start, duration, steps) in cases {
        let mut g = Glide::new(*start);
        let mut values = Vec::new();
        for (target, secs) in steps.iter() {
            g.advance(*target, *secs, *duration);
            values.push((g.value, g.velocity));
        }
        print!("    .{{ .start = {}, .duration = {}, .steps = &.{{", f(*start), f(*duration));
        for (t, s) in steps.iter() {
            print!(" .{{ {}, {} }},", f(*t), f(*s));
        }
        print!(" }}, .values = &.{{");
        for (v, vel) in values {
            print!(" .{{ {}, {} }},", f(v), f(vel));
        }
        println!(" }} }},");
    }
    println!("}};");
    println!();

    // ---- visuals ----
    println!("pub const VisualCase = struct {{ kind: u8, time: f32, from: [4]f32, out: [4]f32 }};");
    println!("pub const visuals = [_]VisualCase{{");
    let froms = [
        Visuals::settled(false),
        Visuals::settled(true),
        Visuals { transcript: 0.4, selectors: 0.7, footer: 0.2, dissolve: 0.55 },
    ];
    for kind in 0u8..4 {
        for from in &froms {
            for step in 0..=20 {
                let time = step as f32 / 20.0 * 1.1;
                let v = match kind {
                    0 => from.advance(true, time),
                    1 => from.advance(false, time),
                    2 => from.enter_with_panel(time),
                    _ => from.return_from_panel(time),
                };
                println!(
                    "    .{{ .kind = {kind}, .time = {}, .from = .{{ {}, {}, {}, {} }}, .out = .{{ {}, {}, {}, {} }} }},",
                    f(time),
                    f(from.transcript), f(from.selectors), f(from.footer), f(from.dissolve),
                    f(v.transcript), f(v.selectors), f(v.footer), f(v.dissolve)
                );
            }
        }
    }
    println!("}};");
    println!();

    // ---- whole routes ----
    println!("pub const Frame = struct {{ t_ms: u64, docked: bool, pane_width: f32, width: f32, x: f32, y: f32, out_active: bool, out_amount: f32, out_visuals: [4]f32, out_opacity: f32, out_width: f32, out_y: f32 }};");
    println!("pub const RouteCase = struct {{ frames: []const Frame }};");
    println!("pub const routes = [_]RouteCase{{");
    // (t_ms, docked, pane_width, width, y) script per case.
    type Step = (u64, bool, f32, f32, f32);
    let mut scripts: Vec<Vec<Step>> = Vec::new();
    // 1. Hero → thread, settles.
    scripts.push((0..50).map(|i| (i * 16, i >= 3, 0.0, if i >= 3 { 760.0 } else { 680.0 }, if i >= 3 { 620.0 } else { 330.0 })).collect());
    // 2. Thread → hero, reversed mid-flight back to the thread.
    scripts.push((0..60).map(|i| {
        let docked = !(3..12).contains(&i);
        (i * 16, docked, 0.0, if docked { 760.0 } else { 680.0 }, if docked { 620.0 } else { 330.0 })
    }).collect());
    // 3. Hero → thread with the right pane opening (panel hand-off).
    scripts.push((0..40).map(|i| {
        let docked = i >= 2;
        (i * 16, docked, if docked { 480.0 } else { 0.0 }, if docked { 520.0 } else { 680.0 }, if docked { 620.0 } else { 330.0 })
    }).collect());
    // 4. Thread (pane open) → hero: the return hand-off; then an idle gap.
    scripts.push((0..40).map(|i| {
        let docked = i < 2;
        let t = if i < 30 { i * 16 } else { i * 16 + 2000 };
        (t, docked, if docked { 480.0 } else { 0.0 }, if docked { 520.0 } else { 680.0 }, if docked { 620.0 } else { 330.0 })
    }).collect());
    let base = Instant::now();
    for script in &scripts {
        let mut state = DockState::default();
        println!("    .{{ .frames = &.{{");
        for &(t_ms, docked, pane_width, width, y) in script {
            let now = base + Duration::from_millis(t_ms);
            state.observe_pane(docked, pane_width, true, now);
            let frame = state.tick(docked, false, now);
            let w = state.layout_width(width, false, now);
            let py = place(&mut state, 40.0, y, false, now);
            println!(
                "        .{{ .t_ms = {t_ms}, .docked = {docked}, .pane_width = {}, .width = {}, .x = 40, .y = {}, .out_active = {}, .out_amount = {}, .out_visuals = .{{ {}, {}, {}, {} }}, .out_opacity = {}, .out_width = {}, .out_y = {} }},",
                f(pane_width), f(width), f(y), frame.active, f(frame.amount),
                f(frame.transcript()), f(frame.selectors()), f(frame.footer()), f(frame.dissolve()),
                f(state.opacity()), f(w), f(py)
            );
        }
        println!("    }} }},");
    }
    println!("}};");
}
