#!/usr/bin/env python3
"""Generate apps/zeron/src/engine/methods.zig from the Rust engine sources.

Method names come from `pub mod methods` in crates/rpc/src/lib.rs (the single
source of truth for both ends). Stream-vs-unary is derived from the engine's
dispatch (`crates/engine/src/rpc.rs`): an arm whose body yields
`RpcReply::Stream` is a stream.

Usage: gen_methods.py [ZERON_REPO] > apps/zeron/src/engine/methods.zig
"""
import re
import sys
from pathlib import Path

repo = Path(sys.argv[1] if len(sys.argv) > 1 else "/home/user/zeron")
lib = (repo / "crates/rpc/src/lib.rs").read_text()
rpc = (repo / "crates/engine/src/rpc.rs").read_text()

block = re.search(r"pub mod methods \{(.*?)\n\}", lib, re.S)
if not block:
    sys.exit("methods module not found")

methods = []  # (CONST_NAME, wire, doc lines)
doc = []
for raw in block.group(1).splitlines():
    line = raw.strip()
    if line.startswith("///"):
        doc.append(line[3:].strip())
        continue
    m = re.match(r'pub const (\w+): &str = "(\w+)";', line)
    if m:
        methods.append((m.group(1), m.group(2), doc))
    doc = []

# Dispatch arms: `methods::A | methods::B => body`. The body runs until the
# next line indented at or left of the arm (the next arm or the match's end).
arm_start = re.compile(r"^(\s*)(?:\|\s*)?methods::(\w+)((?:\s*\|\s*methods::\w+)*)\s*=>", re.M)
streams = set()
lines = rpc.splitlines()
for i, line in enumerate(lines):
    m = arm_start.match(line)
    if not m:
        continue
    indent = len(m.group(1))
    body = [line[m.end():]]
    for nxt in lines[i + 1:]:
        stripped = nxt.strip()
        if stripped and len(nxt) - len(nxt.lstrip()) <= indent:
            break
        body.append(nxt)
    if "RpcReply::Stream" in "\n".join(body):
        streams.update([m.group(2)] + re.findall(r"methods::(\w+)", m.group(3)))

known = {c for c, _, _ in methods}
streams &= known


def snake(const: str) -> str:
    return const.lower()


out = []
out.append("//! RPC method names, generated by apps/zeron/scripts/gen_methods.py from")
out.append("//! zeron `crates/rpc/src/lib.rs` (`pub mod methods`). Do not edit by hand.")
out.append("//! Stream classification is derived from `crates/engine/src/rpc.rs`.")
out.append("")
out.append("pub const Kind = enum { unary, stream };")
out.append("")
out.append("pub const Method = enum {")
for const, wire, d in methods:
    for line in d:
        out.append(f"    /// {line}" if line else "    ///")
    out.append(f"    {wire},")
out.append("")
out.append("    /// Wire name (identical to the tag name).")
out.append("    pub fn name(m: Method) []const u8 {")
out.append("        return @tagName(m);")
out.append("    }")
out.append("")
out.append("    /// Whether the engine answers with `{id,item}*` frames instead of one `{id,ok}`.")
out.append("    pub fn kind(m: Method) Kind {")
out.append("        return switch (m) {")
if streams:
    names = sorted(w for c, w, _ in methods if c in streams)
    out.append("            " + ",\n            ".join(f".{n}" for n in names) + " => .stream,")
out.append("            else => .unary,")
out.append("        };")
out.append("    }")
out.append("};")
out.append("")
out.append(f"/// Number of methods in zeron_rpc::methods.")
out.append(f"pub const count = {len(methods)};")
out.append("")
out.append("/// Every method, in source order.")
out.append("pub const all = std.enums.values(Method);")
out.append("")
out.append("const std = @import(\"std\");")
out.append("")
out.append("test \"method table is complete\" {")
out.append(f"    try std.testing.expectEqual(@as(usize, {len(methods)}), all.len);")
out.append("    try std.testing.expectEqual(Kind.stream, Method.WatchDocMessages.kind());")
out.append("    try std.testing.expectEqual(Kind.unary, Method.EngineInfo.kind());")
out.append("}")
print("\n".join(out))
sys.stderr.write(f"{len(methods)} methods, {len(streams)} streams: {sorted(streams)}\n")
