#!/usr/bin/env python3
"""Generate apps/zeron/src/assets.zig: embedded control icons, fonts and file icons.

Icon names and order come from the `icon_assets![...]` table in zeron's
`crates/ui/src/icons.rs`, so `Icon` tags match the Rust constants
(`icons::PEN_NEW_SQUARE` -> `.pen_new_square`). Fonts and file icons are
enumerated from apps/zeron/assets/.

The build (see `addZeronAssets` in build.zig) places assets.zig next to a copy
of apps/zeron/assets/ as `assets/`, which is what the `@embedFile` paths below
are relative to.

Usage: gen_assets.py [ZERON_REPO] > apps/zeron/src/assets.zig
"""
import re
import sys
from pathlib import Path


def zig_fmt(source):
    """Format with `zig fmt --stdin` when zig is on PATH; else return as is."""
    import shutil
    import subprocess
    if not shutil.which("zig"):
        return source
    res = subprocess.run(["zig", "fmt", "--stdin"], input=source, capture_output=True, text=True)
    return res.stdout if res.returncode == 0 else source

repo = Path(sys.argv[1] if len(sys.argv) > 1 else "/home/user/zeron")
here = Path(__file__).resolve().parent.parent  # apps/zeron
assets = here / "assets"

icons_rs = (repo / "crates/ui/src/icons.rs").read_text()
table = re.search(r"icon_assets!\[(.*?)\n\];", icons_rs, re.S)
if not table:
    sys.exit("icon_assets! table not found")
icons = re.findall(r'\((\w+),\s*"([\w-]+)"\)', table.group(1))
for _, name in icons:
    if not (assets / "icons" / f"{name}.svg").is_file():
        sys.exit(f"missing icon asset: {name}.svg (re-copy crates/ui/assets/icons)")
unregistered = sorted(p.stem for p in (assets / "icons").glob("*.svg") if p.stem not in {n for _, n in icons})

STYLE = {  # file suffix -> (weight, italic)
    "": (400, False), "Italic": (400, True), "Medium": (500, False), "MediumItalic": (500, True),
    "SemiBold": (600, False), "SemiBoldItalic": (600, True), "Bold": (700, False), "BoldItalic": (700, True),
}
fonts = []
for path in sorted((assets / "fonts").glob("*.ttf")):
    family, _, style = path.stem.partition("-")
    weight, italic = STYLE[style]
    tag = re.sub(r"(?<!^)(?=[A-Z])", "_", family).lower() + ("_" + re.sub(r"(?<!^)(?=[A-Z])", "_", style).lower() if style else "_regular")
    fonts.append((tag, {"Geist": "Geist", "GeistMono": "Geist Mono"}[family], weight, italic, path.name))

file_icons = sorted(
    str(p.relative_to(assets / "file-icons"))
    for sub in ("files", "folders")
    for p in (assets / "file-icons" / sub).iterdir() if p.suffix in (".svg", ".png")
)

out = []
w = out.append
w("//! Embedded zeron assets. GENERATED by apps/zeron/scripts/gen_assets.py -- do not edit.")
w("//!")
w("//! - `Icon`: control icons, named after zeron's `crates/ui/src/icons.rs` constants")
w("//!   (Solar Icons Linear by 480 Design, CC BY 4.0, plus zeron's own MIT glyphs);")
w("//! - `Font`: Geist / Geist Mono static TTFs (SIL OFL 1.1);")
w("//! - `fileIcon`: vscode-symbols file/folder SVGs (MIT) and their icon-theme manifest.")
w("//! See apps/zeron/assets/README.md for sources and licenses.")
w("")
w('const std = @import("std");')
w("")
w("pub const Icon = enum {")
ZIG_KEYWORDS = {"return", "test", "error", "type", "const", "var", "fn", "if", "else", "for", "while",
                "switch", "break", "continue", "defer", "try", "catch", "struct", "enum", "union",
                "opaque", "and", "or", "pub", "export", "extern", "inline", "align", "async", "await"}
for const, _ in icons:
    tag = const.lower()
    w(f'    @"{tag}",' if tag in ZIG_KEYWORDS else f"    {tag},")
w("")
w("    /// The SVG bytes (all glyphs paint with `currentColor`).")
w("    pub fn svg(self: Icon) []const u8 {")
w("        return icon_svgs[@backingInt(self)];")
w("    }")
w("")
w("    /// zeron's asset path, e.g. `icons/pen-new-square.svg`.")
w("    pub fn path(self: Icon) []const u8 {")
w("        return icon_paths[@backingInt(self)];")
w("    }")
w("")
w("    /// The asset file stem, e.g. `pen-new-square`.")
w("    pub fn fileName(self: Icon) []const u8 {")
w('        const p = self.path();')
w('        return p["icons/".len .. p.len - ".svg".len];')
w("    }")
w("")
w("    /// Look up by asset path (`icons/<name>.svg`).")
w("    pub fn fromPath(asset_path: []const u8) ?Icon {")
w("        for (icon_paths, 0..) |p, i| if (std.mem.eql(u8, p, asset_path)) return @fromBackingInt(@intCast(i));")
w("        return null;")
w("    }")
w("};")
w("")
w("const icon_paths = [_][]const u8{")
for _, name in icons:
    w(f'    "icons/{name}.svg",')
w("};")
w("")
w("const icon_svgs = [_][]const u8{")
for _, name in icons:
    w(f'    @embedFile("assets/icons/{name}.svg"),')
w("};")
w("")
w("/// The Claude mark's brand orange (`#D97757`), applied at the call site.")
w("pub const claude_brand_rgb: u32 = 0xD97757;")
w("")
if unregistered:
    w("// Present in assets/icons but not registered in icons.rs: " + ", ".join(unregistered))
    w("")
w("pub const Font = enum {")
for tag, *_ in fonts:
    w(f"    {tag},")
w("")
w("    pub const Info = struct { family: []const u8, weight: u16, italic: bool, file: []const u8, data: []const u8 };")
w("")
w("    pub fn info(self: Font) Info {")
w("        return font_infos[@backingInt(self)];")
w("    }")
w("};")
w("")
w("const font_infos = [_]Font.Info{")
for tag, family, weight, italic, fname in fonts:
    w(f'    .{{ .family = "{family}", .weight = {weight}, .italic = {"true" if italic else "false"}, .file = "{fname}", .data = @embedFile("assets/fonts/{fname}") }},')
w("};")
w("")
w("/// Geist / Geist Mono license (SIL OFL 1.1); ship it alongside binaries.")
w('pub const font_license = @embedFile("assets/fonts/licenses/Geist-OFL.txt");')
w("")
w("/// VS Code file-icon theme manifest (vscode-symbols); `iconPath`s are")
w("/// `./icons/{files,folders}/<name>.svg`, i.e. `fileIcon` paths under `./icons/`.")
w('pub const file_icons_manifest = @embedFile("assets/file-icons/file-icons.json");')
w('pub const file_icons_license = @embedFile("assets/file-icons/LICENSE.symbols");')
w("")
w("/// Embedded file-icon bytes by relative path (`files/rust.svg`, `folders/folder-src.svg`;")
w("/// one upstream icon, `files/nuxt.png`, is a PNG).")
w("pub fn fileIcon(rel_path: []const u8) ?[]const u8 {")
w("    const i = std.sort.binarySearch([]const u8, &file_icon_paths, rel_path, struct {")
w("        fn order(key: []const u8, item: []const u8) std.math.Order {")
w("            return std.mem.order(u8, key, item);")
w("        }")
w("    }.order) orelse return null;")
w("    return file_icon_svgs[i];")
w("}")
w("")
w("/// Dark-appearance accent lifts zeron applies to file-icon SVG colors (both cases).")
w("pub const file_icon_dark_swaps = [_][2][]const u8{")
for a, b in [("#64748B", "#CBD5E1"), ("#71717A", "#D4D4D8"), ("#2563EB", "#60A5FA"), ("#EA580C", "#FB923C"),
             ("#16A34A", "#4ADE80"), ("#8B5CF6", "#A78BFA"), ("#A855F7", "#C084FC")]:
    w(f'    .{{ "{a}", "{b}" }},')
w("};")
w("")
w("/// Sorted relative paths of every embedded file icon.")
w("pub const file_icon_paths = [_][]const u8{")
for p in file_icons:
    w(f'    "{p}",')
w("};")
w("")
w("const file_icon_svgs = [_][]const u8{")
for p in file_icons:
    w(f'    @embedFile("assets/file-icons/{p}"),')
w("};")
w("")
w("test {")
w("    for (std.enums.values(Icon)) |icon| {")
w('        try std.testing.expect(std.mem.indexOf(u8, icon.svg(), "<svg") != null);')
w('        try std.testing.expect(std.mem.indexOf(u8, icon.svg(), "viewBox") != null);')
w("        try std.testing.expectEqual(icon, Icon.fromPath(icon.path()).?);")
w("    }")
w('    try std.testing.expectEqualStrings("pen-new-square", Icon.pen_new_square.fileName());')
w('    try std.testing.expect(Icon.fromPath("icons/nope.svg") == null);')
w("    for (std.enums.values(Font)) |f| {")
w("        const d = f.info().data;")
w("        try std.testing.expect(d.len > 1024 and std.mem.readInt(u32, d[0..4], .big) == 0x00010000);")
w("    }")
w("    for (file_icon_paths) |p| {")
w("        if (std.mem.endsWith(u8, p, \".svg\")) try std.testing.expect(std.mem.indexOf(u8, fileIcon(p).?, \"<svg\") != null);")
w("    }")
w('    try std.testing.expect(fileIcon("files/does-not-exist.svg") == null);')
w('    try std.testing.expect(std.mem.indexOf(u8, file_icons_manifest, "iconDefinitions") != null);')
w("}")
print(zig_fmt("\n".join(out) + "\n"), end="")
print(f"icons={len(icons)} unregistered={unregistered} fonts={len(fonts)} file_icons={len(file_icons)}", file=sys.stderr)
