#!/usr/bin/env python3
"""Generate apps/zeron/src/theme/builtins.zig from zeron's built-in theme seeds.

Source of truth: `crates/theme/src/builtins.rs` in the zeron repo. Every
built-in variant there is a `variant(Seeds { .. })` call; this script extracts
the seed literals and the family registry verbatim. The seed -> full variant
derivation is hand-ported in `derive.zig` and runs at comptime, so rerunning
this script is all that is needed when zeron adds or retunes a theme.

Usage: gen_themes.py [ZERON_REPO] > apps/zeron/src/theme/builtins.zig
"""
import re
import sys
from pathlib import Path


def zig_fmt(source):
    """Format with `zig fmt --stdin` when zig is on PATH; else return as is."""
    import shutil
    import subprocess
    if not shutil.which("zig"):
        return source
    res = subprocess.run(["zig", "fmt", "--stdin"], input=source, capture_output=True, text=True)
    return res.stdout if res.returncode == 0 else source

repo = Path(sys.argv[1] if len(sys.argv) > 1 else "/home/user/zeron")
src = (repo / "crates/theme/src/builtins.rs").read_text()

STR = r'"((?:[^"\\]|\\.)*)"'


def strings(text):
    return re.findall(STR, text)


# Shared ANSI palettes: `const ANSI_DARK: [&str; 16] = [ ... ];`
consts = {}
for m in re.finditer(r"const (\w+): \[&str; 16\] = \[(.*?)\];", src, re.S):
    consts[m.group(1)] = strings(m.group(2))

# Family registry: `family("id", "Name", vec![a(), b()])`.
reg = re.search(r"families: vec!\[(.*?)\n\s*\],\n\s*\}\)", src, re.S)
if not reg:
    sys.exit("family registry not found")
families = []
for m in re.finditer(r'family\(\s*' + STR + r',\s*' + STR + r',\s*vec!\[(.*?)\]\s*,?\s*\)', reg.group(1), re.S):
    fns = re.findall(r"(\w+)\(\)", m.group(3))
    families.append((m.group(1), m.group(2), fns))

# Seed functions: `fn name() -> ThemeVariant { variant(Seeds { ... }) }`.
seeds = {}
for m in re.finditer(r"fn (\w+)\(\) -> ThemeVariant \{\s*variant\(Seeds \{(.*?)\n    \}\)\n\}", src, re.S):
    name, body = m.group(1), m.group(2)
    seed = {}
    for key in ("id", "family_id", "name", "background", "shell", "raised", "card", "text",
                "muted", "faint", "accent", "danger", "warning", "success", "terminal_background"):
        f = re.search(r"\b" + key + r":\s*" + STR + ",", body)
        if not f:
            sys.exit(f"{name}: missing {key}")
        seed[key] = f.group(1)
    seed["appearance"] = re.search(r"appearance:\s*Appearance::(\w+)", body).group(1).lower()
    seed["treatment"] = re.search(r"treatment:\s*SurfaceTreatment::(\w+)", body).group(1).lower()
    ansi = re.search(r"ansi:\s*(\w+|\[.*?\]),", body, re.S).group(1)
    seed["ansi"] = consts[ansi] if ansi in consts else strings(ansi)
    seed["syntax"] = strings(re.search(r"syntax:\s*\[(.*?)\]", body, re.S).group(1))
    seed["source"] = strings(re.search(r"source:\s*source\((.*?)\)", body, re.S).group(1))
    if len(seed["ansi"]) != 16 or len(seed["syntax"]) != 12 or len(seed["source"]) != 5:
        sys.exit(f"{name}: unexpected array length")
    seeds[name] = seed

missing = [f for _, _, fns in families for f in fns if f not in seeds]
if missing:
    sys.exit(f"seed functions not found: {missing}")


def zs(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def arr(items, per_line):
    lines = []
    for i in range(0, len(items), per_line):
        lines.append(" ".join(zs(x) + "," for x in items[i:i + per_line]))
    return lines


out = []
w = out.append
w("//! Built-in theme seeds. GENERATED by apps/zeron/scripts/gen_themes.py from")
w("//! zeron `crates/theme/src/builtins.rs` -- do not edit by hand.")
w("//!")
w("//! The full variants are derived from these seeds at comptime by `derive.zig`.")
w("")
w('const derive = @import("derive.zig");')
w('const model = @import("model.zig");')
w("")
w("const Seeds = derive.Seeds;")
w("")
w("/// Every built-in family, in zeron's registry order.")
w("pub const families = [_]model.ThemeFamily{")
for fid, fname, fns in families:
    w(f"    .{{ .id = {zs(fid)}, .name = {zs(fname)}, .variants = &.{{ " +
      ", ".join(f"derive.variant({fn})" for fn in fns) + " } },")
w("};")
w("")
w(f"/// Number of built-in variants across all families.")
w(f"pub const variant_count = {sum(len(f[2]) for f in families)};")
for fid, fname, fns in families:
    for fn in fns:
        s = seeds[fn]
        w("")
        w(f"pub const {fn}: Seeds = .{{")
        for key in ("id", "family_id", "name"):
            w(f"    .{key} = {zs(s[key])},")
        w(f"    .appearance = .{s['appearance']},")
        w(f"    .treatment = .{'opaque_' if s['treatment'] == 'opaque' else s['treatment']},")
        for key in ("background", "shell", "raised", "card", "text", "muted", "faint", "accent",
                    "danger", "warning", "success", "terminal_background"):
            w(f"    .{key} = {zs(s[key])},")
        w("    .ansi = .{")
        for line in arr(s["ansi"], 8):
            w("        " + line)
        w("    },")
        w("    .syntax = .{")
        for line in arr(s["syntax"], 6):
            w("        " + line)
        w("    },")
        fmt, url, rev, lic = s["source"][1:]
        w(f"    .source = .{{ .format = {zs(fmt)}, .url = {zs(url)}, .revision = {zs(rev)}, .license = {zs(lic)} }},")
        w("};")
print(zig_fmt("\n".join(out) + "\n"), end="")
