#!/usr/bin/env python3
"""Generate apps/zeron/src/markdown/cmark/{entities,puncttable}.zig from
pulldown-cmark 0.12.2's entities.rs / puncttable.rs (the Rust crate zeron
links), so the Zig port resolves entities and punctuation identically.

usage: gen_cmark_tables.py <pulldown-cmark-0.12.2/src> <out dir>
"""
import re, sys, os

src, out = sys.argv[1], sys.argv[2]

ent = open(os.path.join(src, "entities.rs")).read()
pairs = re.findall(r'\(b"([^"]+)", "([^"]*)"\)', ent)
def unrust(s):
    return re.sub(r'\\u\{([0-9A-Fa-f]+)\}', lambda m: chr(int(m.group(1), 16)), s)
def zstr(s):
    o = []
    for b in s.encode("utf-8"):
        if 0x20 <= b < 0x7f and chr(b) not in '"\\':
            o.append(chr(b))
        else:
            o.append("\\x%02x" % b)
    return '"' + "".join(o) + '"'
with open(os.path.join(out, "entities.zig"), "w") as f:
    f.write("//! HTML5 entity table — generated by apps/zeron/scripts/gen_cmark_tables.py\n")
    f.write("//! from pulldown-cmark 0.12.2 src/entities.rs. Do not edit.\n\n")
    f.write("const std = @import(\"std\");\n\n")
    f.write("const Entry = struct { []const u8, []const u8 };\n\n")
    f.write("const entities = [_]Entry{\n")
    for k, v in pairs:
        f.write("    .{ %s, %s },\n" % (zstr(k), zstr(unrust(v))))
    f.write("};\n\n")
    f.write("""/// Binary search over byte-sorted names (mirrors `get_entity`).
pub fn get(name: []const u8) ?[]const u8 {
    var lo: usize = 0;
    var hi: usize = entities.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, entities[mid][0], name)) {
            .eq => return entities[mid][1],
            .lt => lo = mid + 1,
            .gt => hi = mid,
        }
    }
    return null;
}
""")

p = open(os.path.join(src, "puncttable.rs")).read()
def arr(name):
    m = re.search(r'const %s: \[u16; \d+\] = \[(.*?)\];' % name, p, re.S)
    return [x.strip() for x in re.sub(r'//[^\n]*', '', m.group(1)).split(",") if x.strip()]
ascii_ = arr("PUNCT_MASKS_ASCII"); tab = arr("PUNCT_TAB"); masks = arr("PUNCT_MASKS")
with open(os.path.join(out, "puncttable.zig"), "w") as f:
    f.write("//! CommonMark punctuation (Unicode P + S) — generated by\n")
    f.write("//! apps/zeron/scripts/gen_cmark_tables.py from pulldown-cmark 0.12.2. Do not edit.\n\n")
    f.write("const ascii_masks = [_]u16{ %s };\n\n" % ", ".join(ascii_))
    f.write("const tab = [_]u16{ %s };\n\n" % ", ".join(tab))
    f.write("const masks = [_]u16{ %s };\n\n" % ", ".join(masks))
    f.write("""pub fn isAsciiPunctuation(c: u8) bool {
    return c < 128 and (ascii_masks[c / 16] & (@as(u16, 1) << @intCast(c & 15))) != 0;
}

pub fn isPunctuation(cp: u21) bool {
    if (cp < 128) return isAsciiPunctuation(@intCast(cp));
    if (cp > 0x1FBCA) return false;
    const high: u16 = @intCast(cp / 16);
    var lo: usize = 0;
    var hi: usize = tab.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (tab[mid] == high) return (masks[mid] & (@as(u16, 1) << @intCast(cp & 15))) != 0;
        if (tab[mid] < high) lo = mid + 1 else hi = mid;
    }
    return false;
}
""")

# Full Unicode case folding (C + F), what unicase uses for reference-label
# matching. Python's str.casefold implements the same table.
import unicodedata
fold = []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    c = chr(cp)
    f = c.casefold()
    if f != c:
        fold.append((cp, f))
with open(os.path.join(out, "casefold.zig"), "w") as f:
    f.write("//! Unicode full case folding (C+F) — generated by\n")
    f.write("//! apps/zeron/scripts/gen_cmark_tables.py (Unicode %s). Do not edit.\n\n" % unicodedata.unidata_version)
    f.write("const Entry = struct { u21, []const u8 };\n\n")
    f.write("const table = [_]Entry{\n")
    for cp, s in fold:
        f.write("    .{ 0x%X, %s },\n" % (cp, zstr(s)))
    f.write("};\n\n")
    f.write("""/// The case-folded UTF-8 of `cp`, or null when it folds to itself.
pub fn fold(cp: u21) ?[]const u8 {
    var lo: usize = 0;
    var hi: usize = table.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (table[mid][0] == cp) return table[mid][1];
        if (table[mid][0] < cp) lo = mid + 1 else hi = mid;
    }
    return null;
}
""")
