//! Dumps zeron's markdown results as canonical JSON lines for the Zig parity
//! tests in apps/zeron/src/markdown/parity_test.zig.
//!
//! Inputs come from apps/zeron/src/markdown/testdata/{corpus,stream}.txt
//! (generated by apps/zeron/scripts/gen_md_corpus.py). Outputs, one line per
//! input document, written next to them:
//!   events.jsonl — pulldown-cmark 0.12.2 offset events (zeron's options)
//!   trees.jsonl  — zeron_markdown::parse_full block trees
//!   mend.jsonl   — zeron_markdown::mend::close_hanging (string or null)
//!   stream.jsonl — IncrementalParser steps streaming each stream.txt doc:
//!                  FNV-1a 64 hashes of the canonical/display tree JSON
//!                  (display null when equal), stable prefix, reparsed bytes
//!
//! Build against the zeron workspace's prebuilt rlibs (no Cargo project):
//!   D=$ZERON/target/debug/deps
//!   rustc --edition 2024 -O markdown_parity.rs -o /tmp/markdown_parity -L $D \
//!     --extern zeron_markdown=$(ls $D/libzeron_markdown-*.rlib) \
//!     --extern pulldown_cmark=$(ls $D/libpulldown_cmark-*.rlib)
//!   /tmp/markdown_parity apps/zeron/src/markdown/testdata

use std::fmt::Write as _;
use std::io::Write as _;

use pulldown_cmark::{Alignment, CodeBlockKind, Event, LinkType, Options, Parser, Tag, TagEnd};
use zeron_markdown::parser::{Block, BlockTree, IncrementalParser, InlineRun, TableAlign, parse_full};

fn esc(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
}

fn opt(out: &mut String, s: Option<&str>) {
    match s {
        Some(s) => esc(out, s),
        None => out.push_str("null"),
    }
}

fn run(out: &mut String, r: &InlineRun) {
    out.push_str("{\"text\":");
    esc(out, &r.text);
    let _ = write!(
        out,
        ",\"b\":{},\"i\":{},\"c\":{},\"s\":{},\"link\":",
        r.style.bold, r.style.italic, r.style.code, r.style.strikethrough
    );
    opt(out, r.style.link.as_deref());
    out.push_str(",\"image\":");
    match &r.style.image {
        Some(img) => {
            out.push_str("{\"source\":");
            esc(out, &img.source);
            out.push_str(",\"alt\":");
            esc(out, &img.alt);
            out.push_str(",\"title\":");
            esc(out, &img.title);
            out.push_str(",\"link\":");
            opt(out, img.link.as_deref());
            out.push('}');
        }
        None => out.push_str("null"),
    }
    out.push_str(",\"task\":");
    match &r.style.task {
        Some(t) => {
            let _ = write!(
                out,
                "{{\"checked\":{},\"range\":[{},{}]}}",
                t.checked, t.range.start, t.range.end
            );
        }
        None => out.push_str("null"),
    }
    out.push('}');
}

fn runs(out: &mut String, rs: &[InlineRun]) {
    out.push('[');
    for (i, r) in rs.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        run(out, r);
    }
    out.push(']');
}

fn cells(out: &mut String, cs: &[Vec<InlineRun>]) {
    out.push('[');
    for (i, c) in cs.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        runs(out, c);
    }
    out.push(']');
}

fn blocks(out: &mut String, bs: &[Block]) {
    out.push('[');
    for (i, b) in bs.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        block(out, b);
    }
    out.push(']');
}

fn block(out: &mut String, b: &Block) {
    match b {
        Block::Paragraph { runs: rs } => {
            out.push_str("{\"t\":\"p\",\"runs\":");
            runs(out, rs);
            out.push('}');
        }
        Block::Heading { level, runs: rs } => {
            let _ = write!(out, "{{\"t\":\"h\",\"level\":{level},\"runs\":");
            runs(out, rs);
            out.push('}');
        }
        Block::CodeBlock { language, code } => {
            out.push_str("{\"t\":\"code\",\"lang\":");
            opt(out, language.as_deref());
            out.push_str(",\"code\":");
            esc(out, code);
            out.push('}');
        }
        Block::BlockQuote { children } => {
            out.push_str("{\"t\":\"quote\",\"children\":");
            blocks(out, children);
            out.push('}');
        }
        Block::List {
            ordered_start,
            items,
        } => {
            out.push_str("{\"t\":\"list\",\"start\":");
            match ordered_start {
                Some(s) => {
                    let _ = write!(out, "{s}");
                }
                None => out.push_str("null"),
            }
            out.push_str(",\"items\":[");
            for (i, it) in items.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                blocks(out, it);
            }
            out.push_str("]}");
        }
        Block::Table {
            header,
            rows,
            align,
        } => {
            out.push_str("{\"t\":\"table\",\"header\":");
            cells(out, header);
            out.push_str(",\"rows\":[");
            for (i, r) in rows.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                cells(out, r);
            }
            out.push_str("],\"align\":[");
            for (i, a) in align.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                out.push_str(match a {
                    TableAlign::Left => "\"left\"",
                    TableAlign::Center => "\"center\"",
                    TableAlign::Right => "\"right\"",
                });
            }
            out.push_str("]}");
        }
        Block::Rule => out.push_str("{\"t\":\"rule\"}"),
    }
}

fn tree(out: &mut String, t: &BlockTree) {
    out.push('[');
    for (i, tb) in t.blocks.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        let _ = write!(
            out,
            "{{\"range\":[{},{}],\"block\":",
            tb.range.start, tb.range.end
        );
        block(out, &tb.block);
        out.push('}');
    }
    out.push(']');
}

fn tag_name(t: &Tag) -> &'static str {
    match t {
        Tag::Paragraph => "paragraph",
        Tag::Heading { .. } => "heading",
        Tag::BlockQuote(_) => "block_quote",
        Tag::CodeBlock(_) => "code_block",
        Tag::HtmlBlock => "html_block",
        Tag::List(_) => "list",
        Tag::Item => "item",
        Tag::Table(_) => "table",
        Tag::TableHead => "table_head",
        Tag::TableRow => "table_row",
        Tag::TableCell => "table_cell",
        Tag::Emphasis => "emphasis",
        Tag::Strong => "strong",
        Tag::Strikethrough => "strikethrough",
        Tag::Link { .. } => "link",
        Tag::Image { .. } => "image",
        _ => "other",
    }
}

fn end_name(t: &TagEnd) -> &'static str {
    match t {
        TagEnd::Paragraph => "paragraph",
        TagEnd::Heading(_) => "heading",
        TagEnd::BlockQuote(_) => "block_quote",
        TagEnd::CodeBlock => "code_block",
        TagEnd::HtmlBlock => "html_block",
        TagEnd::List(_) => "list",
        TagEnd::Item => "item",
        TagEnd::Table => "table",
        TagEnd::TableHead => "table_head",
        TagEnd::TableRow => "table_row",
        TagEnd::TableCell => "table_cell",
        TagEnd::Emphasis => "emphasis",
        TagEnd::Strong => "strong",
        TagEnd::Strikethrough => "strikethrough",
        TagEnd::Link => "link",
        TagEnd::Image => "image",
        _ => "other",
    }
}

fn link_type(t: &LinkType) -> &'static str {
    match t {
        LinkType::Inline => "inline",
        LinkType::Reference => "reference",
        LinkType::Collapsed => "collapsed",
        LinkType::Shortcut => "shortcut",
        LinkType::Autolink => "autolink",
        LinkType::Email => "email",
        _ => "other",
    }
}

fn events(out: &mut String, src: &str) {
    let opts = Options::ENABLE_TABLES | Options::ENABLE_STRIKETHROUGH | Options::ENABLE_TASKLISTS;
    out.push('[');
    for (i, (ev, r)) in Parser::new_ext(src, opts).into_offset_iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        let (s, e) = (r.start, r.end);
        match ev {
            Event::Start(tag) => {
                let _ = write!(out, "[\"S\",\"{}\",{s},{e}", tag_name(&tag));
                match &tag {
                    Tag::Heading { level, .. } => {
                        let _ = write!(out, ",{}", *level as u8);
                    }
                    Tag::CodeBlock(kind) => {
                        out.push(',');
                        match kind {
                            CodeBlockKind::Fenced(info) => esc(out, info),
                            CodeBlockKind::Indented => out.push_str("null"),
                        }
                    }
                    Tag::List(start) => match start {
                        Some(n) => {
                            let _ = write!(out, ",{n}");
                        }
                        None => out.push_str(",null"),
                    },
                    Tag::Table(al) => {
                        out.push_str(",[");
                        for (k, a) in al.iter().enumerate() {
                            if k > 0 {
                                out.push(',');
                            }
                            out.push_str(match a {
                                Alignment::None => "\"none\"",
                                Alignment::Left => "\"left\"",
                                Alignment::Center => "\"center\"",
                                Alignment::Right => "\"right\"",
                            });
                        }
                        out.push(']');
                    }
                    Tag::Link {
                        link_type: lt,
                        dest_url,
                        title,
                        id,
                    }
                    | Tag::Image {
                        link_type: lt,
                        dest_url,
                        title,
                        id,
                    } => {
                        let _ = write!(out, ",\"{}\",", link_type(lt));
                        esc(out, dest_url);
                        out.push(',');
                        esc(out, title);
                        out.push(',');
                        esc(out, id);
                    }
                    _ => {}
                }
                out.push(']');
            }
            Event::End(t) => {
                let _ = write!(out, "[\"E\",\"{}\",{s},{e}]", end_name(&t));
            }
            Event::Text(t) => text_ev(out, "T", s, e, &t),
            Event::Code(t) => text_ev(out, "C", s, e, &t),
            Event::Html(t) => text_ev(out, "H", s, e, &t),
            Event::InlineHtml(t) => text_ev(out, "I", s, e, &t),
            Event::SoftBreak => {
                let _ = write!(out, "[\"SB\",{s},{e}]");
            }
            Event::HardBreak => {
                let _ = write!(out, "[\"HB\",{s},{e}]");
            }
            Event::Rule => {
                let _ = write!(out, "[\"R\",{s},{e}]");
            }
            Event::TaskListMarker(b) => {
                let _ = write!(out, "[\"X\",{s},{e},{b}]");
            }
            _ => out.push_str("[\"?\"]"),
        }
    }
    out.push(']');
}

fn text_ev(out: &mut String, k: &str, s: usize, e: usize, t: &str) {
    let _ = write!(out, "[\"{k}\",{s},{e},");
    esc(out, t);
    out.push(']');
}

/// FNV-1a 64 of a tree's canonical JSON (stream steps store hashes only).
fn fnv(s: &str) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for b in s.bytes() {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

fn read_docs(path: &str) -> Vec<String> {
    let bytes = std::fs::read(path).expect("read corpus");
    let mut docs = Vec::new();
    let mut at = 0;
    while at < bytes.len() {
        let nl = at + bytes[at..].iter().position(|&b| b == b'\n').unwrap();
        let len: usize = std::str::from_utf8(&bytes[at..nl]).unwrap().parse().unwrap();
        let start = nl + 1;
        docs.push(String::from_utf8(bytes[start..start + len].to_vec()).unwrap());
        at = start + len + 1;
    }
    docs
}

/// Chunk size used to stream a document (mirrors parity_test.zig).
fn chunk_for(doc: &str) -> usize {
    if doc.len() <= 160 { 1 } else { 5 }
}

fn main() {
    let dir = std::env::args().nth(1).expect("testdata dir");
    let corpus = read_docs(&format!("{dir}/corpus.txt"));
    let mut ev = String::new();
    let mut tr = String::new();
    let mut me = String::new();
    for doc in &corpus {
        events(&mut ev, doc);
        ev.push('\n');
        tree(&mut tr, &parse_full(doc));
        tr.push('\n');
        opt(&mut me, zeron_markdown::mend::close_hanging(doc).as_deref());
        me.push('\n');
    }
    std::fs::File::create(format!("{dir}/events.jsonl")).unwrap().write_all(ev.as_bytes()).unwrap();
    std::fs::File::create(format!("{dir}/trees.jsonl")).unwrap().write_all(tr.as_bytes()).unwrap();
    std::fs::File::create(format!("{dir}/mend.jsonl")).unwrap().write_all(me.as_bytes()).unwrap();

    let stream = read_docs(&format!("{dir}/stream.txt"));
    let mut st = String::new();
    for doc in &stream {
        let chunk = chunk_for(doc);
        let mut p = IncrementalParser::new();
        let mut start = 0;
        st.push('[');
        let mut first = true;
        while start < doc.len() {
            let mut end = (start + chunk).min(doc.len());
            while end < doc.len() && !doc.is_char_boundary(end) {
                end += 1;
            }
            p.append(&doc[start..end]);
            start = end;
            if !first {
                st.push(',');
            }
            first = false;
            let _ = write!(
                st,
                "{{\"n\":{},\"stable\":{},\"bytes\":{},\"canon\":",
                end,
                p.stable_prefix_blocks(),
                p.last_parse_bytes()
            );
            let mut c = String::new();
            tree(&mut c, p.tree());
            let _ = write!(st, "\"{:016x}\",\"display\":", fnv(&c));
            let d = p.display_tree();
            if &d == p.tree() {
                st.push_str("null");
            } else {
                let mut dj = String::new();
                tree(&mut dj, &d);
                let _ = write!(st, "\"{:016x}\"", fnv(&dj));
            }
            st.push('}');
        }
        st.push_str("]\n");
    }
    std::fs::File::create(format!("{dir}/stream.jsonl")).unwrap().write_all(st.as_bytes()).unwrap();
    eprintln!("wrote {} corpus docs, {} stream docs", corpus.len(), stream.len());
}
