//! Dumps the transcript stick-to-bottom spring (zeron `crates/ui/src/transcript.rs`
//! `StickSpring`) for a deterministic corpus as Zig source, for
//! apps/zeron/src/ui/transcript/testdata/stick_parity.zig (compared by the
//! "stick spring parity" test in apps/zeron/src/ui/transcript/stick.zig).
//!
//! The stepper is private to the gpui crate, so the constants and the struct
//! are lifted VERBATIM into a generated include (`#[cfg(test)]` accessors and
//! the doc comments dropped):
//!   Z=$ZERON  S=/tmp/stick_parity && mkdir -p $S
//!   sed -n '/^pub const SPRING_DAMPING/,/^pub const SPRING_CHASE_MAX_LEAD/p;/^pub struct StickSpring/,/^\/\/ Row model/p' \
//!     $Z/crates/ui/src/transcript.rs | grep -v '^// ' | sed '/#\[cfg(test)\]/,+4d' > $S/spring.rs
//!   SPRING_LIFTED=$S/spring.rs rustc --edition 2024 stick_parity.rs -o $S/run
//!   $S/run > apps/zeron/src/ui/transcript/testdata/stick_parity.zig

#![allow(dead_code)]

include!(env!("SPRING_LIFTED"));

fn f(v: f32) -> String {
    format!("{v:?}")
}

fn main() {
    println!("//! Generated by apps/zeron/scripts/stick_parity.rs from zeron transcript.rs. Do not edit.");
    println!();
    println!("pub const Step = struct {{ pos: f32, target: f32, frames: f32, out: f32 }};");
    println!("pub const Case = struct {{ steps: []const Step }};");
    println!("pub const cases = [_]Case{{");
    // (pos, target, frames) scripts; `pos` -1 means "carry the previous output".
    let scripts: Vec<Vec<(f32, f32, f32)>> = vec![
        // A far glide to a fixed bottom.
        (0..60).map(|_| (-1.0, 900.0, 1.0)).collect(),
        // Streaming growth: the target climbs while the spring chases it.
        (0..80).map(|i| (-1.0, 400.0 + i as f32 * 6.0, 1.0)).collect(),
        // Hitches (catch-up frames), then a shrinking target.
        vec![(-1.0, 600.0, 3.0), (-1.0, 600.0, 8.0), (-1.0, 700.0, 0.5), (-1.0, 650.0, 2.0), (-1.0, 640.0, 1.0), (-1.0, 640.0, 4.0), (-1.0, 640.0, 8.0), (-1.0, 640.0, 8.0)],
    ];
    for script in scripts {
        let mut s = StickSpring::new();
        let mut pos = 0.0f32;
        println!("    .{{ .steps = &.{{");
        for (p, target, frames) in script {
            if p >= 0.0 {
                pos = p;
            }
            let out = s.step(pos, target, frames);
            println!("        .{{ .pos = {}, .target = {}, .frames = {}, .out = {} }},", f(pos), f(target), f(frames), f(out));
            pos = out;
        }
        println!("    }} }},");
    }
    println!("}};");
}
