//! Dumps zeron's resolved theme values as Zig source for
//! apps/zeron/src/theme/parity_data.zig (compared by parity_test.zig).
//!
//! Build against the zeron workspace's prebuilt rlibs (no Cargo project needed):
//!   D=$ZERON/target/debug/deps   # after `cargo build -p zeron-ui` in $ZERON
//!   rustc --edition 2024 theme_parity.rs -o /tmp/theme_parity -L $D \
//!     --extern zeron_theme=$(ls $D/libzeron_theme-*.rlib) \
//!     --extern zeron_ui=$(ls $D/libzeron_ui-*.rlib) \
//!     --extern zeron_syntax=$(ls $D/libzeron_syntax-*.rlib) --extern gpui=$(ls $D/libgpui-*.rlib) \
//!     --extern serde_json=<the libserde_json-*.rlib zeron_theme links>
//!   /tmp/theme_parity > apps/zeron/src/theme/parity_data.zig
//! Values are platform-dependent (glass alpha); run on the target OS.

use zeron_syntax::HighlightKind as K;
use zeron_theme::{AccentPreset, AccentSelection, Color, SurfacePreference, ThemeRegistry};
use gpui::Hsla;
use zeron_ui::theme::{AccentColor, Appearance, Theme};

fn h(c: Hsla) -> String {
    format!(".{{ {:?}, {:?}, {:?}, {:?} }}", c.h, c.s, c.l, c.a)
}

const KINDS: [K; 31] = [
    K::Comment, K::Keyword, K::String, K::StringSpecial, K::Escape, K::Number, K::Boolean,
    K::Type, K::TypeBuiltin, K::Constructor, K::Function, K::FunctionBuiltin, K::Macro,
    K::Property, K::Constant, K::Variable, K::VariableSpecial, K::Parameter, K::Operator,
    K::Punctuation, K::Tag, K::Attribute, K::Label, K::MarkupHeading, K::MarkupRaw,
    K::MarkupLink, K::MarkupReference, K::MarkupEmphasis, K::MarkupStrong, K::Embedded,
    K::Invalid,
];

fn dump(name: &str, t: &Theme) {
    println!("    .{{ .name = \"{name}\", .tokens = &.{{");
    let popup = t.for_popup();
    let mut fields: Vec<(&str, Hsla)> = vec![
        ("bg", t.bg), ("surface", t.surface), ("surface_raised", t.surface_raised),
        ("surface_card", t.surface_card), ("surface_dialog", t.surface_dialog),
        ("surface_overlay", t.surface_overlay), ("element_hover", t.element_hover),
        ("element_active", t.element_active), ("border", t.border), ("border_strong", t.border_strong),
        ("text", t.text), ("text_muted", t.text_muted), ("text_faint", t.text_faint), ("text_dim", t.text_dim),
        ("solid", t.solid), ("on_solid", t.on_solid), ("accent", t.accent), ("accent_strong", t.accent_strong),
        ("accent_wash", t.accent_wash), ("on_accent", t.on_accent), ("danger", t.danger),
        ("danger_muted", t.danger_muted), ("warning", t.warning), ("warning_muted", t.warning_muted),
        ("success", t.success), ("busy", t.busy), ("glyph.light", t.glyph.light), ("glyph.mid", t.glyph.mid),
        ("glyph.deep", t.glyph.deep), ("success_muted", t.success_muted),
        ("surface_raised_hover", t.surface_raised_hover), ("band", t.band), ("input_bg", t.input_bg),
        ("selection", t.selection), ("cursor", t.cursor), ("caret", t.caret), ("danger_strong", t.danger_strong),
        ("code_text", t.code_text), ("code_wash", t.code_wash), ("diff_add", t.diff_add),
        ("diff_del", t.diff_del), ("diff_hunk_bg", t.diff_hunk_bg),
        ("terminal.background", t.terminal.background), ("terminal.foreground", t.terminal.foreground),
        ("terminal.selection", t.terminal.selection),
        ("glass()", t.glass()), ("glass_overlay()", t.glass_overlay()), ("input_glass_bg()", t.input_glass_bg()),
        ("card_glass_bg()", t.card_glass_bg()), ("composer_sidebar_tint()", t.composer_sidebar_tint()),
        ("composer_surface_bg()", t.composer_surface_bg()), ("composer_surface_border()", t.composer_surface_border()),
        ("panel_bg()", t.panel_bg()), ("scrim()", t.scrim()),
        ("popup.text", popup.text), ("popup.text_muted", popup.text_muted),
        ("popup.text_dim", popup.text_dim), ("popup.text_faint", popup.text_faint),
    ];
    for (i, c) in t.terminal.ansi.iter().enumerate() {
        fields.push((Box::leak(format!("terminal.ansi[{i}]").into_boxed_str()), *c));
    }
    for k in KINDS {
        fields.push((Box::leak(format!("syntax.{k:?}").into_boxed_str()), t.syntax.color(k)));
    }
    for (n, c) in fields {
        println!("        .{{ \"{n}\", {} }},", h(c));
    }
    println!("    }}, .is_glass = {}, .is_frost = {} }},", t.is_glass(), t.is_frost());
}

fn main() {
    let reg = ThemeRegistry::builtin();
    println!("//! GENERATED by apps/zeron/scripts/theme_parity.rs from zeron's Rust theme crates.");
    println!("//! Expected values for parity_test.zig. Do not edit by hand.\n");
    println!("pub const Expected = struct {{ name: []const u8, tokens: []const struct {{ []const u8, [4]f32 }}, is_glass: bool, is_frost: bool }};\n");
    println!("/// `(variant id, serde asset hash)` for every built-in.");
    println!("pub const asset_hashes = [_][2][]const u8{{");
    for f in &reg.families {
        for v in &f.variants {
            println!("    .{{ \"{}\", \"{}\" }},", v.id, v.source.asset_hash);
        }
    }
    println!("}};\n");
    for id in ["zeron-dark", "zeron-light"] {
        let mut v = reg.variant(id).unwrap().clone();
        v.source.asset_hash.clear();
        let json = serde_json::to_string(&v).unwrap();
        println!("pub const {}_json =\n    \\\\{}\n;\n", id.replace('-', "_"), json);
    }
    println!("pub const themes = [_]Expected{{");
    dump("dark()", &Theme::dark());
    dump("light()", &Theme::light());
    dump("dark_with_accent(pink)", &Theme::dark_with_accent(AccentColor::Pink));
    dump("light_with_accent(amber)", &Theme::light_with_accent(AccentColor::Amber));
    let sel = |a, id: &str, acc, surf| Theme::for_selection(a, id, acc, surf);
    use AccentSelection::*;
    use SurfacePreference as S;
    for (a, id, acc, surf, label) in [
        (Appearance::Dark, "zeron-dark", ThemeDefault, S::ThemeDefault, "zeron-dark"),
        (Appearance::Light, "zeron-light", ThemeDefault, S::ThemeDefault, "zeron-light"),
        (Appearance::Dark, "zeron-dark", Preset(AccentPreset::Cyan), S::ThemeDefault, "zeron-dark+cyan"),
        (Appearance::Light, "zeron-light", Preset(AccentPreset::Orange), S::Opaque, "zeron-light+orange/opaque"),
        (Appearance::Dark, "catppuccin-mocha", ThemeDefault, S::Frosted, "catppuccin-mocha/frosted"),
        (Appearance::Light, "github-light", ThemeDefault, S::Frosted, "github-light/frosted"),
        (Appearance::Dark, "synthwave-84", ThemeDefault, S::ThemeDefault, "synthwave-84"),
        (Appearance::Light, "dracula", ThemeDefault, S::ThemeDefault, "light fallback"),
    ] {
        dump(label, &sel(a, id, acc, surf));
    }
    let _ = Color::BLACK;
    println!("}};");
}
