const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const zpui = b.addModule("zpui", .{
        .root_source_file = b.path("src/zpui.zig"),
        .target = target,
        .optimize = optimize,
    });

    const tests = b.addTest(.{ .root_module = zpui });
    const run_tests = b.addRunArtifact(tests);
    const test_step = b.step("test", "Run zpui unit tests");
    test_step.dependOn(&run_tests.step);

    addZeronEngine(b, target, optimize, test_step);
    addZeronDesign(b, target, optimize, zpui, test_step);
    addVulkanRenderer(b, target, optimize, zpui);
    addMetalRenderer(b, target, optimize, zpui);
    addLinuxText(b, target, optimize, zpui);
    addLinuxPlatform(b, target, optimize, zpui);
    addMacPlatform(b, target, optimize, zpui);
    addZeronSyntax(b, target, optimize, test_step);
    addZeronMarkdownDiff(b, target, optimize, test_step);
}

/// zeron engine client library (apps/zeron/src/engine), its tests, and the
/// `zeron-probe` CLI (`zig build probe -- --help`).
fn addZeronEngine(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    test_step: *std.Build.Step,
) void {
    const engine = b.addModule("zeron_engine", .{
        .root_source_file = b.path("apps/zeron/src/engine/engine.zig"),
        .target = target,
        .optimize = optimize,
    });
    const engine_tests = b.addTest(.{ .root_module = engine });
    test_step.dependOn(&b.addRunArtifact(engine_tests).step);

    const probe = b.addExecutable(.{
        .name = "zeron-probe",
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/zeron/examples/probe.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zeron_engine", .module = engine }},
        }),
    });
    b.installArtifact(probe);
    const run_probe = b.addRunArtifact(probe);
    run_probe.addPassthruArgs();
    const probe_step = b.step("probe", "Run zeron-probe against a local engine");
    probe_step.dependOn(&run_probe.step);
}

fn addZeronDesign(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
    test_step: *std.Build.Step,
) void {
    const theme = b.addModule("zeron_theme", .{
        .root_source_file = b.path("apps/zeron/src/theme/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{.{ .name = "zpui", .module = zpui }},
    });
    test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .root_module = theme })).step);

    const files = b.addWriteFiles();
    _ = files.addCopyDirectory(b.path("apps/zeron/assets"), "assets", .{});
    const assets = b.addModule("zeron_assets", .{
        .root_source_file = files.addCopyFile(b.path("apps/zeron/src/assets.zig"), "assets.zig"),
        .target = target,
        .optimize = optimize,
    });
    test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .root_module = assets })).step);
}

/// Vulkan renderer (src/renderer/vulkan/) on non-Apple targets: Vulkan C
/// bindings via translate-c, GLSL shaders compiled to SPIR-V with `glslc`
/// and embedded through a generated `vulkan_shaders` module, plus the
/// `render-test` golden-image harness (`zig build render-test`).
fn addVulkanRenderer(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    const os = target.result.os.tag;
    if (os.isDarwin()) return;

    const vk_c = b.addTranslateC(.{
        .root_source_file = b.path("src/renderer/vulkan/vk.h"),
        .target = target,
        .optimize = optimize,
    });
    // Named module "vk_c" (raw Vulkan C API), reusable by the Linux platform layer.
    zpui.addImport("vk_c", vk_c.addModule("vk_c"));
    zpui.link_libc = true;
    zpui.linkSystemLibrary(if (os == .windows) "vulkan-1" else "vulkan", .{});

    const shader_dir = "src/renderer/vulkan/shaders/";
    const shaders = [_][]const u8{
        "quad.vert",               "quad.frag",
        "shadow.vert",             "shadow.frag",
        "underline.vert",          "underline.frag",
        "mono_sprite.vert",        "mono_sprite.frag",
        "subpixel_sprite.frag",    "subpixel_sprite_fallback.frag",
        "poly_sprite.vert",        "poly_sprite.frag",
        "path_rasterization.vert", "path_rasterization.frag",
        "path_sprite.vert",        "path_sprite.frag",
        "blur_pass.vert",          "blur_pass.frag",
        "backdrop_blur.vert",      "backdrop_blur.frag",
    };
    const wf = b.addWriteFiles();
    var index: std.ArrayList(u8) = .empty;
    index.appendSlice(b.allocator, "//! Generated by build.zig: SPIR-V for src/renderer/vulkan/shaders.\n") catch @panic("OOM");
    for (shaders) |name| {
        const spv = b.fmt("{s}.spv", .{name});
        const glslc = b.addSystemCommand(&.{ "glslc", "--target-env=vulkan1.3", "-O", "-MD" });
        glslc.addArg("-MF");
        _ = glslc.addDepFileOutputArg(b.fmt("{s}.d", .{name}));
        glslc.addFileArg(b.path(b.fmt("{s}{s}", .{ shader_dir, name })));
        glslc.addArg("-o");
        _ = wf.addCopyFile(glslc.addOutputFileArg(spv), spv);
        const ident = b.allocator.dupe(u8, name) catch @panic("OOM");
        for (ident) |*c| if (c.* == '.') {
            c.* = '_';
        };
        index.print(b.allocator, "pub const {s} align(4) = @embedFile(\"{s}\").*;\n", .{ ident, spv }) catch @panic("OOM");
    }
    const shaders_mod = b.createModule(.{ .root_source_file = wf.add("shaders.zig", index.items) });
    zpui.addImport("vulkan_shaders", shaders_mod);

    const render_test = b.addExecutable(.{
        .name = "render-test",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/render_test.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(render_test);
    const run = b.addRunArtifact(render_test);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    const step = b.step("render-test", "Render the showcase scene offscreen to zig-out/render-test.png and compare with tests/golden");
    step.dependOn(&run.step);
}

/// Metal renderer (src/renderer/metal/) on Apple targets: system frameworks,
/// the `render-test` harness, and `metal-check`, which compiles the renderer
/// and showcase scene to an object file. Cross builds from non-macOS hosts
/// have no SDK to link frameworks against, so there `zig build` only runs
/// `metal-check` (`zig build -Dtarget=aarch64-macos`); CI links and runs on macOS.
fn addMetalRenderer(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (!target.result.os.tag.isDarwin()) return;
    const native = @import("builtin").os.tag.isDarwin();

    const check = b.addObject(.{
        .name = "metal-check",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/metal_check.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    const install_check = b.addInstallFile(check.getEmittedBin(), "metal-check.o");
    const check_step = b.step("metal-check", "Compile the Metal renderer to zig-out/metal-check.o (no SDK needed)");
    check_step.dependOn(&install_check.step);
    if (!native) {
        b.getInstallStep().dependOn(&install_check.step);
        return;
    }

    zpui.link_libc = true;
    zpui.linkSystemLibrary("objc", .{});
    for ([_][]const u8{ "Foundation", "CoreGraphics", "QuartzCore", "Metal" }) |name| zpui.linkFramework(name, .{});
    // Only reached through objc_getClass("MPSImageGaussianBlur"); keep it linked.
    zpui.linkFramework("MetalPerformanceShaders", .{ .needed = true });

    const render_test = b.addExecutable(.{
        .name = "render-test",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/render_test.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(render_test);
    const run = b.addRunArtifact(render_test);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    const step = b.step("render-test", "Render the showcase scene offscreen with Metal to zig-out/render-test.png");
    step.dependOn(&run.step);
}

/// Linux text backend (src/text/freetype.zig): FreeType, HarfBuzz and fontconfig
/// via the `freetype_c` translate-c module, plus the `text-dump` CPU raster check
/// (`zig build text-dump` writes zig-out/text-dump.png).
fn addLinuxText(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (target.result.os.tag != .linux) return;
    const c = b.addTranslateC(.{
        .root_source_file = b.path("src/text/freetype_c.h"),
        .target = target,
        .optimize = optimize,
    });
    c.addSystemIncludePath(.{ .cwd_relative = "/usr/include/freetype2" });
    c.addSystemIncludePath(.{ .cwd_relative = "/usr/include/harfbuzz" });
    zpui.addImport("freetype_c", c.createModule());
    zpui.link_libc = true;
    for ([_][]const u8{ "freetype2", "harfbuzz", "fontconfig" }) |lib| zpui.linkSystemLibrary(lib, .{});

    const dump = b.addExecutable(.{
        .name = "text-dump",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/text_dump.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(dump);
    const run = b.addRunArtifact(dump);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    const step = b.step("text-dump", "Rasterize a sample paragraph on the CPU to zig-out/text-dump.png");
    step.dependOn(&run.step);
}

/// Linux platform backend (src/platform/linux/): wayland-scanner protocol
/// bindings, the `linux_c` translate-c module (wayland, xkbcommon, Xlib/xcb),
/// system libraries, and the `linux-window` demo (`zig build linux-window`).
fn addLinuxPlatform(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (target.result.os.tag != .linux) return;

    const c = b.addTranslateC(.{
        .root_source_file = b.path("src/platform/linux/c.h"),
        .target = target,
        .optimize = optimize,
    });
    const protocols = [_][]const u8{
        "xdg-shell",              "xdg-decoration-unstable-v1", "fractional-scale-v1",
        "viewporter",             "tablet-v2",                  "cursor-shape-v1",
        "text-input-unstable-v3", "org-kde-kwin-blur",
    };
    for (protocols) |name| {
        const xml = b.path(b.fmt("src/platform/linux/protocols/{s}.xml", .{name}));
        const header = b.addSystemCommand(&.{ "wayland-scanner", "client-header" });
        header.addFileArg(xml);
        c.addIncludePath(header.addOutputFileArg(b.fmt("{s}-client-protocol.h", .{name})).dirname());
        const code = b.addSystemCommand(&.{ "wayland-scanner", "private-code" });
        code.addFileArg(xml);
        zpui.addCSourceFile(.{ .file = code.addOutputFileArg(b.fmt("{s}-protocol.c", .{name})) });
    }
    zpui.addImport("linux_c", c.createModule());
    zpui.link_libc = true;
    for ([_][]const u8{
        "wayland-client", "wayland-cursor", "xkbcommon", "xkbcommon-x11",
        "X11",            "X11-xcb",        "xcb",       "xcb-xkb",
        "Xcursor",        "Xi",
    }) |lib| zpui.linkSystemLibrary(lib, .{});

    const demo = b.addExecutable(.{
        .name = "linux-window",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/linux_window.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(demo);
    const run = b.addRunArtifact(demo);
    run.addPassthruArgs();
    const step = b.step("linux-window", "Open the Linux platform demo window (Wayland or X11)");
    step.dependOn(&run.step);
}

/// macOS platform backend (src/platform/mac/) + CoreText (src/text/coretext.zig):
/// AppKit/CoreText/CoreVideo/Carbon frameworks, the `mac-window` demo
/// (`zig build mac-window`; `ZPUI_SMOKE_FRAMES=30` makes it render 30 frames,
/// write zig-out/mac-window*.png and exit), and `mac-check`, an object-only
/// compile of the backend that works from non-macOS hosts without an SDK.
fn addMacPlatform(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (target.result.os.tag != .macos) return;
    const native = @import("builtin").os.tag == .macos;

    const check = b.addObject(.{
        .name = "mac-check",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/mac_check.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    const install_check = b.addInstallFile(check.getEmittedBin(), "mac-check.o");
    const check_step = b.step("mac-check", "Compile the macOS platform backend + demo to zig-out/mac-check.o (no SDK needed)");
    check_step.dependOn(&install_check.step);
    if (!native) {
        b.getInstallStep().dependOn(&install_check.step);
        return;
    }

    zpui.link_libc = true;
    for ([_][]const u8{ "AppKit", "CoreFoundation", "CoreText", "CoreVideo", "Carbon" }) |name| zpui.linkFramework(name, .{});

    const demo = b.addExecutable(.{
        .name = "mac-window",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/mac_window.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(demo);
    const run = b.addRunArtifact(demo);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    const step = b.step("mac-window", "Run the macOS window demo (ZPUI_SMOKE_FRAMES=N for the CI smoke test)");
    step.dependOn(&run.step);
}

/// zeron syntax highlighting (apps/zeron/src/syntax): the vendored tree-sitter
/// runtime + grammars (vendor/tree-sitter/tree_sitter_build.zig), the
/// `zeron_syntax` module, and its tests.
fn addZeronSyntax(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    test_step: *std.Build.Step,
) void {
    const ts = @import("vendor/tree-sitter/tree_sitter_build.zig").add(b, target, optimize);
    const syntax = b.addModule("zeron_syntax", .{
        .root_source_file = b.path("apps/zeron/src/syntax/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    ts.addTo(syntax);
    const run = b.addRunArtifact(b.addTest(.{ .root_module = syntax }));
    test_step.dependOn(&run.step);
    b.step("syntax-test", "Run only the zeron_syntax tests").dependOn(&run.step);
}

/// zeron markdown (apps/zeron/src/markdown: pulldown-cmark 0.12 port, block
/// model, incremental reparse, streaming mend) and diff (apps/zeron/src/diff:
/// unified patch parser, `similar` Myers/Patience port) modules + their
/// parity tests.
fn addZeronMarkdownDiff(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    test_step: *std.Build.Step,
) void {
    inline for (.{
        .{ "zeron_markdown", "apps/zeron/src/markdown/root.zig" },
        .{ "zeron_diff", "apps/zeron/src/diff/root.zig" },
    }) |m| {
        const mod = b.addModule(m[0], .{
            .root_source_file = b.path(m[1]),
            .target = target,
            .optimize = optimize,
        });
        test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .name = m[0], .root_module = mod })).step);
    }
}
