const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const zpui = b.addModule("zpui", .{
        .root_source_file = b.path("src/zpui.zig"),
        .target = target,
        .optimize = optimize,
    });

    const tests = b.addTest(.{ .root_module = zpui });
    const run_tests = b.addRunArtifact(tests);
    const test_step = b.step("test", "Run zpui unit tests");
    test_step.dependOn(&run_tests.step);

    addZeronEngine(b, target, optimize, test_step);
    addZeronDesign(b, target, optimize, zpui, test_step);
    addVulkanRenderer(b, target, optimize, zpui);
    addLinuxPlatform(b, target, optimize, zpui);
    addLinuxText(b, target, optimize, zpui);
    addMetalRenderer(b, target, optimize, zpui);
    addMacPlatform(b, target, optimize, zpui);
    addZeronSyntax(b, target, optimize, test_step);
    addImageSupport(b, target, optimize, zpui);
    addZeronMarkdownDiff(b, target, optimize, test_step);
    addZeronModel(b, target, optimize, zpui, test_step);
    addHelloExample(b, target, optimize, zpui);
    addZeronTerminal(b, target, optimize, zpui, test_step);
    addZeronComposer(b, target, optimize, zpui, test_step);
    addZeronTranscriptUi(b, target, optimize, zpui, test_step);
    addZeronApp(b, target, optimize, zpui, test_step);
    addListDemo(b, target, optimize, zpui);
}

/// zeron engine client library (apps/zeron/src/engine), its tests, and the
/// `zeron-probe` CLI (`zig build probe -- --help`).
fn addZeronEngine(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    test_step: *std.Build.Step,
) void {
    const engine = b.addModule("zeron_engine", .{
        .root_source_file = b.path("apps/zeron/src/engine/engine.zig"),
        .target = target,
        .optimize = optimize,
    });
    const engine_tests = b.addTest(.{ .root_module = engine });
    test_step.dependOn(&b.addRunArtifact(engine_tests).step);

    const probe = b.addExecutable(.{
        .name = "zeron-probe",
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/zeron/examples/probe.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zeron_engine", .module = engine }},
        }),
    });
    b.installArtifact(probe);
    const run_probe = b.addRunArtifact(probe);
    run_probe.addPassthruArgs();
    const probe_step = b.step("probe", "Run zeron-probe against a local engine");
    probe_step.dependOn(&run_probe.step);
}

/// Vulkan renderer (src/renderer/vulkan/) on non-Apple targets: Vulkan C
/// bindings via translate-c, GLSL shaders compiled to SPIR-V with `glslc`
/// and embedded through a generated `vulkan_shaders` module, plus the
/// `render-test` golden-image harness (`zig build render-test`).
fn addVulkanRenderer(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    const os = target.result.os.tag;
    if (os.isDarwin()) return;

    const vk_c = b.addTranslateC(.{
        .root_source_file = b.path("src/renderer/vulkan/vk.h"),
        .target = target,
        .optimize = optimize,
    });
    // Named module "vk_c" (raw Vulkan C API), reusable by the Linux platform layer.
    zpui.addImport("vk_c", vk_c.addModule("vk_c"));
    zpui.link_libc = true;
    zpui.linkSystemLibrary(if (os == .windows) "vulkan-1" else "vulkan", .{});

    const shader_dir = "src/renderer/vulkan/shaders/";
    const shaders = [_][]const u8{
        "quad.vert",               "quad.frag",
        "shadow.vert",             "shadow.frag",
        "underline.vert",          "underline.frag",
        "mono_sprite.vert",        "mono_sprite.frag",
        "subpixel_sprite.frag",    "subpixel_sprite_fallback.frag",
        "poly_sprite.vert",        "poly_sprite.frag",
        "path_rasterization.vert", "path_rasterization.frag",
        "path_sprite.vert",        "path_sprite.frag",
        "blur_pass.vert",          "blur_pass.frag",
        "backdrop_blur.vert",      "backdrop_blur.frag",
    };
    const wf = b.addWriteFiles();
    var index: std.ArrayList(u8) = .empty;
    index.appendSlice(b.allocator, "//! Generated by build.zig: SPIR-V for src/renderer/vulkan/shaders.\n") catch @panic("OOM");
    for (shaders) |name| {
        const spv = b.fmt("{s}.spv", .{name});
        const glslc = b.addSystemCommand(&.{ "glslc", "--target-env=vulkan1.3", "-O", "-MD" });
        glslc.addArg("-MF");
        _ = glslc.addDepFileOutputArg(b.fmt("{s}.d", .{name}));
        glslc.addFileArg(b.path(b.fmt("{s}{s}", .{ shader_dir, name })));
        glslc.addArg("-o");
        _ = wf.addCopyFile(glslc.addOutputFileArg(spv), spv);
        const ident = b.allocator.dupe(u8, name) catch @panic("OOM");
        for (ident) |*c| if (c.* == '.') {
            c.* = '_';
        };
        index.print(b.allocator, "pub const {s} align(4) = @embedFile(\"{s}\").*;\n", .{ ident, spv }) catch @panic("OOM");
    }
    const shaders_mod = b.createModule(.{ .root_source_file = wf.add("shaders.zig", index.items) });
    zpui.addImport("vulkan_shaders", shaders_mod);

    const render_test = b.addExecutable(.{
        .name = "render-test",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/render_test.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(render_test);
    const run = b.addRunArtifact(render_test);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    const step = b.step("render-test", "Render the showcase scene offscreen to zig-out/render-test.png and compare with tests/golden");
    step.dependOn(&run.step);
}

/// Linux platform backend (src/platform/linux/): wayland-scanner protocol
/// bindings, the `linux_c` translate-c module (wayland, xkbcommon, Xlib/xcb),
/// system libraries, and the `linux-window` demo (`zig build linux-window`).
fn addLinuxPlatform(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (target.result.os.tag != .linux) return;

    const c = b.addTranslateC(.{
        .root_source_file = b.path("src/platform/linux/c.h"),
        .target = target,
        .optimize = optimize,
    });
    const protocols = [_][]const u8{
        "xdg-shell",              "xdg-decoration-unstable-v1", "fractional-scale-v1",
        "viewporter",             "tablet-v2",                  "cursor-shape-v1",
        "text-input-unstable-v3", "org-kde-kwin-blur",
    };
    for (protocols) |name| {
        const xml = b.path(b.fmt("src/platform/linux/protocols/{s}.xml", .{name}));
        const header = b.addSystemCommand(&.{ "wayland-scanner", "client-header" });
        header.addFileArg(xml);
        c.addIncludePath(header.addOutputFileArg(b.fmt("{s}-client-protocol.h", .{name})).dirname());
        const code = b.addSystemCommand(&.{ "wayland-scanner", "private-code" });
        code.addFileArg(xml);
        zpui.addCSourceFile(.{ .file = code.addOutputFileArg(b.fmt("{s}-protocol.c", .{name})) });
    }
    zpui.addImport("linux_c", c.createModule());
    zpui.link_libc = true;
    for ([_][]const u8{
        "wayland-client", "wayland-cursor", "xkbcommon", "xkbcommon-x11",
        "X11",            "X11-xcb",        "xcb",       "xcb-xkb",
        "Xcursor",        "Xi",
    }) |lib| zpui.linkSystemLibrary(lib, .{});

    const demo = b.addExecutable(.{
        .name = "linux-window",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/linux_window.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(demo);
    const run = b.addRunArtifact(demo);
    run.addPassthruArgs();
    const step = b.step("linux-window", "Open the Linux platform demo window (Wayland or X11)");
    step.dependOn(&run.step);
}

/// Metal renderer (src/renderer/metal/) on Apple targets: system frameworks,
/// the `render-test` harness, and `metal-check`, which compiles the renderer
/// and showcase scene to an object file. Cross builds from non-macOS hosts
/// have no SDK to link frameworks against, so there `zig build` only runs
/// `metal-check` (`zig build -Dtarget=aarch64-macos`); CI links and runs on macOS.
fn addMetalRenderer(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (!target.result.os.tag.isDarwin()) return;
    const native = @import("builtin").os.tag.isDarwin();

    const check = b.addObject(.{
        .name = "metal-check",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/metal_check.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    const install_check = b.addInstallFile(check.getEmittedBin(), "metal-check.o");
    const check_step = b.step("metal-check", "Compile the Metal renderer to zig-out/metal-check.o (no SDK needed)");
    check_step.dependOn(&install_check.step);
    if (!native) {
        b.getInstallStep().dependOn(&install_check.step);
        return;
    }

    zpui.link_libc = true;
    zpui.linkSystemLibrary("objc", .{});
    for ([_][]const u8{ "Foundation", "CoreGraphics", "QuartzCore", "Metal" }) |name| zpui.linkFramework(name, .{});
    // Only reached through objc_getClass("MPSImageGaussianBlur"); keep it linked.
    zpui.linkFramework("MetalPerformanceShaders", .{ .needed = true });

    const render_test = b.addExecutable(.{
        .name = "render-test",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/render_test.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(render_test);
    const run = b.addRunArtifact(render_test);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    const step = b.step("render-test", "Render the showcase scene offscreen with Metal to zig-out/render-test.png");
    step.dependOn(&run.step);
}

/// zeron design system: `zeron_theme` (apps/zeron/src/theme) and
/// `zeron_assets` (generated apps/zeron/src/assets.zig, compiled next to a
/// copy of apps/zeron/assets/ so its @embedFile paths resolve), plus tests.
fn addZeronDesign(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
    test_step: *std.Build.Step,
) void {
    const theme = b.addModule("zeron_theme", .{
        .root_source_file = b.path("apps/zeron/src/theme/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{.{ .name = "zpui", .module = zpui }},
    });
    test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .root_module = theme })).step);

    const files = b.addWriteFiles();
    _ = files.addCopyDirectory(b.path("apps/zeron/assets"), "assets", .{});
    const assets = b.addModule("zeron_assets", .{
        .root_source_file = files.addCopyFile(b.path("apps/zeron/src/assets.zig"), "assets.zig"),
        .target = target,
        .optimize = optimize,
    });
    test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .root_module = assets })).step);
}

/// Linux text backend (src/text/freetype.zig): FreeType, HarfBuzz and fontconfig
/// via the `freetype_c` translate-c module, plus the `text-dump` CPU raster check
/// (`zig build text-dump` writes zig-out/text-dump.png).
fn addLinuxText(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (target.result.os.tag != .linux) return;
    const c = b.addTranslateC(.{
        .root_source_file = b.path("src/text/freetype_c.h"),
        .target = target,
        .optimize = optimize,
    });
    c.addSystemIncludePath(.{ .cwd_relative = "/usr/include/freetype2" });
    c.addSystemIncludePath(.{ .cwd_relative = "/usr/include/harfbuzz" });
    zpui.addImport("freetype_c", c.createModule());
    zpui.link_libc = true;
    for ([_][]const u8{ "freetype2", "harfbuzz", "fontconfig" }) |lib| zpui.linkSystemLibrary(lib, .{});

    const dump = b.addExecutable(.{
        .name = "text-dump",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/text_dump.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(dump);
    const run = b.addRunArtifact(dump);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    const step = b.step("text-dump", "Rasterize a sample paragraph on the CPU to zig-out/text-dump.png");
    step.dependOn(&run.step);
}

/// macOS platform backend (src/platform/mac/) + CoreText (src/text/coretext.zig):
/// AppKit/CoreText/CoreVideo/Carbon frameworks, the `mac-window` demo
/// (`zig build mac-window`; `ZPUI_SMOKE_FRAMES=30` makes it render 30 frames,
/// write zig-out/mac-window*.png and exit), and `mac-check`, an object-only
/// compile of the backend that works from non-macOS hosts without an SDK.
fn addMacPlatform(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (target.result.os.tag != .macos) return;
    const native = @import("builtin").os.tag == .macos;

    const check = b.addObject(.{
        .name = "mac-check",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/mac_check.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    const install_check = b.addInstallFile(check.getEmittedBin(), "mac-check.o");
    const check_step = b.step("mac-check", "Compile the macOS platform backend + demo to zig-out/mac-check.o (no SDK needed)");
    check_step.dependOn(&install_check.step);
    if (!native) {
        b.getInstallStep().dependOn(&install_check.step);
        return;
    }

    zpui.link_libc = true;
    for ([_][]const u8{ "AppKit", "CoreFoundation", "CoreText", "CoreVideo", "Carbon" }) |name| zpui.linkFramework(name, .{});

    const demo = b.addExecutable(.{
        .name = "mac-window",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/mac_window.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    b.installArtifact(demo);
    const run = b.addRunArtifact(demo);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    const step = b.step("mac-window", "Run the macOS window demo (ZPUI_SMOKE_FRAMES=N for the CI smoke test)");
    step.dependOn(&run.step);
}

/// zeron syntax highlighting (apps/zeron/src/syntax): the vendored tree-sitter
/// runtime + grammars (vendor/tree-sitter/tree_sitter_build.zig), the
/// `zeron_syntax` module, and its tests.
fn addZeronSyntax(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    test_step: *std.Build.Step,
) void {
    const ts = @import("vendor/tree-sitter/tree_sitter_build.zig").add(b, target, optimize);
    const syntax = b.addModule("zeron_syntax", .{
        .root_source_file = b.path("apps/zeron/src/syntax/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    ts.addTo(syntax);
    const run = b.addRunArtifact(b.addTest(.{ .root_module = syntax }));
    test_step.dependOn(&run.step);
    b.step("syntax-test", "Run only the zeron_syntax tests").dependOn(&run.step);
}

/// Image + SVG support (src/image/): the vendored lunasvg/plutovg, stb_image
/// and simplewebp compiled into `zpui` (src/image/image_build.zig), plus the
/// `icon-sheet` visual check (`zig build icon-sheet` writes zig-out/icon-sheet.png).
fn addImageSupport(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    @import("src/image/image_build.zig").add(b, zpui);

    const sheet = b.addExecutable(.{
        .name = "icon-sheet",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/icon_sheet.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{.{ .name = "zpui", .module = zpui }},
        }),
    });
    const run = b.addRunArtifact(sheet);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    const step = b.step("icon-sheet", "Rasterize every zeron icon + sample images to zig-out/icon-sheet.png");
    step.dependOn(&run.step);
}

/// zeron markdown (apps/zeron/src/markdown: pulldown-cmark 0.12 port, block
/// model, incremental reparse, streaming mend) and diff (apps/zeron/src/diff:
/// unified patch parser, `similar` Myers/Patience port) modules + their
/// parity tests.
fn addZeronMarkdownDiff(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    test_step: *std.Build.Step,
) void {
    inline for (.{
        .{ "zeron_markdown", "apps/zeron/src/markdown/root.zig" },
        .{ "zeron_diff", "apps/zeron/src/diff/root.zig" },
    }) |m| {
        const mod = b.addModule(m[0], .{
            .root_source_file = b.path(m[1]),
            .target = target,
            .optimize = optimize,
        });
        test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .name = m[0], .root_module = mod })).step);
    }
}

/// zeron app state (apps/zeron/src/model: view logic, settings, engine-backed
/// stores as zpui entities) and the `zeron_actions` module
/// (apps/zeron/src/actions.zig + keymap.zig). `zig build zeron-view-test`
/// runs only the pure parts (no zpui); `zig build zeron-model-test` runs all.
/// `-Dzeron-live=/path/to/zeron` adds a live test against `zeron headless`.
fn addZeronModel(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
    test_step: *std.Build.Step,
) void {
    const engine = b.modules.get("zeron_engine").?;
    const theme = b.modules.get("zeron_theme").?;
    const options = b.addOptions();
    options.addOption(?[]const u8, "live_zeron", b.option([]const u8, "zeron-live", "Path to a zeron binary for the live model test"));

    const pure = b.createModule(.{
        .root_source_file = b.path("apps/zeron/src/model/pure_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zeron_engine", .module = engine },
            .{ .name = "zeron_theme", .module = theme },
        },
    });
    const run_pure = b.addRunArtifact(b.addTest(.{ .name = "zeron_view", .root_module = pure }));
    b.step("zeron-view-test", "Run the pure zeron model tests (view parity, settings)").dependOn(&run_pure.step);

    const model = b.addModule("zeron_model", .{
        .root_source_file = b.path("apps/zeron/src/model/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zpui", .module = zpui },
            .{ .name = "zeron_engine", .module = engine },
            .{ .name = "zeron_theme", .module = theme },
            .{ .name = "model_options", .module = options.createModule() },
        },
    });
    const actions = b.addModule("zeron_actions", .{
        .root_source_file = b.path("apps/zeron/src/actions.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zpui", .module = zpui },
            .{ .name = "zeron_model", .module = model },
        },
    });
    const run_model = b.addRunArtifact(b.addTest(.{ .name = "zeron_model", .root_module = model }));
    const run_actions = b.addRunArtifact(b.addTest(.{ .name = "zeron_actions", .root_module = actions }));
    const model_step = b.step("zeron-model-test", "Run the zeron model + actions tests");
    model_step.dependOn(&run_pure.step);
    model_step.dependOn(&run_model.step);
    model_step.dependOn(&run_actions.step);
    test_step.dependOn(model_step);
}

/// `zig build hello`: the gpui-style Counter example (examples/hello.zig) on the Linux
/// backend, with Geist fonts and icons from `zeron_assets`.
fn addHelloExample(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (target.result.os.tag != .linux) return;
    const assets = b.modules.get("zeron_assets") orelse return;
    const exe = b.addExecutable(.{
        .name = "hello",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/hello.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zpui", .module = zpui },
                .{ .name = "zeron_assets", .module = assets },
            },
        }),
    });
    b.installArtifact(exe);
    const run = b.addRunArtifact(exe);
    run.addPassthruArgs();
    const step = b.step("hello", "Run the zpui hello example (Counter view)");
    step.dependOn(&run.step);
}

/// zeron terminal core: vendored Ghostty VT (vendor/ghostty-vt, ported to Zig
/// 0.17; `ghostty-vt` module) + the zeron wrapper (apps/zeron/src/terminal,
/// `zeron_terminal`). `zig build terminal-test` runs only the wrapper tests;
/// `zig build ghostty-vt-test` runs the full vendored Ghostty suite (~2.8k
/// tests, slow in Debug); `zig build term-dump` renders a shell command's
/// final screen to zig-out/term-dump.png (Linux, FreeType text system).
fn addZeronTerminal(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
    test_step: *std.Build.Step,
) void {
    const vt = @import("vendor/ghostty-vt/module.zig").module(b, .{ .target = target, .optimize = optimize });
    const term = b.addModule("zeron_terminal", .{
        .root_source_file = b.path("apps/zeron/src/terminal/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true, // pty.zig (forkpty)
        .imports = &.{.{ .name = "ghostty-vt", .module = vt }},
    });
    const term_tests = b.addRunArtifact(b.addTest(.{ .root_module = term }));
    term_tests.setCwd(b.path("."));
    test_step.dependOn(&term_tests.step);
    b.step("terminal-test", "Run only the zeron_terminal tests").dependOn(&term_tests.step);

    const vt_test_mod = @import("vendor/ghostty-vt/module.zig").module(b, .{ .target = target, .optimize = optimize, .slow_runtime_safety = true });
    const vt_tests = b.addRunArtifact(b.addTest(.{ .root_module = vt_test_mod }));
    vt_tests.setCwd(b.path("vendor/ghostty-vt")); // snapshot golden files are cwd-relative
    b.step("ghostty-vt-test", "Run the vendored Ghostty terminal test suite").dependOn(&vt_tests.step);

    if (target.result.os.tag != .linux) return;
    const theme = b.modules.get("zeron_theme") orelse return;
    const dump = b.addExecutable(.{
        .name = "term-dump",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/term_dump.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zpui", .module = zpui },
                .{ .name = "zeron_terminal", .module = term },
                .{ .name = "zeron_theme", .module = theme },
            },
        }),
    });
    b.installArtifact(dump);
    const run = b.addRunArtifact(dump);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    b.step("term-dump", "Run a command under a PTY and render the terminal to zig-out/term-dump.png").dependOn(&run.step);
}

/// zeron text editor + composer: `zeron_input` (apps/zeron/src/ui/input: the
/// reusable `TextInput` editor, port of Rust `ComposerInput`) and
/// `zeron_composer` (apps/zeron/src/ui/composer: `ComposerView`), their tests,
/// and `zig build composer-demo` (examples/composer_demo.zig, Linux).
fn addZeronComposer(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
    test_step: *std.Build.Step,
) void {
    const theme = b.modules.get("zeron_theme") orelse return;
    const model = b.modules.get("zeron_model") orelse return;
    const actions = b.modules.get("zeron_actions") orelse return;
    const engine = b.modules.get("zeron_engine") orelse return;
    const assets = b.modules.get("zeron_assets") orelse return;
    const input = b.addModule("zeron_input", .{
        .root_source_file = b.path("apps/zeron/src/ui/input/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zpui", .module = zpui },
            .{ .name = "zeron_theme", .module = theme },
            .{ .name = "zeron_actions", .module = actions },
        },
    });
    const composer = b.addModule("zeron_composer", .{
        .root_source_file = b.path("apps/zeron/src/ui/composer/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zpui", .module = zpui },
            .{ .name = "zeron_theme", .module = theme },
            .{ .name = "zeron_actions", .module = actions },
            .{ .name = "zeron_model", .module = model },
            .{ .name = "zeron_engine", .module = engine },
            .{ .name = "zeron_assets", .module = assets },
            .{ .name = "zeron_input", .module = input },
        },
    });
    const run_input = b.addRunArtifact(b.addTest(.{ .name = "zeron_input", .root_module = input }));
    const run_composer = b.addRunArtifact(b.addTest(.{ .name = "zeron_composer", .root_module = composer }));
    const step = b.step("composer-test", "Run the zeron editor + composer tests");
    step.dependOn(&run_input.step);
    step.dependOn(&run_composer.step);
    test_step.dependOn(step);

    if (target.result.os.tag != .linux) return;
    const exe = b.addExecutable(.{
        .name = "composer-demo",
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/zeron/examples/composer_demo.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zpui", .module = zpui },
                .{ .name = "zeron_assets", .module = assets },
                .{ .name = "zeron_theme", .module = theme },
                .{ .name = "zeron_actions", .module = actions },
                .{ .name = "zeron_model", .module = model },
                .{ .name = "zeron_engine", .module = engine },
                .{ .name = "zeron_input", .module = input },
                .{ .name = "zeron_composer", .module = composer },
            },
        }),
    });
    b.installArtifact(exe);
    const run = b.addRunArtifact(exe);
    run.addPassthruArgs();
    b.step("composer-demo", "Run the zeron composer demo window").dependOn(&run.step);
}

/// zeron transcript + markdown UI: `zeron_ui_markdown` (apps/zeron/src/ui/markdown,
/// the reusable BlockTree → elements renderer) and `zeron_ui_transcript`
/// (apps/zeron/src/ui/transcript, `TranscriptView`), their tests, and the
/// `transcript-demo` harness (`zig build transcript-demo -- --help`).
fn addZeronTranscriptUi(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
    test_step: *std.Build.Step,
) void {
    const theme = b.modules.get("zeron_theme") orelse return;
    const assets = b.modules.get("zeron_assets") orelse return;
    const markdown = b.modules.get("zeron_markdown") orelse return;
    const syntax = b.modules.get("zeron_syntax") orelse return;
    const diff = b.modules.get("zeron_diff") orelse return;
    const model = b.modules.get("zeron_model") orelse return;
    const engine = b.modules.get("zeron_engine") orelse return;
    const ui_md = b.addModule("zeron_ui_markdown", .{
        .root_source_file = b.path("apps/zeron/src/ui/markdown/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zpui", .module = zpui },
            .{ .name = "zeron_theme", .module = theme },
            .{ .name = "zeron_assets", .module = assets },
            .{ .name = "zeron_markdown", .module = markdown },
            .{ .name = "zeron_syntax", .module = syntax },
        },
    });
    const ui_tr = b.addModule("zeron_ui_transcript", .{
        .root_source_file = b.path("apps/zeron/src/ui/transcript/root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zpui", .module = zpui },
            .{ .name = "zeron_theme", .module = theme },
            .{ .name = "zeron_assets", .module = assets },
            .{ .name = "zeron_markdown", .module = markdown },
            .{ .name = "zeron_syntax", .module = syntax },
            .{ .name = "zeron_diff", .module = diff },
            .{ .name = "zeron_model", .module = model },
            .{ .name = "zeron_engine", .module = engine },
            .{ .name = "zeron_ui_markdown", .module = ui_md },
        },
    });
    const md_tests = b.addRunArtifact(b.addTest(.{ .name = "zeron_ui_markdown", .root_module = ui_md }));
    const tr_tests = b.addRunArtifact(b.addTest(.{ .name = "zeron_ui_transcript", .root_module = ui_tr }));
    const ui_step = b.step("transcript-test", "Run the zeron transcript + markdown UI tests");
    ui_step.dependOn(&md_tests.step);
    ui_step.dependOn(&tr_tests.step);
    test_step.dependOn(ui_step);

    if (target.result.os.tag != .linux) return;
    const demo = b.addExecutable(.{
        .name = "transcript-demo",
        .root_module = b.createModule(.{
            .root_source_file = b.path("apps/zeron/src/ui/transcript/demo.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zpui", .module = zpui },
                .{ .name = "zeron_theme", .module = theme },
                .{ .name = "zeron_assets", .module = assets },
                .{ .name = "zeron_model", .module = model },
                .{ .name = "zeron_engine", .module = engine },
                .{ .name = "zeron_ui_transcript", .module = ui_tr },
            },
        }),
    });
    b.installArtifact(demo);
    const run = b.addRunArtifact(demo);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    b.step("transcript-demo", "Render transcript fixtures in a window (apps/zeron/fixtures/transcript-*.json)").dependOn(&run.step);
}

/// The zeron desktop app (apps/zeron/src/main.zig): `zig build zeron` builds it,
/// `zig build run-zeron -- [--fixtures dir] [--frames n]` runs it. On a non-macOS
/// host targeting macOS it compiles to an object only (zig-out/zeron-mac-check.o).
fn addZeronApp(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
    test_step: *std.Build.Step,
) void {
    const os = target.result.os.tag;
    if (os != .linux and os != .macos) return;
    const names = [_][]const u8{ "zeron_assets", "zeron_theme", "zeron_model", "zeron_engine", "zeron_actions", "zeron_markdown", "zeron_diff", "zeron_syntax", "zeron_terminal", "zeron_input", "zeron_composer", "zeron_ui_markdown", "zeron_ui_transcript" };
    var imports: std.ArrayList(std.Build.Module.Import) = .empty;
    imports.append(b.allocator, .{ .name = "zpui", .module = zpui }) catch @panic("OOM");
    for (names) |n| if (b.modules.get(n)) |m| imports.append(b.allocator, .{ .name = n, .module = m }) catch @panic("OOM");
    const root = b.createModule(.{
        .root_source_file = b.path("apps/zeron/src/main.zig"),
        .target = target,
        .optimize = optimize,
        .imports = imports.items,
    });
    const step = b.step("zeron", "Build the zeron desktop app");
    if (os == .macos and @import("builtin").os.tag != .macos) {
        const obj = b.addObject(.{ .name = "zeron-mac-check", .root_module = root });
        const install = b.addInstallFile(obj.getEmittedBin(), "zeron-mac-check.o");
        step.dependOn(&install.step);
        b.getInstallStep().dependOn(&install.step);
        return;
    }
    const exe = b.addExecutable(.{ .name = "zeron", .root_module = root });
    const install = b.addInstallArtifact(exe, .{});
    step.dependOn(&install.step);
    b.getInstallStep().dependOn(&install.step);
    const run = b.addRunArtifact(exe);
    run.setCwd(b.path("."));
    run.addPassthruArgs();
    b.step("run-zeron", "Run the zeron desktop app").dependOn(&run.step);

    // Headless shell/sidebar tests (TestPlatform + checked-in fixtures).
    const tests = b.addRunArtifact(b.addTest(.{ .name = "zeron_app", .root_module = root }));
    tests.setCwd(b.path("."));
    test_step.dependOn(&tests.step);
    b.step("zeron-app-test", "Run the zeron shell/sidebar tests").dependOn(&tests.step);
}

/// `zig build list-demo`: examples/list_demo.zig — virtualized chat list (10k rows),
/// entrance animations, edge fade, overlay scrollbar and a frosted panel (Linux).
fn addListDemo(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    zpui: *std.Build.Module,
) void {
    if (target.result.os.tag != .linux) return;
    const assets = b.modules.get("zeron_assets") orelse return;
    const exe = b.addExecutable(.{
        .name = "list-demo",
        .root_module = b.createModule(.{
            .root_source_file = b.path("examples/list_demo.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zpui", .module = zpui },
                .{ .name = "zeron_assets", .module = assets },
            },
        }),
    });
    const install = b.addInstallArtifact(exe, .{});
    const run = b.addRunArtifact(exe);
    run.step.dependOn(&install.step);
    run.addPassthruArgs();
    const step = b.step("list-demo", "Run the virtualized list demo (examples/list_demo.zig)");
    step.dependOn(&run.step);
}
