//! RPC method names, generated by apps/zeron/scripts/gen_methods.py from
//! zeron `crates/rpc/src/lib.rs` (`pub mod methods`). Do not edit by hand.
//! Stream classification is derived from `crates/engine/src/rpc.rs`.

pub const Kind = enum { unary, stream };

pub const Method = enum {
    WatchPreviews,
    ListHarnesses,
    CancelInstall,
    InstallHarness,
    /// Flip a harness's enablement on the target device (Settings → Providers);
    /// replies with the device's fresh `ListHarnesses` catalog.
    GetTitleSettings,
    SetTitleSettings,
    SetHarnessEnabled,
    ListModels,
    ListSkills,
    ListCommands,
    QueueCommand,
    TakeProjectActionSetup,
    /// Peer-to-peer delivery fallback: the SENDER's engine forwards a queued
    /// command entry (client-minted id and all) straight over the device-room
    /// link when its chat2 rows can't reach the edge but the host's peer link
    /// is alive. The host claims the id in its processed ledger before
    /// executing, so the doc row arriving later dedupes to a no-op —
    /// exactly-once by construction. Params `{chatId, entry}`.
    RelayCommand,
    /// User-driven delivery retry for a chat with unadopted queued sends:
    /// fresh chat2 socket, host nudge, drain pass, and a new delivery escort
    /// per pending command. Params `{chatId}`; IPC-only.
    RetryDelivery,
    ForkSideChat,
    WatchDocMessages,
    /// Explicit user navigation, `{chatId}`. Prioritizes this device's sync
    /// connection; automatic subscriptions and retries must not call it.
    FocusChat,
    /// Messages typed while the agent was busy, held on the chat doc so every
    /// device sees the same queue. `{ chatId }` → `{ items: QueuedMessage[] }`.
    WatchQueue,
    /// Append to the queue. `{ chatId, text, attachments?, holdForTurnEnd? }` → `{ id }`.
    QueueMessage,
    /// Retype a queued message; empty text deletes it.
    /// `{ chatId, id, text }` → `{ changed }`.
    UpdateQueuedMessage,
    /// Acquire a host-authoritative edit lease for one queued row.
    BeginQueuedMessageEdit,
    /// Renew an acquired queue edit lease.
    RenewQueuedMessageEdit,
    /// Commit, cancel, discard, or explicitly release an acquired edit.
    FinishQueuedMessageEdit,
    /// Reorder. `{ chatId, id, toIndex }` → `{ changed }`.
    MoveQueuedMessage,
    RemoveQueuedMessage,
    /// Interrupt whatever is running and send this one. `{ chatId, id }` → `{ sent }`.
    SendQueuedMessageNow,
    /// Steer this row into the live turn without interrupting it.
    /// `{ chatId, id }` → `{ sent }`.
    SteerQueuedMessageNow,
    /// Nudge every open room client to verify liveness NOW (window focus,
    /// app foregrounded). No params; IPC-only. Each room ignores the hint
    /// unless it has been broadcast-quiet ≥30s, so this is cheap to spam.
    ProbeSync,
    /// Live sync introspection (`zeron sync` / debug surfaces): per-room
    /// connection state, last pushed-frame/ack ages, rejoin/probe/resync
    /// counters for the workspace room and every open chat doc. No params;
    /// IPC-only.
    SyncStatus,
    /// Pushed edge-connectivity posture (`zeron_proto::Connectivity`):
    /// current value first, then every change — the connection pill /
    /// composer-honesty / queued-badge feed. No params; IPC-only.
    WatchConnectivity,
    /// In-flight queued-attachment transfers (`zeron_proto::TransferProgress`
    /// list): current set first, then a fresh snapshot per landed chunk —
    /// the sending thumbnail's percent-ring feed. No params; IPC-only.
    WatchTransfers,
    WatchChats,
    WatchSidebarPreferences,
    WatchDevices,
    WatchSessions,
    /// Spaces registry (device+folder pairs) from the workspace doc.
    WatchSpaces,
    /// Entity mutations against the workspace doc (feature-inventory §2 DataRpc).
    /// Params are tagged `{op: createChat|createSpace|renameSpace|deleteSpace|
    /// renameChat|setChatArchived|deleteChat|renameDevice|markChatSeen, …}`.
    Mutate,
    /// This engine's identity → `{deviceId}` (IPC-only; never relay-forwarded —
    /// the answer is about whichever engine you are directly connected to).
    LocalDevice,
    /// This engine runtime's fixed device and workspace identity.
    EngineInfo,
    /// Readiness barrier for the engine runtime. The call completes once stores
    /// and journals are assembled, or fails with the assembly error.
    EngineReady,
    /// Ask a headless IPC owner to drain its runtime and exit successfully.
    /// Headed IPC owners do not implement this method: closing another app's
    /// engine behind its windows would leave that process unusable.
    StopEngine,
    AuthStatus,
    SignIn,
    SignInHeadless,
    CompleteSignIn,
    SignOut,
    ListOrgs,
    CreateOrg,
    SelectOrg,
    /// One-time local→synced profile import: what's importable (unary).
    LocalImportStatus,
    /// One-time local→synced profile import: run it (stream of progress items).
    ImportLocalWorkspace,
    ListRepos,
    AddRepo,
    CloneRepo,
    CreateRepo,
    ListBranches,
    ListRefs,
    ListGitHistory,
    /// Fuzzy commit-subject / SHA search over the complete public history.
    SearchGitHistory,
    /// Resolve hosted profile images for a page of Git commit authors.
    ResolveGitAvatars,
    /// Update remote-tracking refs without changing HEAD, the index, or files.
    FetchAll,
    SwitchRef,
    ListFolders,
    /// The device's browse roots: home plus mounted drives/volumes.
    ListDrives,
    /// Fuzzy relative-path search rooted in a known chat or space checkout.
    SearchFiles,
    ListWorkspaceDirectory,
    SearchWorkspaceFiles,
    ReadWorkspaceImage,
    ReadWorkspaceFile,
    MoveWorkspaceEntry,
    DeleteWorkspaceEntry,
    WriteWorkspaceFile,
    WatchWorkspaceFiles,
    CreateWorktree,
    DeleteWorktree,
    ListProjectActions,
    UpsertProjectAction,
    DeleteProjectAction,
    RunProjectAction,
    OpenTerminal,
    SubscribeTerminal,
    WriteTerminal,
    ResizeTerminal,
    CloseTerminal,
    /// Checkout-diff stream for the target device's chats (DataRpc,
    /// relay-forwardable — diffs are produced where the checkout lives).
    WatchCheckoutDiffs,
    WatchWorkspaceGitStatus,
    /// Current pull request for one checkout, resolved on the checkout's host device.
    WatchCheckoutChangeRequest,
    GetCheckoutDiff,
    /// Permanently restore one chat-owned checkout to its current HEAD and
    /// remove only its untracked, non-ignored paths.
    DiscardWorkingTree,
    GetCheckoutFileDiffText,
    ListAgentAccounts,
    ActivateAgentAccount,
    ForgetAgentAccount,
    StartAgentLogin,
    CompleteAgentLogin,
    PollAgentLogin,
    CancelAgentLogin,
    UploadChunk,
    UploadCommit,
    ReadAttachmentChunk,
    /// Lazy full-tool-output fetch from the R2 sidecar by doc-resident ref
    /// (chat2-sync A3). Edge-direct from any device — never relay-forwarded.
    FetchToolBlob,
    UpdateStatus,
    /// Download + apply the newest release on the target device (symlink-managed
    /// installs; the service restart is scheduled after the reply flushes).
    ApplyUpdate,
    /// Device-local agent CLI update lifecycle. The stream emits the complete
    /// ordered status list initially and after every transition.
    WatchHarnessUpdates,
    CheckHarnessUpdates,
    ApplyHarnessUpdate,
    CancelHarnessUpdate,
    DismissHarnessUpdate,
    SetHarnessUpdatePolicy,

    /// Wire name (identical to the tag name).
    pub fn name(m: Method) []const u8 {
        return @tagName(m);
    }

    /// Whether the engine answers with `{id,item}*` frames instead of one `{id,ok}`.
    pub fn kind(m: Method) Kind {
        return switch (m) {
            .AuthStatus,
            .ImportLocalWorkspace,
            .SubscribeTerminal,
            .UpdateStatus,
            .WatchChats,
            .WatchCheckoutChangeRequest,
            .WatchCheckoutDiffs,
            .WatchConnectivity,
            .WatchDevices,
            .WatchDocMessages,
            .WatchHarnessUpdates,
            .WatchPreviews,
            .WatchQueue,
            .WatchSessions,
            .WatchSidebarPreferences,
            .WatchSpaces,
            .WatchTransfers,
            .WatchWorkspaceFiles,
            .WatchWorkspaceGitStatus => .stream,
            else => .unary,
        };
    }
};

/// Number of methods in zeron_rpc::methods.
pub const count = 109;

/// Every method, in source order.
pub const all = std.enums.values(Method);

const std = @import("std");

test "method table is complete" {
    try std.testing.expectEqual(@as(usize, 109), all.len);
    try std.testing.expectEqual(Kind.stream, Method.WatchDocMessages.kind());
    try std.testing.expectEqual(Kind.unary, Method.EngineInfo.kind());
}
