//! Parity against the Rust pipeline's dumps in testdata/rust (generated by
//! apps/zeron/scripts/mermaid_parity.rs): layout geometry per fixture.

const std = @import("std");
const parser = @import("parser.zig");
const layout_mod = @import("layout/layout.zig");
const theme_mod = @import("theme.zig");
const LayoutConfig = @import("config.zig").LayoutConfig;

const dir = "apps/zeron/src/mermaid/testdata";

pub fn zeronLayoutOptions() LayoutConfig {
    return .{ .node_spacing = 36.0, .rank_spacing = 40.0, .node_padding_x = 18.0, .node_padding_y = 10.0 };
}

const Diff = struct { max: f32 = 0, what: []const u8 = "" };

fn num(v: std.json.Value) f32 {
    return switch (v) {
        .float => |f| @floatCast(f),
        .integer => |i| @floatFromInt(i),
        else => std.math.nan(f32),
    };
}

fn note(d: *Diff, a: f32, b: f32, what: []const u8) void {
    const delta = @abs(a - b);
    if (delta > d.max or std.math.isNan(delta)) {
        d.max = if (std.math.isNan(delta)) std.math.inf(f32) else delta;
        d.what = what;
    }
}

test "layout parity with mermaid-rs-renderer" {
    const gpa = std.testing.allocator;
    var io_threaded: std.Io.Threaded = .init_single_threaded;
    const io = io_threaded.io();
    var d = std.Io.Dir.cwd().openDir(io, dir, .{ .iterate = true }) catch return error.SkipZigTest;
    defer d.close(io);
    var names: std.ArrayList([]const u8) = .empty;
    defer {
        for (names.items) |n| gpa.free(n);
        names.deinit(gpa);
    }
    var it = d.iterate();
    while (try it.next(io)) |e| if (std.mem.endsWith(u8, e.name, ".mmd")) try names.append(gpa, try gpa.dupe(u8, e.name));
    std.mem.sort([]const u8, names.items, {}, struct {
        fn lt(_: void, x: []const u8, y: []const u8) bool {
            return std.mem.order(u8, x, y) == .lt;
        }
    }.lt);
    var failures: usize = 0;
    for (names.items) |name| {
        var arena = std.heap.ArenaAllocator.init(gpa);
        defer arena.deinit();
        const a = arena.allocator();
        const src = try d.readFileAlloc(io, name, a, .limited(1 << 20));
        const stem = name[0 .. name.len - 4];
        const json_src = d.readFileAlloc(io, try std.fmt.allocPrint(a, "rust/{s}.layout.json", .{stem}), a, .limited(8 << 20)) catch continue;
        const ref = try std.json.parseFromSliceLeaky(std.json.Value, a, json_src, .{});
        var p = try parser.Parser.init(a);
        const graph = p.parse(src) catch |err| {
            std.debug.print("{s}: parse error {t}: {s}\n", .{ stem, err, p.message });
            failures += 1;
            continue;
        };
        var theme = try theme_mod.Theme.modern(a);
        theme.font_family = "Geist";
        theme.font_size = 14.0;
        const config = zeronLayoutOptions();
        if (graph.kind == .gantt) theme.primary_border_color = "#9285f6";
        const lay = try layout_mod.computeLayout(a, &graph, &theme, &config);
        var diff: Diff = .{};
        note(&diff, lay.width, num(ref.object.get("width").?), "width");
        note(&diff, lay.height, num(ref.object.get("height").?), "height");
        const rnodes = ref.object.get("nodes").?.array.items;
        if (rnodes.len != lay.nodes.len()) {
            std.debug.print("{s}: node count {d} vs {d}\n", .{ stem, lay.nodes.len(), rnodes.len });
            failures += 1;
            continue;
        }
        for (rnodes) |rn| {
            const id = rn.object.get("id").?.string;
            const n = lay.nodes.get(id) orelse {
                diff.max = std.math.inf(f32);
                diff.what = id;
                continue;
            };
            note(&diff, n.x, num(rn.object.get("x").?), try std.fmt.allocPrint(a, "{s}.x", .{id}));
            note(&diff, n.y, num(rn.object.get("y").?), try std.fmt.allocPrint(a, "{s}.y", .{id}));
            note(&diff, n.width, num(rn.object.get("width").?), try std.fmt.allocPrint(a, "{s}.w", .{id}));
            note(&diff, n.height, num(rn.object.get("height").?), try std.fmt.allocPrint(a, "{s}.h", .{id}));
        }
        const redges = ref.object.get("edges").?.array.items;
        var edge_points_mismatch: usize = 0;
        for (redges, 0..) |re, i| {
            if (i >= lay.edges.items.len) break;
            const rp = re.object.get("points").?.array.items;
            const lp = lay.edges.items[i].points.items;
            if (rp.len != lp.len) {
                edge_points_mismatch += 1;
                continue;
            }
            for (rp, lp, 0..) |r, l, k| {
                note(&diff, l[0], num(r.array.items[0]), try std.fmt.allocPrint(a, "e{d}.p{d}.x", .{ i, k }));
                note(&diff, l[1], num(r.array.items[1]), try std.fmt.allocPrint(a, "e{d}.p{d}.y", .{ i, k }));
            }
        }
        const ok = diff.max <= 0.5 and edge_points_mismatch == 0;
        std.debug.print("{s}: {s} max_delta={d:.3} ({s}) edge_point_count_mismatches={d}\n", .{ stem, if (ok) "OK" else "DIFF", diff.max, diff.what, edge_points_mismatch });
        if (!ok) failures += 1;
    }
    std.debug.print("layout parity failures: {d}/{d}\n", .{ failures, names.items.len });
}
