//! Span-for-span parity with the Rust zeron_syntax crate. testdata/parity.json
//! is generated by apps/zeron/scripts/syntax_parity.rs from the files in
//! testdata/samples (see that script for the rustc command line).

const std = @import("std");
const syntax = @import("root.zig");

const fixture = @embedFile("testdata/parity.json");

fn str(v: std.json.Value) ?[]const u8 {
    return switch (v) {
        .string => |s| s,
        else => null,
    };
}

fn langName(l: ?syntax.LanguageId) ?[]const u8 {
    return if (l) |x| x.debugName() else null;
}

fn eqlOpt(a: ?[]const u8, b: ?[]const u8) bool {
    if (a == null or b == null) return a == null and b == null;
    return std.mem.eql(u8, a.?, b.?);
}

test "highlight spans match the Rust implementation" {
    const gpa = std.testing.allocator;
    const parsed = try std.json.parseFromSlice(std.json.Value, gpa, fixture, .{});
    defer parsed.deinit();
    const cases = parsed.value.object.get("cases").?.array.items;
    try std.testing.expect(cases.len >= 25);

    var failures: usize = 0;
    for (cases) |case| {
        const obj = case.object;
        const path = str(obj.get("path").?);
        const fence = str(obj.get("fence").?);
        const source = str(obj.get("source").?).?;
        const label = path orelse fence orelse "<shebang>";
        var doc = syntax.highlight(gpa, .{ .source = source, .path = path, .fence_tag = fence }) catch |err| {
            std.debug.print("{s}: highlight failed: {t}\n", .{ label, err });
            failures += 1;
            continue;
        };
        defer doc.deinit(gpa);

        if (!std.mem.eql(u8, doc.language.debugName(), str(obj.get("language").?).?)) {
            std.debug.print("{s}: language {s}, expected {s}\n", .{ label, doc.language.debugName(), str(obj.get("language").?).? });
            failures += 1;
        }
        const lines = obj.get("lines").?.array.items;
        if (lines.len != doc.lineCount()) {
            std.debug.print("{s}: {d} lines, expected {d}\n", .{ label, doc.lineCount(), lines.len });
            failures += 1;
            continue;
        }
        var case_failures: usize = 0;
        for (lines, 0..) |expected_line, li| {
            const expected = expected_line.array.items;
            const actual = doc.line(li);
            var ok = expected.len == actual.len;
            if (ok) for (expected, actual) |e, a| {
                const t = e.array.items;
                if (t[0].integer != a.start or t[1].integer != a.end or !std.mem.eql(u8, str(t[2]).?, a.kind.name())) {
                    ok = false;
                    break;
                }
            };
            if (!ok) {
                case_failures += 1;
                if (case_failures <= 3) {
                    std.debug.print("{s}:{d}: span mismatch\n  expected:", .{ label, li + 1 });
                    for (expected) |e| std.debug.print(" [{d},{d},{s}]", .{ e.array.items[0].integer, e.array.items[1].integer, str(e.array.items[2]).? });
                    std.debug.print("\n  actual:  ", .{});
                    for (actual) |a| std.debug.print(" [{d},{d},{s}]", .{ a.start, a.end, a.kind.name() });
                    std.debug.print("\n", .{});
                }
            }
        }
        failures += case_failures;
    }
    try std.testing.expectEqual(@as(usize, 0), failures);
}

test "language detection matches the Rust implementation" {
    const gpa = std.testing.allocator;
    const parsed = try std.json.parseFromSlice(std.json.Value, gpa, fixture, .{});
    defer parsed.deinit();
    const root = parsed.value.object;
    var failures: usize = 0;
    for (root.get("paths").?.array.items) |row| {
        const t = row.array.items;
        const got = langName(syntax.languageForPath(str(t[0]).?));
        if (!eqlOpt(got, str(t[1]))) {
            std.debug.print("path {s}: {?s}, expected {?s}\n", .{ str(t[0]).?, got, str(t[1]) });
            failures += 1;
        }
    }
    for (root.get("aliases").?.array.items) |row| {
        const t = row.array.items;
        const got = langName(syntax.languageForAlias(str(t[0]).?));
        if (!eqlOpt(got, str(t[1]))) {
            std.debug.print("alias '{s}': {?s}, expected {?s}\n", .{ str(t[0]).?, got, str(t[1]) });
            failures += 1;
        }
    }
    for (root.get("detect").?.array.items) |row| {
        const t = row.array.items;
        const got = langName(syntax.detectLanguage(str(t[0]), str(t[1]), str(t[2])));
        if (!eqlOpt(got, str(t[3]))) {
            std.debug.print("detect {?s}/{?s}/{?s}: {?s}, expected {?s}\n", .{ str(t[0]), str(t[1]), str(t[2]), got, str(t[3]) });
            failures += 1;
        }
    }
    try std.testing.expectEqual(@as(usize, 0), failures);
}
