//! Wayland backend (gpui_linux `wayland/client.rs` + `wayland/window.rs`).
//!
//! libwayland-client with protocol bindings generated by wayland-scanner (see build.zig):
//! xdg-shell toplevels with optional server decorations (xdg-decoration), fractional
//! scaling (wp-fractional-scale + wp-viewporter, falling back to integer buffer scale),
//! `wl_surface.frame` pacing, seat input (pointer incl. axis_value120, keyboard via
//! xkbcommon with repeat + compose), text-input-v3 IME, wl_data_device clipboard,
//! cursor-shape-v1 cursors (wl_cursor theme fallback) and KDE blur.

const std = @import("std");
const linux = std.os.linux;
const c = @import("linux_c");
const platform = @import("../platform.zig");
const input = @import("../../input.zig");
const scene_mod = @import("../../scene.zig");
const atlas_mod = @import("../../atlas.zig");
const event_loop = @import("event_loop.zig");
const keyboard = @import("keyboard.zig");
const x11_uri = @import("x11.zig");
const common = @import("window_common.zig");
const util = @import("util.zig");
const Presenter = @import("presenter.zig").Presenter;
const LinuxPlatform = @import("linux.zig").LinuxPlatform;

const log = std.log.scoped(.wayland);
const Allocator = std.mem.Allocator;

fn fixedToF32(v: c.wl_fixed_t) f32 {
    return @as(f32, @floatFromInt(v)) / 256.0;
}

/// Iterates a `wl_array` of u32 (xdg_toplevel states).
fn arrayU32(arr: [*c]c.struct_wl_array) []const u32 {
    if (arr == null or arr.*.data == null) return &.{};
    const p: [*]const u32 = @ptrCast(@alignCast(arr.*.data.?));
    return p[0 .. arr.*.size / 4];
}

const text_mimes = [_][*:0]const u8{ "text/plain;charset=utf-8", "UTF8_STRING", "text/plain", "TEXT", "STRING" };

const Output = struct {
    output: *c.struct_wl_output,
    name: u32,
    x: i32 = 0,
    y: i32 = 0,
    width: i32 = 0,
    height: i32 = 0,
    scale: i32 = 1,
};

/// A selection offer and whether it carries text we can read.
const Offer = struct {
    offer: *c.struct_wl_data_offer,
    mime: ?[*:0]const u8 = null,
    mime_rank: usize = text_mimes.len,
    /// Offers `text/uri-list` (file drops / file-manager copies).
    uri_list: bool = false,
    /// Best image type offered (`platform.ClipboardImageFormat.preference` order).
    image: ?platform.ClipboardImageFormat = null,
    image_rank: usize = platform.ClipboardImageFormat.preference.len,
};

const image_mimes = blk: {
    var out: [platform.ClipboardImageFormat.preference.len][*:0]const u8 = undefined;
    for (platform.ClipboardImageFormat.preference, 0..) |f, i| out[i] = switch (f) {
        .png => "image/png",
        .jpeg => "image/jpeg",
        .gif => "image/gif",
        .webp => "image/webp",
        .bmp => "image/bmp",
        .tiff => "image/tiff",
        .svg => "image/svg+xml",
    };
    break :blk out;
};

/// The drag-and-drop offer over one of our surfaces.
const DndState = struct {
    offer: ?Offer = null,
    window: ?*Window = null,
    serial: u32 = 0,
    position: platform.Point = .zero,
    paths: std.ArrayList([]u8) = .empty,
    entered: bool = false,
};

pub const Client = struct {
    gpa: Allocator,
    plat: *LinuxPlatform,
    display: *c.struct_wl_display,
    registry: *c.struct_wl_registry,
    source: ?*event_loop.Source = null,
    read_prepared: bool = false,
    read_done: bool = false,
    broken: bool = false,

    // Globals.
    compositor: ?*c.struct_wl_compositor = null,
    compositor_version: u32 = 0,
    wm_base: ?*c.struct_xdg_wm_base = null,
    seat: ?*c.struct_wl_seat = null,
    seat_version: u32 = 0,
    shm: ?*c.struct_wl_shm = null,
    data_device_manager: ?*c.struct_wl_data_device_manager = null,
    decoration_manager: ?*c.struct_zxdg_decoration_manager_v1 = null,
    fractional_scale_manager: ?*c.struct_wp_fractional_scale_manager_v1 = null,
    viewporter: ?*c.struct_wp_viewporter = null,
    cursor_shape_manager: ?*c.struct_wp_cursor_shape_manager_v1 = null,
    text_input_manager: ?*c.struct_zwp_text_input_manager_v3 = null,
    blur_manager: ?*c.struct_org_kde_kwin_blur_manager = null,
    /// wlr-layer-shell (overlay windows; absent on GNOME / Mutter).
    layer_shell: ?*c.struct_zwlr_layer_shell_v1 = null,
    /// wlr-foreign-toplevel-management (the foreground app; wlroots compositors).
    toplevel_manager: ?*c.struct_zwlr_foreign_toplevel_manager_v1 = null,
    toplevels: std.ArrayList(*ForeignToplevel) = .empty,
    active_toplevel: ?*ForeignToplevel = null,
    foreground_cb: platform.Callback(void, void) = .{},
    outputs: std.ArrayList(Output) = .empty,

    // Seat devices.
    pointer: ?*c.struct_wl_pointer = null,
    kb: ?*c.struct_wl_keyboard = null,
    data_device: ?*c.struct_wl_data_device = null,
    cursor_shape_device: ?*c.struct_wp_cursor_shape_device_v1 = null,
    text_input: ?*c.struct_zwp_text_input_v3 = null,

    windows: std.ArrayList(*Window) = .empty,
    mouse_focus: ?*Window = null,
    keyboard_focus: ?*Window = null,

    // Pointer state.
    pointer_enter_serial: u32 = 0,
    last_button_serial: u32 = 0,
    last_serial: u32 = 0,
    mouse_position: platform.Point = .zero,
    pressed_button: ?input.MouseButton = null,
    click: common.ClickState = .{},
    scroll: common.WaylandScroll = .{},
    cursor_style: platform.CursorStyle = .arrow,
    cursor_theme: ?*c.struct_wl_cursor_theme = null,
    cursor_theme_scale: i32 = 0,
    cursor_surface: ?*c.struct_wl_surface = null,

    // Keyboard state.
    keyboard: keyboard.Keyboard,
    modifiers: input.Modifiers = .{},
    capslock: bool = false,
    repeat_rate: i32 = 25,
    repeat_delay: i32 = 600,
    repeat_timer: ?event_loop.TimerId = null,
    repeat_keycode: ?u32 = null,
    repeat_keystroke: keyboard.OwnedKeystroke = .{},

    // IME (text-input-v3).
    ime_enabled: bool = false,
    ime_preedit: ?[]u8 = null,

    // Clipboard.
    selection: ?Offer = null,
    pending_offers: std.ArrayList(Offer) = .empty,
    data_source: ?*c.struct_wl_data_source = null,
    clipboard_text: ?[]u8 = null,
    dnd: DndState = .{},

    pub fn create(gpa: Allocator, plat: *LinuxPlatform) !*Client {
        const display = c.wl_display_connect(null) orelse return error.WaylandConnectFailed;
        errdefer c.wl_display_disconnect(display);
        const self = try gpa.create(Client);
        errdefer gpa.destroy(self);
        self.* = .{
            .gpa = gpa,
            .plat = plat,
            .display = display,
            .registry = c.wl_display_get_registry(display) orelse return error.WaylandRegistry,
            .keyboard = try keyboard.Keyboard.init(),
        };
        _ = c.wl_registry_add_listener(self.registry, &registry_listener, self);
        // Globals, then the events they trigger (seat capabilities, output modes).
        if (c.wl_display_roundtrip(display) < 0) return error.WaylandRoundtrip;
        if (c.wl_display_roundtrip(display) < 0) return error.WaylandRoundtrip;
        if (self.compositor == null or self.wm_base == null) return error.WaylandMissingGlobals;

        self.source = try plat.loop.addFd(c.wl_display_get_fd(display), linux.EPOLL.IN, .{ .ctx = self, .func = onReadable });
        plat.loop.hooks = .{ .ctx = self, .before_wait = beforeWait, .after_dispatch = afterDispatch };
        return self;
    }

    pub fn destroy(self: *Client) void {
        while (self.windows.items.len > 0) self.windows.items[self.windows.items.len - 1].closeWindow();
        self.windows.deinit(self.gpa);
        if (self.source) |s| self.plat.loop.removeFd(s);
        self.plat.loop.hooks = .{};
        if (self.read_prepared) c.wl_display_cancel_read(self.display);
        if (self.repeat_timer) |t| self.plat.loop.cancelTimer(t);
        if (self.selection) |o| c.wl_data_offer_destroy(o.offer);
        self.resetDnd();
        for (self.pending_offers.items) |o| c.wl_data_offer_destroy(o.offer);
        self.pending_offers.deinit(self.gpa);
        if (self.data_source) |s| c.wl_data_source_destroy(s);
        if (self.clipboard_text) |t| self.gpa.free(t);
        if (self.ime_preedit) |t| self.gpa.free(t);
        if (self.cursor_theme) |t| c.wl_cursor_theme_destroy(t);
        if (self.cursor_surface) |s| c.wl_surface_destroy(s);
        for (self.toplevels.items) |t| {
            c.zwlr_foreign_toplevel_handle_v1_destroy(t.handle);
            self.gpa.destroy(t);
        }
        self.toplevels.deinit(self.gpa);
        self.outputs.deinit(self.gpa);
        self.keyboard.deinit();
        c.wl_display_disconnect(self.display);
        self.gpa.destroy(self);
    }

    // -- event loop integration ---------------------------------------------------------

    fn beforeWait(ctx: ?*anyopaque) void {
        const self: *Client = @ptrCast(@alignCast(ctx.?));
        if (self.broken) return;
        while (c.wl_display_prepare_read(self.display) != 0) {
            if (c.wl_display_dispatch_pending(self.display) < 0) return self.fail();
        }
        self.read_prepared = true;
        self.read_done = false;
        _ = c.wl_display_flush(self.display);
    }

    fn onReadable(ctx: ?*anyopaque, events: u32) void {
        const self: *Client = @ptrCast(@alignCast(ctx.?));
        if (!self.read_prepared) return;
        self.read_prepared = false;
        self.read_done = true;
        if (events & (linux.EPOLL.ERR | linux.EPOLL.HUP) != 0) {
            c.wl_display_cancel_read(self.display);
            return self.fail();
        }
        if (c.wl_display_read_events(self.display) < 0) self.fail();
    }

    fn afterDispatch(ctx: ?*anyopaque) void {
        const self: *Client = @ptrCast(@alignCast(ctx.?));
        if (self.read_prepared) {
            c.wl_display_cancel_read(self.display);
            self.read_prepared = false;
        }
        if (self.broken) return;
        if (c.wl_display_dispatch_pending(self.display) < 0) self.fail();
        _ = c.wl_display_flush(self.display);
    }

    fn fail(self: *Client) void {
        if (self.broken) return;
        self.broken = true;
        log.err("lost the Wayland connection (error {d})", .{c.wl_display_get_error(self.display)});
        self.plat.requestQuit();
    }

    // -- registry -----------------------------------------------------------------------

    const registry_listener: c.struct_wl_registry_listener = .{ .global = onGlobal, .global_remove = onGlobalRemove };

    fn bind(self: *Client, comptime T: type, name: u32, iface: *const c.struct_wl_interface, version: u32, max: u32) *T {
        return @ptrCast(c.wl_registry_bind(self.registry, name, iface, @min(version, max)).?);
    }

    fn onGlobal(data: ?*anyopaque, _: ?*c.struct_wl_registry, name: u32, iface_c: [*c]const u8, version: u32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const iface = std.mem.span(iface_c);
        const eql = std.mem.eql;
        if (eql(u8, iface, "wl_compositor")) {
            self.compositor_version = @min(version, 6);
            self.compositor = self.bind(c.struct_wl_compositor, name, &c.wl_compositor_interface, version, 6);
        } else if (eql(u8, iface, "xdg_wm_base")) {
            self.wm_base = self.bind(c.struct_xdg_wm_base, name, &c.xdg_wm_base_interface, version, 5);
            _ = c.xdg_wm_base_add_listener(self.wm_base, &wm_base_listener, self);
        } else if (eql(u8, iface, "wl_seat") and self.seat == null) {
            self.seat_version = @min(version, 8);
            self.seat = self.bind(c.struct_wl_seat, name, &c.wl_seat_interface, version, 8);
            _ = c.wl_seat_add_listener(self.seat, &seat_listener, self);
        } else if (eql(u8, iface, "wl_shm")) {
            self.shm = self.bind(c.struct_wl_shm, name, &c.wl_shm_interface, version, 1);
        } else if (eql(u8, iface, "wl_output")) {
            const out = self.bind(c.struct_wl_output, name, &c.wl_output_interface, version, 4);
            self.outputs.append(self.gpa, .{ .output = out, .name = name }) catch return;
            _ = c.wl_output_add_listener(out, &output_listener, self);
        } else if (eql(u8, iface, "wl_data_device_manager")) {
            self.data_device_manager = self.bind(c.struct_wl_data_device_manager, name, &c.wl_data_device_manager_interface, version, 3);
        } else if (eql(u8, iface, "zxdg_decoration_manager_v1")) {
            self.decoration_manager = self.bind(c.struct_zxdg_decoration_manager_v1, name, &c.zxdg_decoration_manager_v1_interface, version, 1);
        } else if (eql(u8, iface, "wp_fractional_scale_manager_v1")) {
            self.fractional_scale_manager = self.bind(c.struct_wp_fractional_scale_manager_v1, name, &c.wp_fractional_scale_manager_v1_interface, version, 1);
        } else if (eql(u8, iface, "wp_viewporter")) {
            self.viewporter = self.bind(c.struct_wp_viewporter, name, &c.wp_viewporter_interface, version, 1);
        } else if (eql(u8, iface, "wp_cursor_shape_manager_v1")) {
            self.cursor_shape_manager = self.bind(c.struct_wp_cursor_shape_manager_v1, name, &c.wp_cursor_shape_manager_v1_interface, version, 1);
        } else if (eql(u8, iface, "zwp_text_input_manager_v3")) {
            self.text_input_manager = self.bind(c.struct_zwp_text_input_manager_v3, name, &c.zwp_text_input_manager_v3_interface, version, 1);
        } else if (eql(u8, iface, "org_kde_kwin_blur_manager")) {
            self.blur_manager = self.bind(c.struct_org_kde_kwin_blur_manager, name, &c.org_kde_kwin_blur_manager_interface, version, 1);
        } else if (eql(u8, iface, "zwlr_layer_shell_v1") and std.c.getenv("ZPUI_NO_LAYER_SHELL") == null) {
            self.layer_shell = self.bind(c.struct_zwlr_layer_shell_v1, name, &c.zwlr_layer_shell_v1_interface, version, 4);
        } else if (eql(u8, iface, "zwlr_foreign_toplevel_manager_v1")) {
            self.toplevel_manager = self.bind(c.struct_zwlr_foreign_toplevel_manager_v1, name, &c.zwlr_foreign_toplevel_manager_v1_interface, version, 3);
            _ = c.zwlr_foreign_toplevel_manager_v1_add_listener(self.toplevel_manager, &toplevel_manager_listener, self);
        } else return;
        self.setupSeatDevices();
    }

    fn onGlobalRemove(data: ?*anyopaque, _: ?*c.struct_wl_registry, name: u32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        for (self.outputs.items, 0..) |o, i| if (o.name == name) {
            c.wl_output_destroy(o.output);
            _ = self.outputs.swapRemove(i);
            return;
        };
    }

    /// Creates per-seat objects once both the seat and the relevant manager exist.
    fn setupSeatDevices(self: *Client) void {
        const seat = self.seat orelse return;
        if (self.data_device == null) if (self.data_device_manager) |m| {
            self.data_device = c.wl_data_device_manager_get_data_device(m, seat);
            _ = c.wl_data_device_add_listener(self.data_device, &data_device_listener, self);
        };
        if (self.text_input == null) if (self.text_input_manager) |m| {
            self.text_input = c.zwp_text_input_manager_v3_get_text_input(m, seat);
            _ = c.zwp_text_input_v3_add_listener(self.text_input, &text_input_listener, self);
        };
        if (self.cursor_shape_device == null) if (self.cursor_shape_manager) |m| if (self.pointer) |p| {
            self.cursor_shape_device = c.wp_cursor_shape_manager_v1_get_pointer(m, p);
        };
    }

    const wm_base_listener: c.struct_xdg_wm_base_listener = .{ .ping = onPing };

    fn onPing(_: ?*anyopaque, base: ?*c.struct_xdg_wm_base, serial: u32) callconv(.c) void {
        c.xdg_wm_base_pong(base, serial);
    }

    // -- outputs ------------------------------------------------------------------------

    const output_listener: c.struct_wl_output_listener = .{
        .geometry = onOutputGeometry,
        .mode = onOutputMode,
        .done = onOutputDone,
        .scale = onOutputScale,
        .name = onOutputName,
        .description = onOutputName,
    };

    fn findOutput(self: *Client, out: ?*c.struct_wl_output) ?*Output {
        for (self.outputs.items) |*o| if (o.output == out) return o;
        return null;
    }

    fn findOutputConst(self: *const Client, out: ?*c.struct_wl_output) ?*const Output {
        for (self.outputs.items) |*o| if (o.output == out) return o;
        return null;
    }

    fn onOutputGeometry(data: ?*anyopaque, out: ?*c.struct_wl_output, x: i32, y: i32, _: i32, _: i32, _: i32, _: [*c]const u8, _: [*c]const u8, _: i32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const o = self.findOutput(out) orelse return;
        o.x = x;
        o.y = y;
    }

    fn onOutputMode(data: ?*anyopaque, out: ?*c.struct_wl_output, flags: u32, w: i32, h: i32, _: i32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const o = self.findOutput(out) orelse return;
        if (flags & c.WL_OUTPUT_MODE_CURRENT != 0) {
            o.width = w;
            o.height = h;
        }
    }

    fn onOutputDone(data: ?*anyopaque, _: ?*c.struct_wl_output) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        for (self.windows.items) |w| w.updateScale();
    }

    fn onOutputScale(data: ?*anyopaque, out: ?*c.struct_wl_output, factor: i32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const o = self.findOutput(out) orelse return;
        o.scale = @max(1, factor);
    }

    fn onOutputName(_: ?*anyopaque, _: ?*c.struct_wl_output, _: [*c]const u8) callconv(.c) void {}

    // -- foreign toplevels (foreground application) ------------------------------------

    const toplevel_manager_listener: c.struct_zwlr_foreign_toplevel_manager_v1_listener = .{ .toplevel = onForeignToplevel, .finished = onToplevelManagerFinished };
    const toplevel_handle_listener: c.struct_zwlr_foreign_toplevel_handle_v1_listener = .{
        .title = ForeignToplevel.onTitle,
        .app_id = ForeignToplevel.onAppId,
        .output_enter = ForeignToplevel.onOutput,
        .output_leave = ForeignToplevel.onOutput,
        .state = ForeignToplevel.onState,
        .done = ForeignToplevel.onDone,
        .closed = ForeignToplevel.onClosed,
        .parent = ForeignToplevel.onParent,
    };

    fn onForeignToplevel(data: ?*anyopaque, _: ?*c.struct_zwlr_foreign_toplevel_manager_v1, handle: ?*c.struct_zwlr_foreign_toplevel_handle_v1) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const h = handle orelse return;
        const t = self.gpa.create(ForeignToplevel) catch return;
        t.* = .{ .client = self, .handle = h };
        self.toplevels.append(self.gpa, t) catch {
            self.gpa.destroy(t);
            c.zwlr_foreign_toplevel_handle_v1_destroy(h);
            return;
        };
        _ = c.zwlr_foreign_toplevel_handle_v1_add_listener(h, &toplevel_handle_listener, t);
    }

    fn onToplevelManagerFinished(data: ?*anyopaque, m: ?*c.struct_zwlr_foreign_toplevel_manager_v1) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        c.zwlr_foreign_toplevel_manager_v1_destroy(m);
        self.toplevel_manager = null;
    }

    fn setActiveToplevel(self: *Client, t: ?*ForeignToplevel) void {
        if (self.active_toplevel == t) return;
        self.active_toplevel = t;
        _ = self.foreground_cb.call({});
    }

    pub fn setForegroundCallback(self: *Client, cb: platform.Callback(void, void)) void {
        self.foreground_cb = cb;
    }

    /// The activated toplevel's app_id (wlr-foreign-toplevel); null without the protocol.
    pub fn foregroundApp(self: *Client, buf: []u8) ?platform.ForegroundApp {
        const t = self.active_toplevel orelse return null;
        const id = t.app_id[0..t.app_id_len];
        if (id.len == 0 or id.len > buf.len) return null;
        @memcpy(buf[0..id.len], id);
        return .{ .id = buf[0..id.len], .name = buf[0..id.len] };
    }

    pub fn displays(self: *Client, out: []platform.Display) usize {
        var n: usize = 0;
        for (self.outputs.items, 0..) |o, i| {
            if (n == out.len) break;
            const scale: f32 = @floatFromInt(o.scale);
            const b: platform.Bounds = .{
                .origin = .{ .x = @floatFromInt(o.x), .y = @floatFromInt(o.y) },
                .size = .{ .width = @as(f32, @floatFromInt(o.width)) / scale, .height = @as(f32, @floatFromInt(o.height)) / scale },
            };
            out[n] = .{ .id = @intCast(i), .bounds = b, .visible_bounds = b, .scale_factor = scale, .primary = i == 0 };
            n += 1;
        }
        return n;
    }

    // -- seat ---------------------------------------------------------------------------

    const seat_listener: c.struct_wl_seat_listener = .{ .capabilities = onSeatCapabilities, .name = onSeatName };

    fn onSeatName(_: ?*anyopaque, _: ?*c.struct_wl_seat, _: [*c]const u8) callconv(.c) void {}

    fn onSeatCapabilities(data: ?*anyopaque, seat: ?*c.struct_wl_seat, caps: u32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const has_pointer = caps & c.WL_SEAT_CAPABILITY_POINTER != 0;
        const has_keyboard = caps & c.WL_SEAT_CAPABILITY_KEYBOARD != 0;
        if (has_pointer and self.pointer == null) {
            self.pointer = c.wl_seat_get_pointer(seat);
            _ = c.wl_pointer_add_listener(self.pointer, &pointer_listener, self);
        } else if (!has_pointer and self.pointer != null) {
            if (self.cursor_shape_device) |d| c.wp_cursor_shape_device_v1_destroy(d);
            self.cursor_shape_device = null;
            c.wl_pointer_destroy(self.pointer);
            self.pointer = null;
        }
        if (has_keyboard and self.kb == null) {
            self.kb = c.wl_seat_get_keyboard(seat);
            _ = c.wl_keyboard_add_listener(self.kb, &keyboard_listener, self);
        } else if (!has_keyboard and self.kb != null) {
            c.wl_keyboard_destroy(self.kb);
            self.kb = null;
        }
        self.setupSeatDevices();
    }

    fn windowForSurface(self: *Client, surface: ?*c.struct_wl_surface) ?*Window {
        const s = surface orelse return null;
        for (self.windows.items) |w| if (w.surface == s) return w;
        return null;
    }

    // -- pointer ------------------------------------------------------------------------

    const pointer_listener: c.struct_wl_pointer_listener = .{
        .enter = onPointerEnter,
        .leave = onPointerLeave,
        .motion = onPointerMotion,
        .button = onPointerButton,
        .axis = onPointerAxis,
        .frame = onPointerFrame,
        .axis_source = onPointerAxisSource,
        .axis_stop = onPointerAxisStop,
        .axis_discrete = onPointerAxisDiscrete,
        .axis_value120 = onPointerAxisValue120,
        .axis_relative_direction = onPointerAxisRelativeDirection,
    };

    fn onPointerEnter(data: ?*anyopaque, _: ?*c.struct_wl_pointer, serial: u32, surface: ?*c.struct_wl_surface, x: c.wl_fixed_t, y: c.wl_fixed_t) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.pointer_enter_serial = serial;
        self.mouse_position = .{ .x = fixedToF32(x), .y = fixedToF32(y) };
        const w = self.windowForSurface(surface) orelse return;
        self.mouse_focus = w;
        self.applyCursor();
        w.common.mouse_position = self.mouse_position;
        w.common.setHovered(true);
        w.common.handleInput(.{ .mouse_move = .{ .position = self.mouse_position, .pressed_button = self.pressed_button, .modifiers = self.modifiers } });
    }

    fn onPointerLeave(data: ?*anyopaque, _: ?*c.struct_wl_pointer, _: u32, surface: ?*c.struct_wl_surface) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const w = self.windowForSurface(surface) orelse return;
        if (self.mouse_focus == w) self.mouse_focus = null;
        w.common.handleInput(.{ .mouse_exited = .{ .position = self.mouse_position, .pressed_button = self.pressed_button, .modifiers = self.modifiers } });
        w.common.setHovered(false);
    }

    fn onPointerMotion(data: ?*anyopaque, _: ?*c.struct_wl_pointer, _: u32, x: c.wl_fixed_t, y: c.wl_fixed_t) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.mouse_position = .{ .x = fixedToF32(x), .y = fixedToF32(y) };
        const w = self.mouse_focus orelse return;
        w.common.mouse_position = self.mouse_position;
        w.common.handleInput(.{ .mouse_move = .{ .position = self.mouse_position, .pressed_button = self.pressed_button, .modifiers = self.modifiers } });
    }

    fn onPointerButton(data: ?*anyopaque, _: ?*c.struct_wl_pointer, serial: u32, _: u32, button: u32, state: u32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.last_serial = serial;
        const b = common.evdevButton(button) orelse return;
        const w = self.mouse_focus orelse return;
        if (state == c.WL_POINTER_BUTTON_STATE_PRESSED) {
            self.last_button_serial = serial;
            self.pressed_button = b;
            const count = self.click.press(b, self.mouse_position, event_loop.monotonicNow());
            w.common.handleInput(.{ .mouse_down = .{ .button = b, .position = self.mouse_position, .modifiers = self.modifiers, .click_count = count, .first_mouse = !w.common.active } });
        } else {
            self.pressed_button = null;
            w.common.handleInput(.{ .mouse_up = .{ .button = b, .position = self.mouse_position, .modifiers = self.modifiers, .click_count = self.click.count } });
        }
    }

    fn axisOf(axis: u32) common.Axis {
        return if (axis == c.WL_POINTER_AXIS_HORIZONTAL_SCROLL) .horizontal else .vertical;
    }

    fn onPointerAxis(data: ?*anyopaque, _: ?*c.struct_wl_pointer, _: u32, axis: u32, value: c.wl_fixed_t) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.scroll.axisValue(axisOf(axis), fixedToF32(value), self.modifiers.shift);
        // wl_pointer < v5 has no frame event: flush immediately.
        if (self.seat_version < 5) onPointerFrame(data, null);
    }

    fn onPointerAxisSource(data: ?*anyopaque, _: ?*c.struct_wl_pointer, source: u32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.scroll.source = switch (source) {
            c.WL_POINTER_AXIS_SOURCE_FINGER => .finger,
            c.WL_POINTER_AXIS_SOURCE_CONTINUOUS => .continuous,
            c.WL_POINTER_AXIS_SOURCE_WHEEL_TILT => .wheel_tilt,
            else => .wheel,
        };
    }

    fn onPointerAxisStop(_: ?*anyopaque, _: ?*c.struct_wl_pointer, _: u32, _: u32) callconv(.c) void {}

    fn onPointerAxisDiscrete(data: ?*anyopaque, _: ?*c.struct_wl_pointer, axis: u32, discrete: i32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.scroll.axisDiscrete(axisOf(axis), discrete, self.modifiers.shift);
    }

    fn onPointerAxisValue120(data: ?*anyopaque, _: ?*c.struct_wl_pointer, axis: u32, value120: i32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.scroll.axisValue120(axisOf(axis), value120, self.modifiers.shift);
    }

    fn onPointerAxisRelativeDirection(_: ?*anyopaque, _: ?*c.struct_wl_pointer, _: u32, _: u32) callconv(.c) void {}

    fn onPointerFrame(data: ?*anyopaque, _: ?*c.struct_wl_pointer) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const delta = self.scroll.frame() orelse return;
        const w = self.mouse_focus orelse return;
        w.common.handleInput(.{ .scroll_wheel = .{ .position = self.mouse_position, .delta = delta, .modifiers = self.modifiers } });
    }

    // -- cursor -------------------------------------------------------------------------

    pub fn setCursorStyle(self: *Client, style: platform.CursorStyle) void {
        if (style == self.cursor_style) return;
        self.cursor_style = style;
        self.applyCursor();
    }

    fn cursorShape(style: platform.CursorStyle) u32 {
        return switch (style) {
            .arrow, .none => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_DEFAULT,
            .ibeam => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_TEXT,
            .crosshair => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CROSSHAIR,
            .closed_hand => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_GRABBING,
            .open_hand => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_GRAB,
            .pointing_hand => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_POINTER,
            .resize_left => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_W_RESIZE,
            .resize_right => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_E_RESIZE,
            .resize_left_right => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_EW_RESIZE,
            .resize_up => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_N_RESIZE,
            .resize_down => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_S_RESIZE,
            .resize_up_down => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NS_RESIZE,
            .resize_column => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_COL_RESIZE,
            .resize_row => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ROW_RESIZE,
            .operation_not_allowed => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_NOT_ALLOWED,
            .drag_link => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_ALIAS,
            .drag_copy => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_COPY,
            .context_menu => c.WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CONTEXT_MENU,
        };
    }

    /// Applies `cursor_style` to the pointer (needs the latest enter serial).
    fn applyCursor(self: *Client) void {
        const pointer = self.pointer orelse return;
        const serial = self.pointer_enter_serial;
        if (self.cursor_style == .none) {
            c.wl_pointer_set_cursor(pointer, serial, null, 0, 0);
            return;
        }
        if (self.cursor_shape_device) |d| {
            c.wp_cursor_shape_device_v1_set_shape(d, serial, cursorShape(self.cursor_style));
            return;
        }
        // wl_cursor theme fallback.
        const scale: i32 = if (self.mouse_focus) |w| @intFromFloat(@ceil(w.common.scale)) else 1;
        if (self.cursor_theme == null or self.cursor_theme_scale != scale) {
            if (self.cursor_theme) |t| c.wl_cursor_theme_destroy(t);
            const size: i32 = blk: {
                const s = std.c.getenv("XCURSOR_SIZE") orelse break :blk 24;
                break :blk std.fmt.parseInt(i32, std.mem.span(s), 10) catch 24;
            };
            self.cursor_theme = c.wl_cursor_theme_load(std.c.getenv("XCURSOR_THEME"), size * scale, self.shm);
            self.cursor_theme_scale = scale;
        }
        const theme = self.cursor_theme orelse return;
        var cursor: [*c]c.struct_wl_cursor = null;
        for (util.cursorNames(self.cursor_style)) |name| {
            cursor = c.wl_cursor_theme_get_cursor(theme, name);
            if (cursor != null) break;
        }
        if (cursor == null) cursor = c.wl_cursor_theme_get_cursor(theme, "left_ptr");
        if (cursor == null or cursor.*.image_count == 0) return;
        const image = cursor.*.images[0];
        const buffer = c.wl_cursor_image_get_buffer(image) orelse return;
        if (self.cursor_surface == null) self.cursor_surface = c.wl_compositor_create_surface(self.compositor);
        const surf = self.cursor_surface orelse return;
        c.wl_surface_set_buffer_scale(surf, scale);
        c.wl_surface_attach(surf, buffer, 0, 0);
        c.wl_surface_damage(surf, 0, 0, std.math.maxInt(i32), std.math.maxInt(i32));
        c.wl_surface_commit(surf);
        c.wl_pointer_set_cursor(pointer, serial, surf, @divTrunc(@as(i32, @intCast(image.*.hotspot_x)), scale), @divTrunc(@as(i32, @intCast(image.*.hotspot_y)), scale));
    }

    // -- keyboard -----------------------------------------------------------------------

    const keyboard_listener: c.struct_wl_keyboard_listener = .{
        .keymap = onKeymap,
        .enter = onKeyboardEnter,
        .leave = onKeyboardLeave,
        .key = onKey,
        .modifiers = onModifiers,
        .repeat_info = onRepeatInfo,
    };

    fn onKeymap(data: ?*anyopaque, _: ?*c.struct_wl_keyboard, format: u32, fd: i32, size: u32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        defer _ = linux.close(fd);
        if (format != c.WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1) return;
        const addr = linux.mmap(null, size, .{ .READ = true }, .{ .TYPE = .PRIVATE }, fd, 0);
        if (linux.errno(addr) != .SUCCESS) return;
        defer _ = linux.munmap(@ptrFromInt(addr), size);
        const text: [*:0]const u8 = @ptrFromInt(addr);
        self.keyboard.setKeymapFromString(text) catch |e| {
            log.err("failed to compile keymap: {t}", .{e});
            return;
        };
        if (self.plat.callbacks.keyboard_layout_change) |f| f(self.plat.callbacks.ctx);
    }

    fn onKeyboardEnter(data: ?*anyopaque, _: ?*c.struct_wl_keyboard, serial: u32, surface: ?*c.struct_wl_surface, _: [*c]c.struct_wl_array) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.last_serial = serial;
        const w = self.windowForSurface(surface) orelse return;
        self.keyboard_focus = w;
        w.common.setActive(true);
    }

    fn onKeyboardLeave(data: ?*anyopaque, _: ?*c.struct_wl_keyboard, _: u32, surface: ?*c.struct_wl_surface) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const w = self.windowForSurface(surface) orelse return;
        if (self.keyboard_focus == w) self.keyboard_focus = null;
        self.stopRepeat();
        self.keyboard.resetCompose();
        w.common.handleIme(.delete_text);
        w.common.setActive(false);
    }

    fn onModifiers(data: ?*anyopaque, _: ?*c.struct_wl_keyboard, _: u32, depressed: u32, latched: u32, locked: u32, group: u32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const old_layout = self.keyboard.layoutIndex();
        self.keyboard.updateMask(depressed, latched, locked, 0, 0, group);
        self.modifiers = self.keyboard.modifiers();
        self.capslock = self.keyboard.capslock();
        if (self.keyboard_focus) |w| {
            w.common.modifiers = self.modifiers;
            w.common.handleInput(.{ .modifiers_changed = .{ .modifiers = self.modifiers, .capslock = self.capslock } });
        }
        if (group != old_layout) if (self.plat.callbacks.keyboard_layout_change) |f| f(self.plat.callbacks.ctx);
    }

    fn onRepeatInfo(data: ?*anyopaque, _: ?*c.struct_wl_keyboard, rate: i32, delay: i32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.repeat_rate = rate;
        self.repeat_delay = delay;
    }

    fn onKey(data: ?*anyopaque, _: ?*c.struct_wl_keyboard, serial: u32, _: u32, key: u32, state: u32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.last_serial = serial;
        const w = self.keyboard_focus orelse return;
        const keycode = key + 8;
        const sym = self.keyboard.keysym(keycode);
        if (keyboard.isModifierKey(sym)) return;

        if (state == c.WL_KEYBOARD_KEY_STATE_PRESSED) {
            var r: keyboard.PressResult = undefined;
            self.keyboard.press(self.modifiers, keycode, &r);
            if (r.ime_insert) |t| w.common.handleIme(.{ .insert_text = t });
            if (r.ime_marked) |t| w.common.handleIme(.{ .set_marked_text = t });

            self.stopRepeat();
            self.repeat_keycode = keycode;
            self.repeat_keystroke = r.keystroke;
            if (self.repeat_rate > 0) {
                self.repeat_timer = self.plat.loop.addTimer(@as(u64, @intCast(@max(self.repeat_delay, 0))) * std.time.ns_per_ms, .{ .ctx = self, .func = onRepeat }) catch null;
            }
            w.common.handleInput(.{ .key_down = .{ .keystroke = r.keystroke.keystroke() } });
        } else {
            const ks = self.keyboard.keystroke(self.modifiers, keycode);
            if (self.repeat_keycode == keycode) self.stopRepeat();
            w.common.handleInput(.{ .key_up = .{ .keystroke = ks.keystroke() } });
        }
    }

    fn stopRepeat(self: *Client) void {
        if (self.repeat_timer) |t| self.plat.loop.cancelTimer(t);
        self.repeat_timer = null;
        self.repeat_keycode = null;
    }

    fn onRepeat(ctx: ?*anyopaque, _: event_loop.TimerId) void {
        const self: *Client = @ptrCast(@alignCast(ctx.?));
        self.repeat_timer = null;
        const w = self.keyboard_focus orelse return;
        if (self.repeat_keycode == null or self.repeat_rate <= 0) return;
        const interval = std.time.ns_per_s / @as(u64, @intCast(self.repeat_rate));
        self.repeat_timer = self.plat.loop.addTimer(interval, .{ .ctx = self, .func = onRepeat }) catch null;
        w.common.handleInput(.{ .key_down = .{ .keystroke = self.repeat_keystroke.keystroke(), .is_held = true } });
    }

    // -- text input v3 (IME) ------------------------------------------------------------

    const text_input_listener: c.struct_zwp_text_input_v3_listener = .{
        .enter = onTextInputEnter,
        .leave = onTextInputLeave,
        .preedit_string = onPreedit,
        .commit_string = onCommitString,
        .delete_surrounding_text = onDeleteSurrounding,
        .done = onTextInputDone,
    };

    fn onTextInputEnter(data: ?*anyopaque, ti: ?*c.struct_zwp_text_input_v3, _: ?*c.struct_wl_surface) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        c.zwp_text_input_v3_enable(ti);
        c.zwp_text_input_v3_set_content_type(ti, c.ZWP_TEXT_INPUT_V3_CONTENT_HINT_NONE, c.ZWP_TEXT_INPUT_V3_CONTENT_PURPOSE_NORMAL);
        if (self.keyboard_focus) |w| if (w.common.imeArea()) |a| setCursorRect(ti, a);
        c.zwp_text_input_v3_commit(ti);
        self.ime_enabled = true;
    }

    fn onTextInputLeave(data: ?*anyopaque, ti: ?*c.struct_zwp_text_input_v3, _: ?*c.struct_wl_surface) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        c.zwp_text_input_v3_disable(ti);
        c.zwp_text_input_v3_commit(ti);
        self.ime_enabled = false;
    }

    fn setCursorRect(ti: ?*c.struct_zwp_text_input_v3, a: platform.Bounds) void {
        c.zwp_text_input_v3_set_cursor_rectangle(ti, @intFromFloat(a.origin.x), @intFromFloat(a.origin.y), @intFromFloat(a.size.width), @intFromFloat(a.size.height));
    }

    fn onPreedit(data: ?*anyopaque, _: ?*c.struct_zwp_text_input_v3, text: [*c]const u8, _: i32, _: i32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        if (self.ime_preedit) |t| self.gpa.free(t);
        self.ime_preedit = if (text != null) self.gpa.dupe(u8, std.mem.span(text)) catch null else null;
    }

    fn onCommitString(data: ?*anyopaque, _: ?*c.struct_zwp_text_input_v3, text: [*c]const u8) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const w = self.keyboard_focus orelse return;
        if (text == null) return;
        const t = std.mem.span(text);
        // gpui: single-byte commits become key presses (keeps vim-style bindings working).
        if (t.len == 1) {
            w.common.handleInput(.{ .key_down = .{ .keystroke = .{ .key = t, .key_char = t } } });
        } else {
            w.common.handleIme(.{ .insert_text = t });
        }
    }

    fn onDeleteSurrounding(_: ?*anyopaque, _: ?*c.struct_zwp_text_input_v3, _: u32, _: u32) callconv(.c) void {}

    fn onTextInputDone(data: ?*anyopaque, ti: ?*c.struct_zwp_text_input_v3, _: u32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const w = self.keyboard_focus orelse return;
        if (self.ime_preedit) |t| {
            w.common.handleIme(.{ .set_marked_text = t });
            self.gpa.free(t);
            self.ime_preedit = null;
            if (w.common.imeArea()) |a| {
                setCursorRect(ti, a);
                c.zwp_text_input_v3_commit(ti);
            }
        } else {
            w.common.handleIme(.delete_text);
        }
    }

    pub fn updateImePosition(self: *Client, bounds: platform.Bounds) void {
        const ti = self.text_input orelse return;
        if (!self.ime_enabled) return;
        setCursorRect(ti, bounds);
        c.zwp_text_input_v3_commit(ti);
    }

    // -- clipboard ----------------------------------------------------------------------

    const data_device_listener: c.struct_wl_data_device_listener = .{
        .data_offer = onDataOffer,
        .enter = onDndEnter,
        .leave = onDndLeave,
        .motion = onDndMotion,
        .drop = onDndDrop,
        .selection = onSelection,
    };
    const data_offer_listener: c.struct_wl_data_offer_listener = .{ .offer = onOfferMime, .source_actions = onOfferActions, .action = onOfferActions };

    fn onDataOffer(data: ?*anyopaque, _: ?*c.struct_wl_data_device, offer: ?*c.struct_wl_data_offer) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const o = offer orelse return;
        self.pending_offers.append(self.gpa, .{ .offer = o }) catch {
            c.wl_data_offer_destroy(o);
            return;
        };
        _ = c.wl_data_offer_add_listener(o, &data_offer_listener, self);
    }

    fn onOfferMime(data: ?*anyopaque, offer: ?*c.struct_wl_data_offer, mime: [*c]const u8) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        const m = std.mem.span(mime);
        for (self.pending_offers.items) |*o| if (o.offer == offer) {
            for (text_mimes, 0..) |tm, rank| if (rank < o.mime_rank and std.mem.eql(u8, m, std.mem.span(tm))) {
                o.mime = tm;
                o.mime_rank = rank;
            };
            if (std.mem.eql(u8, m, "text/uri-list")) o.uri_list = true;
            for (image_mimes, 0..) |im, rank| if (rank < o.image_rank and std.mem.eql(u8, m, std.mem.span(im))) {
                o.image = platform.ClipboardImageFormat.preference[rank];
                o.image_rank = rank;
            };
        };
    }

    fn onOfferActions(_: ?*anyopaque, _: ?*c.struct_wl_data_offer, _: u32) callconv(.c) void {}

    fn takeOffer(self: *Client, offer: ?*c.struct_wl_data_offer) ?Offer {
        for (self.pending_offers.items, 0..) |o, i| if (o.offer == offer) return self.pending_offers.swapRemove(i);
        return null;
    }

    fn onSelection(data: ?*anyopaque, _: ?*c.struct_wl_data_device, offer: ?*c.struct_wl_data_offer) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        if (self.selection) |o| c.wl_data_offer_destroy(o.offer);
        self.selection = self.takeOffer(offer);
    }

    // Drag and drop of files (`text/uri-list`) from other apps (gpui_linux wayland
    // `data_device` handling): the paths are read on enter, then motion / drop /
    // leave map to `FileDropEvent`s.
    fn onDndEnter(data: ?*anyopaque, _: ?*c.struct_wl_data_device, serial: u32, surface: ?*c.struct_wl_surface, x: c.wl_fixed_t, y: c.wl_fixed_t, offer: ?*c.struct_wl_data_offer) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.resetDnd();
        const o = self.takeOffer(offer) orelse return;
        const w = self.windowForSurface(surface) orelse {
            c.wl_data_offer_destroy(o.offer);
            return;
        };
        self.dnd = .{ .offer = o, .window = w, .serial = serial, .position = .{ .x = fixedToF32(x), .y = fixedToF32(y) } };
        if (!o.uri_list) {
            c.wl_data_offer_accept(o.offer, serial, null);
            return;
        }
        c.wl_data_offer_accept(o.offer, serial, "text/uri-list");
        if (c.wl_data_offer_get_version(o.offer) >= 3) c.wl_data_offer_set_actions(o.offer, c.WL_DATA_DEVICE_MANAGER_DND_ACTION_COPY, c.WL_DATA_DEVICE_MANAGER_DND_ACTION_COPY);
        const bytes = self.receiveOffer(o.offer, "text/uri-list") orelse return;
        defer self.gpa.free(bytes);
        x11_uri.parseUriList(self.gpa, bytes, &self.dnd.paths);
        if (self.dnd.paths.items.len == 0) return;
        self.dnd.entered = true;
        const view: []const []const u8 = @ptrCast(self.dnd.paths.items);
        w.common.handleInput(.{ .file_drop = .{ .entered = .{ .position = self.dnd.position, .paths = view } } });
    }
    fn onDndLeave(data: ?*anyopaque, _: ?*c.struct_wl_data_device) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        if (self.dnd.entered) if (self.dnd.window) |w| w.common.handleInput(.{ .file_drop = .exited });
        self.resetDnd();
    }
    fn onDndMotion(data: ?*anyopaque, _: ?*c.struct_wl_data_device, _: u32, x: c.wl_fixed_t, y: c.wl_fixed_t) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        self.dnd.position = .{ .x = fixedToF32(x), .y = fixedToF32(y) };
        if (!self.dnd.entered) return;
        const w = self.dnd.window orelse return;
        w.common.handleInput(.{ .file_drop = .{ .pending = .{ .position = self.dnd.position } } });
    }
    fn onDndDrop(data: ?*anyopaque, _: ?*c.struct_wl_data_device) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        if (self.dnd.entered) if (self.dnd.window) |w| {
            w.common.handleInput(.{ .file_drop = .{ .submit = .{ .position = self.dnd.position } } });
            w.common.handleInput(.{ .file_drop = .exited });
        };
        if (self.dnd.offer) |o| if (self.dnd.entered and c.wl_data_offer_get_version(o.offer) >= 3) c.wl_data_offer_finish(o.offer);
        self.resetDnd();
    }

    fn resetDnd(self: *Client) void {
        if (self.dnd.offer) |o| c.wl_data_offer_destroy(o.offer);
        for (self.dnd.paths.items) |p| self.gpa.free(p);
        self.dnd.paths.deinit(self.gpa);
        self.dnd = .{};
    }

    /// Reads one mime type of an offer (blocking, with the clipboard timeout).
    fn receiveOffer(self: *Client, offer: *c.struct_wl_data_offer, mime: [*:0]const u8) ?[]u8 {
        var fds: [2]linux.fd_t = undefined;
        if (linux.errno(linux.pipe2(&fds, .{ .CLOEXEC = true })) != .SUCCESS) return null;
        c.wl_data_offer_receive(offer, mime, fds[1]);
        _ = linux.close(fds[1]);
        _ = c.wl_display_flush(self.display);
        return util.readFdWithTimeout(self.gpa, fds[0], util.read_timeout_ms) catch null;
    }

    pub fn readClipboardImage(self: *Client, gpa: Allocator) ?platform.ClipboardImage {
        // Our own selection only ever carries text.
        if (self.data_source != null) return null;
        const sel = self.selection orelse return null;
        const format = sel.image orelse return null;
        var fds: [2]linux.fd_t = undefined;
        if (linux.errno(linux.pipe2(&fds, .{ .CLOEXEC = true })) != .SUCCESS) return null;
        c.wl_data_offer_receive(sel.offer, image_mimes[sel.image_rank], fds[1]);
        _ = linux.close(fds[1]);
        _ = c.wl_display_flush(self.display);
        const bytes = util.readFdWithTimeout(gpa, fds[0], util.read_timeout_ms) catch return null;
        if (bytes.len == 0) {
            gpa.free(bytes);
            return null;
        }
        return .{ .format = format, .bytes = bytes };
    }

    const data_source_listener: c.struct_wl_data_source_listener = .{
        .target = onSourceTarget,
        .send = onSourceSend,
        .cancelled = onSourceCancelled,
        .dnd_drop_performed = onSourceNoop,
        .dnd_finished = onSourceNoop,
        .action = onSourceAction,
    };

    fn onSourceTarget(_: ?*anyopaque, _: ?*c.struct_wl_data_source, _: [*c]const u8) callconv(.c) void {}
    fn onSourceNoop(_: ?*anyopaque, _: ?*c.struct_wl_data_source) callconv(.c) void {}
    fn onSourceAction(_: ?*anyopaque, _: ?*c.struct_wl_data_source, _: u32) callconv(.c) void {}

    fn onSourceSend(data: ?*anyopaque, _: ?*c.struct_wl_data_source, _: [*c]const u8, fd: i32) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        util.writeAllAndClose(fd, self.clipboard_text orelse "");
    }

    fn onSourceCancelled(data: ?*anyopaque, source: ?*c.struct_wl_data_source) callconv(.c) void {
        const self: *Client = @ptrCast(@alignCast(data.?));
        c.wl_data_source_destroy(source);
        if (self.data_source == source) {
            self.data_source = null;
            if (self.clipboard_text) |t| self.gpa.free(t);
            self.clipboard_text = null;
        }
    }

    pub fn writeClipboard(self: *Client, text: []const u8) void {
        const mgr = self.data_device_manager orelse return;
        const dev = self.data_device orelse return;
        const copy = self.gpa.dupe(u8, text) catch return;
        if (self.data_source) |s| c.wl_data_source_destroy(s);
        if (self.clipboard_text) |t| self.gpa.free(t);
        self.clipboard_text = copy;
        const source = c.wl_data_device_manager_create_data_source(mgr) orelse return;
        self.data_source = source;
        _ = c.wl_data_source_add_listener(source, &data_source_listener, self);
        for (text_mimes) |m| c.wl_data_source_offer(source, m);
        c.wl_data_device_set_selection(dev, source, self.last_serial);
        _ = c.wl_display_flush(self.display);
    }

    pub fn readClipboard(self: *Client, gpa: Allocator) ?[]u8 {
        // Our own selection: no round trip through the compositor (avoids a self-deadlock).
        if (self.data_source != null) if (self.clipboard_text) |t| return gpa.dupe(u8, t) catch null;
        const sel = self.selection orelse return null;
        const mime = sel.mime orelse return null;
        var fds: [2]linux.fd_t = undefined;
        if (linux.errno(linux.pipe2(&fds, .{ .CLOEXEC = true })) != .SUCCESS) return null;
        c.wl_data_offer_receive(sel.offer, mime, fds[1]);
        _ = linux.close(fds[1]);
        _ = c.wl_display_flush(self.display);
        return util.readFdWithTimeout(gpa, fds[0], util.read_timeout_ms) catch null;
    }

    // -- windows ------------------------------------------------------------------------

    pub fn openWindow(self: *Client, params: platform.WindowParams) !platform.Window {
        const w = try Window.create(self, params);
        return w.window();
    }

    fn removeWindow(self: *Client, w: *Window) void {
        for (self.windows.items, 0..) |item, i| if (item == w) {
            _ = self.windows.orderedRemove(i);
            break;
        };
        if (self.mouse_focus == w) self.mouse_focus = null;
        if (self.keyboard_focus == w) {
            self.keyboard_focus = null;
            self.stopRepeat();
        }
        if (self.dnd.window == w) self.resetDnd();
    }
};

/// One wlr-foreign-toplevel handle (another app's window). Only the app_id and the
/// activated state are kept; titles are ignored (never stored).
const ForeignToplevel = struct {
    client: *Client,
    handle: *c.struct_zwlr_foreign_toplevel_handle_v1,
    app_id: [128]u8 = undefined,
    app_id_len: usize = 0,
    pending_activated: bool = false,

    fn cast(data: ?*anyopaque) *ForeignToplevel {
        return @ptrCast(@alignCast(data.?));
    }
    fn onTitle(_: ?*anyopaque, _: ?*c.struct_zwlr_foreign_toplevel_handle_v1, _: [*c]const u8) callconv(.c) void {}
    fn onAppId(data: ?*anyopaque, _: ?*c.struct_zwlr_foreign_toplevel_handle_v1, id: [*c]const u8) callconv(.c) void {
        const t = cast(data);
        const s = if (id != null) std.mem.span(id) else "";
        t.app_id_len = @min(s.len, t.app_id.len);
        @memcpy(t.app_id[0..t.app_id_len], s[0..t.app_id_len]);
    }
    fn onOutput(_: ?*anyopaque, _: ?*c.struct_zwlr_foreign_toplevel_handle_v1, _: ?*c.struct_wl_output) callconv(.c) void {}
    fn onState(data: ?*anyopaque, _: ?*c.struct_zwlr_foreign_toplevel_handle_v1, states: [*c]c.struct_wl_array) callconv(.c) void {
        const t = cast(data);
        t.pending_activated = false;
        for (arrayU32(states)) |st| if (st == c.ZWLR_FOREIGN_TOPLEVEL_HANDLE_V1_STATE_ACTIVATED) {
            t.pending_activated = true;
        };
    }
    fn onDone(data: ?*anyopaque, _: ?*c.struct_zwlr_foreign_toplevel_handle_v1) callconv(.c) void {
        const t = cast(data);
        const cl = t.client;
        if (t.pending_activated) {
            cl.setActiveToplevel(t);
        } else if (cl.active_toplevel == t) cl.setActiveToplevel(null);
    }
    fn onClosed(data: ?*anyopaque, h: ?*c.struct_zwlr_foreign_toplevel_handle_v1) callconv(.c) void {
        const t = cast(data);
        const cl = t.client;
        for (cl.toplevels.items, 0..) |x, i| if (x == t) {
            _ = cl.toplevels.swapRemove(i);
            break;
        };
        if (cl.active_toplevel == t) cl.setActiveToplevel(null);
        c.zwlr_foreign_toplevel_handle_v1_destroy(h);
        cl.gpa.destroy(t);
    }
    fn onParent(_: ?*anyopaque, _: ?*c.struct_zwlr_foreign_toplevel_handle_v1, _: ?*c.struct_zwlr_foreign_toplevel_handle_v1) callconv(.c) void {}
};

pub const Window = struct {
    client: *Client,
    common: common.Common = .{},
    surface: *c.struct_wl_surface,
    /// xdg-shell role (normal windows, and overlays without layer-shell).
    xdg_surface: ?*c.struct_xdg_surface = null,
    toplevel: ?*c.struct_xdg_toplevel = null,
    /// wlr-layer-shell role (overlay windows when the compositor has it).
    layer_surface: ?*c.struct_zwlr_layer_surface_v1 = null,
    kind: platform.WindowKind = .normal,
    anchor: platform.OverlayAnchor = .{},
    mouse_passthrough: bool = false,
    /// `setVisible(false)`: unmapped (null buffer), no frame callbacks, swapchain parked.
    hidden: bool = false,
    /// `setInputRegion` (surface-local logical px); null = whole surface.
    input_rects: ?[]platform.Bounds = null,
    /// The output the layer surface was created on (null = compositor's choice).
    layer_output: ?*c.struct_wl_output = null,
    decoration: ?*c.struct_zxdg_toplevel_decoration_v1 = null,
    fractional_scale: ?*c.struct_wp_fractional_scale_v1 = null,
    viewport: ?*c.struct_wp_viewport = null,
    blur: ?*c.struct_org_kde_kwin_blur = null,
    frame_callback: ?*c.struct_wl_callback = null,
    /// Until a buffer is committed the surface is unmapped and gets no frame callbacks.
    presented: bool = false,
    first_frame_timer: ?event_loop.TimerId = null,
    presenter: ?Presenter = null,

    configured: bool = false,
    pending_width: i32 = 0,
    pending_height: i32 = 0,
    pending_maximized: bool = false,
    pending_fullscreen: bool = false,
    /// Server-side decorations granted by the compositor.
    server_decorations: bool = false,
    preferred_fractional: ?f32 = null,
    preferred_buffer_scale: ?i32 = null,
    entered_outputs: std.ArrayList(*c.struct_wl_output) = .empty,
    min_size: ?platform.Size = null,
    client_inset: f32 = 0,
    title_z: ?[:0]u8 = null,

    fn create(client: *Client, params: platform.WindowParams) !*Window {
        const gpa = client.gpa;
        const surface = c.wl_compositor_create_surface(client.compositor) orelse return error.WaylandSurface;
        errdefer c.wl_surface_destroy(surface);

        const self = try gpa.create(Window);
        errdefer gpa.destroy(self);
        self.* = .{ .client = client, .surface = surface, .min_size = params.min_size, .kind = params.kind, .anchor = params.anchor orelse .{} };
        self.common.size = params.bounds.size;
        self.common.background = params.background;
        _ = c.wl_surface_add_listener(surface, &surface_listener, self);

        if (params.kind == .overlay and client.layer_shell != null) {
            // Overlay layer, pinned to a corner by anchors + margins, never focused.
            const output: ?*c.struct_wl_output = if (params.display_id) |d| (if (d < client.outputs.items.len) client.outputs.items[d].output else null) else null;
            const ns = params.app_id orelse "zpui-overlay";
            const ns_z = try gpa.dupeSentinel(u8, ns, 0);
            defer gpa.free(ns_z);
            const layer = c.zwlr_layer_shell_v1_get_layer_surface(client.layer_shell, surface, output, c.ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY, ns_z) orelse return error.WaylandSurface;
            self.layer_surface = layer;
            self.layer_output = output;
            _ = c.zwlr_layer_surface_v1_add_listener(layer, &layer_listener, self);
            self.applyLayerState(self.common.size);
        } else {
            const xdg_surface = c.xdg_wm_base_get_xdg_surface(client.wm_base, surface) orelse return error.WaylandSurface;
            errdefer c.xdg_surface_destroy(xdg_surface);
            const toplevel = c.xdg_surface_get_toplevel(xdg_surface) orelse return error.WaylandSurface;
            errdefer c.xdg_toplevel_destroy(toplevel);
            self.xdg_surface = xdg_surface;
            self.toplevel = toplevel;
            _ = c.xdg_surface_add_listener(xdg_surface, &xdg_surface_listener, self);
            _ = c.xdg_toplevel_add_listener(toplevel, &toplevel_listener, self);

            if (params.titlebar) |tb| self.setTitleZ(tb.title);
            if (params.app_id) |id| {
                const z = try gpa.dupeSentinel(u8, id, 0);
                defer gpa.free(z);
                c.xdg_toplevel_set_app_id(toplevel, z);
            }
            if (params.kind == .overlay) {
                // No layer-shell (GNOME): a plain fixed-size toplevel; the compositor
                // places it and keeps it in the normal stacking order (best effort).
                const w: i32 = @intFromFloat(params.bounds.size.width);
                const h: i32 = @intFromFloat(params.bounds.size.height);
                c.xdg_toplevel_set_min_size(toplevel, w, h);
                c.xdg_toplevel_set_max_size(toplevel, w, h);
            } else if (params.min_size) |m| c.xdg_toplevel_set_min_size(toplevel, @intFromFloat(m.width), @intFromFloat(m.height));

            if (client.decoration_manager) |m| {
                self.decoration = c.zxdg_decoration_manager_v1_get_toplevel_decoration(m, toplevel);
                _ = c.zxdg_toplevel_decoration_v1_add_listener(self.decoration, &decoration_listener, self);
                c.zxdg_toplevel_decoration_v1_set_mode(self.decoration, if (params.decorations == .client or params.kind == .overlay)
                    c.ZXDG_TOPLEVEL_DECORATION_V1_MODE_CLIENT_SIDE
                else
                    c.ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE);
            }
        }
        if (params.mouse_passthrough) self.applyPassthrough(true);
        if (client.fractional_scale_manager != null and client.viewporter != null) {
            self.fractional_scale = c.wp_fractional_scale_manager_v1_get_fractional_scale(client.fractional_scale_manager, surface);
            _ = c.wp_fractional_scale_v1_add_listener(self.fractional_scale, &fractional_listener, self);
            self.viewport = c.wp_viewporter_get_viewport(client.viewporter, surface);
        }
        self.applyBackground();

        try client.windows.append(gpa, self);
        errdefer _ = client.windows.pop();

        // Initial commit without a buffer; the compositor answers with a configure.
        // A window created hidden stays without a role commit until `setVisible(true)`.
        self.hidden = !params.show;
        if (!self.hidden) {
            c.wl_surface_commit(surface);
            _ = c.wl_display_roundtrip(client.display);
        }

        const dev = self.common.deviceSize();
        self.presenter = Presenter.init(gpa, .{ .wayland = .{ .display = client.display, .surface = surface } }, dev.width, dev.height, params.background != .opaque_) catch |e| blk: {
            log.err("renderer init failed: {t}; window will not draw", .{e});
            break :blk null;
        };
        if (self.configured) self.common.requestFrame(true);
        return self;
    }

    fn setTitleZ(self: *Window, title: []const u8) void {
        const z = self.client.gpa.dupeSentinel(u8, title, 0) catch return;
        if (self.title_z) |t| self.client.gpa.free(t);
        self.title_z = z;
        if (self.toplevel) |t| c.xdg_toplevel_set_title(t, z);
    }

    fn closeWindow(self: *Window) void {
        const gpa = self.client.gpa;
        self.client.removeWindow(self);
        if (self.client.plat.atspi) |br| br.removeWindow(&self.common);
        if (self.first_frame_timer) |t| self.client.plat.loop.cancelTimer(t);
        if (self.presenter) |*p| p.deinit(gpa);
        if (self.frame_callback) |cb| c.wl_callback_destroy(cb);
        if (self.blur) |b| c.org_kde_kwin_blur_release(b);
        if (self.viewport) |v| c.wp_viewport_destroy(v);
        if (self.fractional_scale) |f| c.wp_fractional_scale_v1_destroy(f);
        if (self.decoration) |d| c.zxdg_toplevel_decoration_v1_destroy(d);
        if (self.toplevel) |t| c.xdg_toplevel_destroy(t);
        if (self.xdg_surface) |x| c.xdg_surface_destroy(x);
        if (self.layer_surface) |l| c.zwlr_layer_surface_v1_destroy(l);
        if (self.input_rects) |r| gpa.free(r);
        c.wl_surface_destroy(self.surface);
        _ = c.wl_display_flush(self.client.display);
        self.entered_outputs.deinit(gpa);
        if (self.title_z) |t| gpa.free(t);
        self.common.notifyClosed();
        gpa.destroy(self);
    }

    // -- scale --------------------------------------------------------------------------

    fn currentScale(self: *const Window) f32 {
        if (self.preferred_fractional) |f| return f;
        if (self.preferred_buffer_scale) |s| return @floatFromInt(s);
        var s: i32 = 1;
        for (self.entered_outputs.items) |o| {
            if (self.client.findOutputConst(o)) |out| s = @max(s, out.scale);
        }
        return @floatFromInt(s);
    }

    fn updateScale(self: *Window) void {
        self.applySize(self.common.size);
    }

    /// Applies a logical size (and the current scale) to the surface and the core.
    fn applySize(self: *Window, size: platform.Size) void {
        const scale = self.currentScale();
        if (self.viewport) |v| {
            c.wp_viewport_set_destination(v, @intFromFloat(@max(1, @round(size.width))), @intFromFloat(@max(1, @round(size.height))));
        } else {
            c.wl_surface_set_buffer_scale(self.surface, @intFromFloat(scale));
        }
        if (self.common.setSizeAndScale(size, scale)) {
            self.applyOpaqueRegion();
            if (self.configured) self.common.requestFrame(true);
        }
    }

    fn applyOpaqueRegion(self: *Window) void {
        if (self.common.background != .opaque_) {
            c.wl_surface_set_opaque_region(self.surface, null);
            return;
        }
        const region = c.wl_compositor_create_region(self.client.compositor) orelse return;
        defer c.wl_region_destroy(region);
        c.wl_region_add(region, 0, 0, @intFromFloat(self.common.size.width), @intFromFloat(self.common.size.height));
        c.wl_surface_set_opaque_region(self.surface, region);
    }

    fn applyBackground(self: *Window) void {
        const want_blur = self.common.background == .blurred;
        if (want_blur and self.blur == null) {
            if (self.client.blur_manager) |m| {
                self.blur = c.org_kde_kwin_blur_manager_create(m, self.surface);
                c.org_kde_kwin_blur_set_region(self.blur, null); // whole surface
                c.org_kde_kwin_blur_commit(self.blur);
            }
        } else if (!want_blur and self.blur != null) {
            c.org_kde_kwin_blur_release(self.blur);
            self.blur = null;
            if (self.client.blur_manager) |m| c.org_kde_kwin_blur_manager_unset(m, self.surface);
        }
        self.applyOpaqueRegion();
    }

    // -- listeners ----------------------------------------------------------------------

    const surface_listener: c.struct_wl_surface_listener = .{
        .enter = onSurfaceEnter,
        .leave = onSurfaceLeave,
        .preferred_buffer_scale = onPreferredBufferScale,
        .preferred_buffer_transform = onPreferredBufferTransform,
    };

    fn onSurfaceEnter(data: ?*anyopaque, _: ?*c.struct_wl_surface, output: ?*c.struct_wl_output) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        const o = output orelse return;
        self.entered_outputs.append(self.client.gpa, o) catch return;
        self.updateScale();
    }

    fn onSurfaceLeave(data: ?*anyopaque, _: ?*c.struct_wl_surface, output: ?*c.struct_wl_output) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        for (self.entered_outputs.items, 0..) |o, i| if (o == output) {
            _ = self.entered_outputs.swapRemove(i);
            break;
        };
        self.updateScale();
    }

    fn onPreferredBufferScale(data: ?*anyopaque, _: ?*c.struct_wl_surface, factor: i32) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        self.preferred_buffer_scale = @max(1, factor);
        self.updateScale();
    }

    fn onPreferredBufferTransform(_: ?*anyopaque, _: ?*c.struct_wl_surface, _: u32) callconv(.c) void {}

    const fractional_listener: c.struct_wp_fractional_scale_v1_listener = .{ .preferred_scale = onPreferredScale };

    fn onPreferredScale(data: ?*anyopaque, _: ?*c.struct_wp_fractional_scale_v1, scale: u32) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        self.preferred_fractional = @as(f32, @floatFromInt(scale)) / 120.0;
        self.updateScale();
    }

    const decoration_listener: c.struct_zxdg_toplevel_decoration_v1_listener = .{ .configure = onDecorationConfigure };

    fn onDecorationConfigure(data: ?*anyopaque, _: ?*c.struct_zxdg_toplevel_decoration_v1, mode: u32) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        self.server_decorations = mode == c.ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE;
    }

    const toplevel_listener: c.struct_xdg_toplevel_listener = .{
        .configure = onToplevelConfigure,
        .close = onToplevelClose,
        .configure_bounds = onConfigureBounds,
        .wm_capabilities = onWmCapabilities,
    };

    fn onToplevelConfigure(data: ?*anyopaque, _: ?*c.struct_xdg_toplevel, width: i32, height: i32, states: [*c]c.struct_wl_array) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        self.pending_width = width;
        self.pending_height = height;
        self.pending_maximized = false;
        self.pending_fullscreen = false;
        for (arrayU32(states)) |s| switch (s) {
            c.XDG_TOPLEVEL_STATE_MAXIMIZED => self.pending_maximized = true,
            c.XDG_TOPLEVEL_STATE_FULLSCREEN => self.pending_fullscreen = true,
            else => {},
        };
    }

    fn onToplevelClose(data: ?*anyopaque, _: ?*c.struct_xdg_toplevel) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        if (self.common.shouldClose()) self.closeWindow();
    }

    fn onConfigureBounds(_: ?*anyopaque, _: ?*c.struct_xdg_toplevel, _: i32, _: i32) callconv(.c) void {}
    fn onWmCapabilities(_: ?*anyopaque, _: ?*c.struct_xdg_toplevel, _: [*c]c.struct_wl_array) callconv(.c) void {}

    const xdg_surface_listener: c.struct_xdg_surface_listener = .{ .configure = onSurfaceConfigure };

    fn onSurfaceConfigure(data: ?*anyopaque, xdg_surface: ?*c.struct_xdg_surface, serial: u32) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        c.xdg_surface_ack_configure(xdg_surface, serial);
        self.common.maximized = self.pending_maximized;
        self.common.fullscreen = self.pending_fullscreen;
        var size = self.common.size;
        if (self.pending_width > 0 and self.pending_height > 0) {
            size = .{ .width = @floatFromInt(self.pending_width), .height = @floatFromInt(self.pending_height) };
        }
        if (self.min_size) |m| {
            size.width = @max(size.width, m.width);
            size.height = @max(size.height, m.height);
        }
        const first = !self.configured;
        self.configured = true;
        self.applySize(size);
        // A configure always needs a new buffer committed in response.
        if (first or self.presenter != null) self.common.requestFrame(true);
    }

    // -- layer shell / overlay ----------------------------------------------------------

    const layer_listener: c.struct_zwlr_layer_surface_v1_listener = .{ .configure = onLayerConfigure, .closed = onLayerClosed };

    /// Size, anchors, margins, no keyboard focus, no exclusive zone (the margins are
    /// measured from other panels' exclusive zones: the work area).
    fn applyLayerState(self: *Window, size: platform.Size) void {
        const l = self.layer_surface orelse return;
        const p = platform.desktop.layerPlacement(self.anchor);
        c.zwlr_layer_surface_v1_set_size(l, @intFromFloat(@max(1, @round(size.width))), @intFromFloat(@max(1, @round(size.height))));
        c.zwlr_layer_surface_v1_set_anchor(l, p.anchor);
        c.zwlr_layer_surface_v1_set_margin(l, p.margin[0], p.margin[1], p.margin[2], p.margin[3]);
        c.zwlr_layer_surface_v1_set_keyboard_interactivity(l, c.ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_NONE);
        c.zwlr_layer_surface_v1_set_exclusive_zone(l, 0);
    }

    fn onLayerConfigure(data: ?*anyopaque, layer: ?*c.struct_zwlr_layer_surface_v1, serial: u32, width: u32, height: u32) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        c.zwlr_layer_surface_v1_ack_configure(layer, serial);
        var size = self.common.size;
        if (width > 0 and height > 0) size = .{ .width = @floatFromInt(width), .height = @floatFromInt(height) };
        const first = !self.configured;
        self.configured = true;
        self.applySize(size);
        if (first or self.presenter != null) self.common.requestFrame(true);
    }

    fn onLayerClosed(data: ?*anyopaque, _: ?*c.struct_zwlr_layer_surface_v1) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        self.closeWindow();
    }

    /// Empty input region = clicks go to whatever is below; the `setInputRegion` rects;
    /// null = the whole surface.
    fn applyPassthrough(self: *Window, on: bool) void {
        self.mouse_passthrough = on;
        if (on or self.input_rects != null) {
            const region = c.wl_compositor_create_region(self.client.compositor) orelse return;
            defer c.wl_region_destroy(region);
            if (!on) for (self.input_rects.?) |r| c.wl_region_add(region, @intFromFloat(@floor(r.origin.x)), @intFromFloat(@floor(r.origin.y)), @intFromFloat(@ceil(r.size.width)), @intFromFloat(@ceil(r.size.height)));
            c.wl_surface_set_input_region(self.surface, region);
        } else c.wl_surface_set_input_region(self.surface, null);
        // Double-buffered: applied by the next commit (the next frame, or this one).
        if (self.configured and !self.hidden) c.wl_surface_commit(self.surface);
    }

    const frame_listener: c.struct_wl_callback_listener = .{ .done = onFrameDone };

    fn onFrameDone(data: ?*anyopaque, cb: ?*c.struct_wl_callback, _: u32) callconv(.c) void {
        const self: *Window = @ptrCast(@alignCast(data.?));
        c.wl_callback_destroy(cb);
        if (self.frame_callback == cb) self.frame_callback = null;
        self.common.requestFrame(false);
    }

    /// Arms a frame callback on the surface's pending state (sent by the next commit).
    fn armFrameCallback(self: *Window) bool {
        if (self.frame_callback != null) return false;
        self.frame_callback = c.wl_surface_frame(self.surface);
        _ = c.wl_callback_add_listener(self.frame_callback, &frame_listener, self);
        return true;
    }

    // -- platform.Window vtable ---------------------------------------------------------

    fn window(self: *Window) platform.Window {
        return .{ .ptr = self, .vtable = &vtable };
    }

    fn cast(ptr: *anyopaque) *Window {
        return @ptrCast(@alignCast(ptr));
    }

    const vtable: platform.Window.VTable = .{
        .setCallbacks = setCallbacks,
        .bounds = bounds,
        .contentSize = contentSize,
        .resize = resize,
        .scaleFactor = scaleFactor,
        .appearance = appearance,
        .mousePosition = mousePosition,
        .modifiers = modifiersFn,
        .isActive = isActive,
        .isHovered = isHovered,
        .isFullscreen = isFullscreen,
        .isMaximized = isMaximized,
        .setInputHandler = setInputHandler,
        .setTitle = setTitle,
        .setBackgroundAppearance = setBackgroundAppearance,
        .activate = activate,
        .minimize = minimize,
        .zoom = zoom,
        .toggleFullscreen = toggleFullscreen,
        .startWindowMove = startWindowMove,
        .startWindowResize = startWindowResize,
        .setClientInset = setClientInset,
        .requestFrame = requestFrame,
        .draw = draw,
        .spriteAtlas = spriteAtlas,
        .updateImePosition = updateImePosition,
        .close = close,
        .a11yUpdate = a11yUpdate,
        .setMousePassthrough = setMousePassthrough,
        .setAnchor = setAnchor,
        .setVisible = setVisible,
        .setInputRegion = setInputRegion,
        .screenMousePosition = screenMousePosition,
    };

    fn setMousePassthrough(ptr: *anyopaque, on: bool) void {
        cast(ptr).applyPassthrough(on);
        _ = c.wl_display_flush(cast(ptr).client.display);
    }
    fn setInputRegion(ptr: *anyopaque, rects: ?[]const platform.Bounds) void {
        const self = cast(ptr);
        const gpa = self.client.gpa;
        if (self.input_rects) |r| gpa.free(r);
        self.input_rects = if (rects) |r| gpa.dupe(platform.Bounds, r) catch null else null;
        self.applyPassthrough(self.mouse_passthrough);
        _ = c.wl_display_flush(self.client.display);
    }
    /// Layer surfaces: output position + anchored origin (from anchor, margins and the
    /// output's logical size; exclusive zones of panels are not known to clients) +
    /// the surface-local pointer. xdg-toplevels never learn their position: null.
    fn screenMousePosition(ptr: *anyopaque) ?platform.Point {
        const self = cast(ptr);
        if (self.layer_surface == null) return null;
        const cl = self.client;
        const out_ptr = self.layer_output orelse (if (self.entered_outputs.items.len > 0) self.entered_outputs.items[0] else null);
        var displays: [16]platform.Display = undefined;
        const n = cl.displays(&displays);
        var found: ?platform.Bounds = null;
        for (cl.outputs.items, 0..) |o, i| if (i < n and (out_ptr == null or o.output == out_ptr)) {
            found = displays[i].bounds;
            break;
        };
        const b = found orelse return null;
        const origin = platform.desktop.anchoredOrigin(self.anchor, b, self.common.size);
        return .{ .x = origin.x + self.common.mouse_position.x, .y = origin.y + self.common.mouse_position.y };
    }
    fn setAnchor(ptr: *anyopaque, anchor: platform.OverlayAnchor, _: ?u32) void {
        // The output is fixed when the layer surface is created (`WindowParams.display_id`).
        const self = cast(ptr);
        self.anchor = anchor;
        if (self.layer_surface == null) return; // xdg-toplevel: clients cannot position
        self.applyLayerState(self.common.size);
        if (self.configured and !self.hidden) c.wl_surface_commit(self.surface);
        _ = c.wl_display_flush(self.client.display);
    }
    fn setVisible(ptr: *anyopaque, visible: bool) void {
        const self = cast(ptr);
        if (self.hidden == !visible) return;
        self.hidden = !visible;
        if (!visible) {
            // Unmap: drop the swapchain, attach no buffer. The surface returns to its
            // pre-configure state; showing re-commits and waits for a configure.
            if (self.first_frame_timer) |t| self.client.plat.loop.cancelTimer(t);
            self.first_frame_timer = null;
            if (self.frame_callback) |cb| c.wl_callback_destroy(cb);
            self.frame_callback = null;
            if (self.presenter) |*p| p.park();
            c.wl_surface_attach(self.surface, null, 0, 0);
            c.wl_surface_commit(self.surface);
            self.configured = false;
            self.presented = false;
        } else {
            self.applyLayerState(self.common.size);
            c.wl_surface_commit(self.surface);
        }
        _ = c.wl_display_flush(self.client.display);
    }

    fn setCallbacks(ptr: *anyopaque, cbs: platform.WindowCallbacks) void {
        const self = cast(ptr);
        self.common.callbacks = cbs;
        // Accessibility: windows with core callbacks are exposed over AT-SPI (atspi.zig).
        if (self.client.plat.atspi) |br| if (cbs.ctx != null) br.addWindow(&self.common, self.window()) else br.removeWindow(&self.common);
    }
    fn a11yUpdate(ptr: *anyopaque, update: platform.a11y.Update) void {
        const self = cast(ptr);
        if (self.client.plat.atspi) |br| br.update(&self.common, update);
    }
    fn bounds(ptr: *anyopaque) platform.Bounds {
        // Wayland never reveals global window positions.
        return .{ .origin = .zero, .size = cast(ptr).common.size };
    }
    fn contentSize(ptr: *anyopaque) platform.Size {
        return cast(ptr).common.size;
    }
    fn resize(ptr: *anyopaque, size: platform.Size) void {
        // Clients may pick their own size only while not maximized/fullscreen.
        const self = cast(ptr);
        if (self.common.maximized or self.common.fullscreen) return;
        if (self.layer_surface != null) {
            // The anchors keep the corner fixed; set_size rides on the next frame's commit
            // together with the new-size buffer (no separate commit, no flicker).
            self.applyLayerState(size);
        } else if (self.kind == .overlay) if (self.toplevel) |t| {
            c.xdg_toplevel_set_min_size(t, @intFromFloat(size.width), @intFromFloat(size.height));
            c.xdg_toplevel_set_max_size(t, @intFromFloat(size.width), @intFromFloat(size.height));
        };
        self.applySize(size);
    }
    fn scaleFactor(ptr: *anyopaque) f32 {
        return cast(ptr).common.scale;
    }
    fn appearance(ptr: *anyopaque) platform.WindowAppearance {
        return cast(ptr).client.plat.appearance;
    }
    fn mousePosition(ptr: *anyopaque) platform.Point {
        return cast(ptr).common.mouse_position;
    }
    fn modifiersFn(ptr: *anyopaque) input.Modifiers {
        return cast(ptr).client.modifiers;
    }
    fn isActive(ptr: *anyopaque) bool {
        return cast(ptr).common.active;
    }
    fn isHovered(ptr: *anyopaque) bool {
        return cast(ptr).common.hovered;
    }
    fn isFullscreen(ptr: *anyopaque) bool {
        return cast(ptr).common.fullscreen;
    }
    fn isMaximized(ptr: *anyopaque) bool {
        return cast(ptr).common.maximized;
    }
    fn setInputHandler(ptr: *anyopaque, h: ?platform.InputHandler) void {
        cast(ptr).common.input_handler = h;
    }
    fn setTitle(ptr: *anyopaque, title: []const u8) void {
        cast(ptr).setTitleZ(title);
    }
    fn setBackgroundAppearance(ptr: *anyopaque, bg: platform.WindowBackgroundAppearance) void {
        const self = cast(ptr);
        self.common.background = bg;
        self.applyBackground();
    }
    fn activate(_: *anyopaque) void {
        // Needs xdg-activation with a token; not supported yet.
    }
    fn minimize(ptr: *anyopaque) void {
        if (cast(ptr).toplevel) |t| c.xdg_toplevel_set_minimized(t);
    }
    fn zoom(ptr: *anyopaque) void {
        const self = cast(ptr);
        const t = self.toplevel orelse return;
        if (self.common.maximized) c.xdg_toplevel_unset_maximized(t) else c.xdg_toplevel_set_maximized(t);
    }
    fn toggleFullscreen(ptr: *anyopaque) void {
        const self = cast(ptr);
        const t = self.toplevel orelse return;
        if (self.common.fullscreen) c.xdg_toplevel_unset_fullscreen(t) else c.xdg_toplevel_set_fullscreen(t, null);
    }
    fn startWindowMove(ptr: *anyopaque) void {
        const self = cast(ptr);
        const t = self.toplevel orelse return;
        c.xdg_toplevel_move(t, self.client.seat, self.client.last_button_serial);
    }
    fn startWindowResize(ptr: *anyopaque, edge: platform.ResizeEdge) void {
        const self = cast(ptr);
        const t = self.toplevel orelse return;
        const e: u32 = switch (edge) {
            .top => c.XDG_TOPLEVEL_RESIZE_EDGE_TOP,
            .top_right => c.XDG_TOPLEVEL_RESIZE_EDGE_TOP_RIGHT,
            .right => c.XDG_TOPLEVEL_RESIZE_EDGE_RIGHT,
            .bottom_right => c.XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_RIGHT,
            .bottom => c.XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM,
            .bottom_left => c.XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_LEFT,
            .left => c.XDG_TOPLEVEL_RESIZE_EDGE_LEFT,
            .top_left => c.XDG_TOPLEVEL_RESIZE_EDGE_TOP_LEFT,
        };
        c.xdg_toplevel_resize(t, self.client.seat, self.client.last_button_serial, e);
    }
    fn setClientInset(ptr: *anyopaque, inset: f32) void {
        // Shadow/resize border drawn by the app for CSD: exclude it from the window geometry.
        const self = cast(ptr);
        self.client_inset = inset;
        const i: i32 = @intFromFloat(inset);
        const w: i32 = @intFromFloat(self.common.size.width);
        const h: i32 = @intFromFloat(self.common.size.height);
        if (self.xdg_surface) |x| if (i > 0 and w > 2 * i and h > 2 * i) c.xdg_surface_set_window_geometry(x, i, i, w - 2 * i, h - 2 * i);
    }
    fn requestFrame(ptr: *anyopaque) void {
        const self = cast(ptr);
        if (self.hidden) return;
        if (!self.presented) {
            // Unmapped surfaces never get frame callbacks: tick from the event loop instead.
            if (self.first_frame_timer == null)
                self.first_frame_timer = self.client.plat.loop.addTimer(0, .{ .ctx = self, .func = onFirstFrameTimer }) catch null;
            return;
        }
        // An empty commit delivers the callback at the compositor's next repaint.
        if (self.armFrameCallback()) c.wl_surface_commit(self.surface);
    }
    fn draw(ptr: *anyopaque, scene: *const scene_mod.Scene) anyerror!void {
        const self = cast(ptr);
        const p = if (self.presenter) |*p| p else return error.NoRenderer;
        if (!self.configured or self.hidden) return; // no buffer may be attached before the first configure
        // Throttle to the compositor: the present's commit carries this frame callback.
        _ = self.armFrameCallback();
        const dev = self.common.deviceSize();
        try p.draw(scene, dev.width, dev.height, self.common.scale);
        self.presented = true;
    }

    fn onFirstFrameTimer(ctx: ?*anyopaque, _: event_loop.TimerId) void {
        const self: *Window = @ptrCast(@alignCast(ctx.?));
        self.first_frame_timer = null;
        if (self.configured) self.common.requestFrame(!self.presented) else requestFrame(self);
    }
    fn spriteAtlas(ptr: *anyopaque) *atlas_mod.Atlas {
        const self = cast(ptr);
        if (self.presenter) |*p| return p.atlas();
        @panic("window has no renderer");
    }
    fn updateImePosition(ptr: *anyopaque, b: platform.Bounds) void {
        cast(ptr).client.updateImePosition(b);
    }
    fn close(ptr: *anyopaque) void {
        cast(ptr).closeWindow();
    }
};
